### ISSUE TITLE
Which license is this released?

### ISSUE THREAD

**Issue by ifraixedes** [khalwat/seomatic#1]
I couldn't see the license of this repo; if you have released this work with one, can you make it more clear in the REAME or adding a LICENSE file?

Otherwise it would be good if you decide for one, whichever you want open source or not, and make it clearly visible.

**Comment by sg-modlab** [comment]
This is important. Don't want to report and engage with issues and/or try to fix them without a license. Open source? Beta before commercial? ...

**Comment by khalwat** [comment]
Well, I haven't decided.  It's possible that when Craft 3 comes out, I will sell it in the Craft Store.  Suggestions for a license to use with that possibility in mind?

I don't really consider it "beta" because I use it on production sites myself.

**Comment by sg-modlab** [comment]
I am not sure the right model to go from an open source license to commercial.

I guess this means that we will just report issues for you to fix in the meantime if we want to give this plugin a go.

Thanks for the quick reply and transparency.

**Comment by khalwat** [comment]
No problem. Still a chance it'll be OSS; I just want to leave the options open.

**Comment by ifraixedes** [comment]
I'm not an expert on this kind of mix and match licenses, but I guess that you can release it for non-commercial and if somebody want to use commercial then pay whatever you estimate.

**Comment by khalwat** [comment]
Just to clarify: the version for Craft 2.4 & 2.5 will always be free. But I do want to retain ownership/copyright on it in the event that I do decide to make it a paid plugin for Craft 3. 

It'll need to be somewhat rewritten then anyway, and with the advent of the Craft Store, I think I'm not alone in this. I think we are at least a year off from that tho, probably more.

**Comment by khalwat** [comment]
I added the MIT license to my other github repos via LICENSE.txt files.  Thanks for the heads up!

**Comment by khalwat** [comment]
I added a LICENSE.txt to the 1.0.5 release to clarify things.
