### ISSUE TITLE
N.B.: Re-save your Sections after updating to 1.1.21 or later, from 1.1.20 or earlier,  if you use SEO Entry Metas

### ISSUE THREAD

**Issue by khalwat** [khalwat/seomatic#100]
I made a change to SEOmatic that saves the data in the SEOmatic Meta FieldType when an entry is saved.  This gives two nice benefits:
1. It's more performant, especially if you're using Extract Keywords, because the parsing is done at save time, not at run time
2. It allows you to access `entry.someSeomaticMetaField.seoDescription` and such in while looping through the entries, because the parsing of the data isn't done at runtime

The downside is that you'll need to re-save any Sections that use SEOmatic Meta FieldTypes so that the data is properly populated.  Fortunately, this is easy: you can do this via Settings → Edit My Section → hit Save.  You'll see a notice about it re-saving the elements in that section, and you should be good to go.

**Comment by bossanova808** [comment]
Worth noting here that the does not work for Commerce Product/Types - you'll (at least currently) have to save each product manually again to get this to work.

(I've sent a feature request to Luke so hopefully this will change!)
