### ISSUE TITLE
SEO Title UI

### ISSUE THREAD

**Issue by AbbeyDesign** [khalwat/seomatic#101]
When I enter a custom title like {title} | {jobTitle} it works as it should. It shows up correctly on the front end.

If I return to the edit page, that field is now blank but still works on the front end.
<img width="448" alt="seomatic_ui" src="https://cloud.githubusercontent.com/assets/11862097/16363975/0a861f0a-3bdc-11e6-805d-01f72a4f626c.png">

**Comment by khalwat** [comment]
Fixed in 1.1.22
