### ISSUE TITLE
In SEO entry meta the content of a global variable does no longer display in the source code of an entry

### ISSUE THREAD

**Issue by winterstetter** [khalwat/seomatic#103]
1.1.21 / 1.1.22

In SEO entry meta a global variable ({{ globals.globalMyGlobal }}) used in title and description (Twig code in the FieldType) **does no longer display** its content in the source code of an entry … Would be great if you could bring back the functionality to do so. Thanks!

**Comment by khalwat** [comment]
Add accessors for seoTitleUnparsed, seoDescriptionUnparsed, and seoKeywordsUnparsed into `develop`:

https://github.com/nystudio107/seomatic/tree/develop

So if you want the unparsed contents of the FieldType, you'll have to do something like `{{ entry.seomaticFieldType.seoTitleUnparsed() | raw }}`
