### ISSUE TITLE
Individual title on homepage

### ISSUE THREAD

**Issue by chives-office** [khalwat/seomatic#104]
Hi nystudio107,
is it possible for SEOMatics in the CraftCMS to overwrite the homepage html title including the defined suffix? Especially for the homepage I want to have an individual line of content for the title not using the usual automatic "- pagename" suffix of all the sub pages.

Thanks for your help!

Kind regards,
Guido of CHIVES

**Comment by khalwat** [comment]
sure, you can easily do that via Twig:

https://github.com/nystudio107/seomatic/wiki/08.-Dynamic-Twig-SEO-Meta

**Comment by emcacace** [comment]
I'm trying to do this but it doesn't seem to work. Is there a certain place it needs to be set at? For example, in one entry I'm doing the following

```
{% set title =  'title' %}
  {% set seomaticMeta = seomaticMeta | merge({'seoTitle': "Prefix: " ~ title }) %}
```

The end result ends up being " Prefix: title | Site Name". I'm looking to remove the "| Site Name" from one of the pages. Maybe you can point me in the right direction please?
