### ISSUE TITLE
Keywords using Meta field type have lost their chickletness

### ISSUE THREAD

**Issue by sg-modlab** [khalwat/seomatic#105]
I upgraded two releases up to the 1.1.22 release. After doing so when I edit keywords in the meta field type and click return they are not "transforming" to a chicklet/tag like design. Has this evolved to be just a comma separated list? or is something up?

Using latest Safari on El Capitan.

**Comment by khalwat** [comment]
Pushed a fix to `develop`:

https://github.com/nystudio107/seomatic/tree/develop
