### ISSUE TITLE
Titles not pulling through.

### ISSUE THREAD

**Issue by KyleBean** [khalwat/seomatic#106]
Im having an issue getting titles to change. Code bellow:

`{% set seomaticMeta = { 
    twitter: { 
        title: "Some Title",
        description: "Some Description"
    },
    og: { 
        title: "Some Title",
        description: "Some Description"
    }
} %}`

The code snippet was extracted from the head, the descriptions are affected but for some reason the titles remain unchanged.

**Comment by khalwat** [comment]
If you do it this way, because of the way Twig works, you'll be deleting everything else in the array unfortunately.  Have a look here for examples:

https://github.com/nystudio107/seomatic/wiki/08.-Dynamic-Twig-SEO-Meta

...of how to either set everything at once, or use the Twig `merge` filter

**Comment by KyleBean** [comment]
In this case its a little irrelevant whether or not ill be removing everything else from the array and just setting the title and description because the title is not being set, only the description is. For some reason im having trouble setting the title. - I have tried both 'merge' aswell as just 'set' and they both fail with the title change.

**Comment by khalwat** [comment]
When you say the title doesn't change, the title of what, exactly?  Are you looking at the rendered meta, and you're saying that the `twitter:title` tag isn't changed?

**Comment by KyleBean** [comment]
That is correct, the rendered meta of `og:title` and `twitter:title` remain unchanged.

So for instance, if the page has a set title and description for both og and twitter:

```
<!-- Facebook OpenGraph -->
<meta property="og:title" content="Old Test OG Title" />
<meta property="og:description" content="Old Test OG Description" />


<!-- Twitter Card -->
<meta property="twitter:title" content="Old Test Twitter Title" />
<meta property="twitter:description" content="Old Test Twitter Description" />
```

and i apply the 'set' or 'merge':

```
{% set seomaticMeta = {
    og: {
        title: "New Test OG Title",
        description: "New Test OG Description"
    },

    twitter: {
        title: "New Test Twitter Title",
        description: "New Test Twitter Description"
    }
} %}

```

it will output: 

```
<!-- Facebook OpenGraph -->
<meta property="og:title" content="Old Test OG Title" />
<meta property="og:description" content="New Test OG Description" />

<!-- Twitter Card -->
<meta property="twitter:title" content="Old Test Twitter Title" />
<meta property="twitter:description" content="New Test Twitter Description" />
```

So it will set the new descriptions but keep the old titles.

If there are no titles or descriptions set and i apply the 'set' or 'merge':

```
{% set seomaticMeta = {
    og: {
        title: "New Test OG Title",
        description: "New Test OG Description"
    },

    twitter: {
        title: "New Test Twitter Title",
        description: "New Test Twitter Description"
    }
} %}
```

it will output: 

```
<!-- Facebook OpenGraph -->
<meta property="og:description" content="New Test OG Description" />

<!-- Twitter Card -->
<meta property="twitter:description" content="New Test Twitter Description" />
```

It will have descriptions but no titles, it seems that the `title` is unaffected.

**Comment by khalwat** [comment]
Where exactly are you putting this code?  It should be in a template that extends your `layout.twig` and it can't be inside of a `{% block %}`

**Comment by KyleBean** [comment]
This is a snippet from the code im using.

```
{% extends "_layout" %}

{% set seomaticMeta = {
    seoTitle: entry.seoMeta.seoTitle,
    seoDescription: entry.seoMeta.seoDescription,
    seoKeywords: entry.seoMeta.seoKeywords,
    seoImage: entry.seoMeta.seoImage,
    canonicalUrl: entry.url,

    og: {
        title: entry.ogTitle,
        description: entry.ogDescription
    },

    twitter: {
        title: entry.twitterTitle,
        description: entry.twitterDescription
    }
} %}

{% block content %}
```

....Rest of content ....

the `layout` is being extended and its before the `block content`.

**Comment by khalwat** [comment]
Can you try what is in the docs, something like this:

```
{% set seomaticMeta = { 
    seoTitle: "Some Title",
    seoDescription: entry.summary,
    seoKeywords: "Some,Key,Words",
    seoImage: seomaticMeta.seoImage,
    canonicalUrl: entry.url,
    twitter: { 
        card: seomaticMeta.twitter.card,
        site: seomaticMeta.twitter.site,
        creator: seomaticMeta.twitter.creator,
        title: "Some Title",
        description: entry.summary,
        image: seomaticMeta.twitter.image
    },
    og: { 
        type: seomaticMeta.og.type,
        locale: seomaticMeta.og.locale,
        url: entry.url,
        title: "Some Title",
        description: entry.summary,
        image: seomaticMeta.og.image,
        site_name: seomaticMeta.og.site_name,
        see_also: seomaticMeta.og.see_also
    }
} %}
```

...where you set the full array? That or use `merge` -- the reason is that the functionality definitely works, but I think by nuking some of the array that SEOmatic expects to be there, it's causing the issues you're having.

**Comment by khalwat** [comment]
?

**Comment by khalwat** [comment]
Alright well, get back to me if you still need assistance.
