### ISSUE TITLE
Dev mode - Undefined index: siteSeoImageTransform

### ISSUE THREAD

**Issue by alanski66** [khalwat/seomatic#109]
Have just upgraded to the latest seomatic and get
Undefined index: siteSeoImageTransform
This is making the site unusable in dev mode

1216         $siteMeta['siteSeoImageTransform'] = $settings['siteSeoImageTransform'];

Whats the best way to fix this?

**Comment by khalwat** [comment]
My guess is maybe you didn't resave the Sections after upgrading to 1.1.21?  Can you try doing that?

**Comment by khalwat** [comment]
Or perhaps the database migration didn't run?  Because that would create that field...

**Comment by alanski66** [comment]
Where in the DB will I find that - I can check its existence....and is
there a force  dB upgrade URL?

**Comment by khalwat** [comment]
If you log into your AdminCP, it should run the migration automatically.

**Comment by alanski66** [comment]
It had run on first go prior to issues. I resaved sections and then got stuck tasks so uninstalled and reinstalled after clearing stuck tasks and all good now. Bit weird but hey this is a top notch product and I am happy to use and iron out wrinkles on route.

**Comment by khalwat** [comment]
Great, glad to hear you got it working!
