### ISSUE TITLE
Exclude seperator from title when Site SEO Title is empty [bug]

### ISSUE THREAD

**Issue by mm-tom** [khalwat/seomatic#11]
If Site SEO Title is blank and a separator is defined and the Site Title is provided, the output may result in:

```
| My Website
```

It may only be an issue for the homepage, but it would be nice if this resulted in:

```
My Website
```

Minor thing!

Thx

**Comment by khalwat** [comment]
Ah okay, that's easy enough to fix.  I pushed a fix for you:

https://github.com/khalwat/seomatic

That said, I do want to caution you; the `<title>` tag is pretty important to SEO, I wouldn't be leaving it blank (other than the SEO Site Name) unless you have a very good reason to do so.

**Comment by mm-tom** [comment]
Ace, thanks :)
