### ISSUE TITLE
Version 1.1.25: Undefined index: seoTitle on Homepage Single

### ISSUE THREAD

**Issue by AbbeyDesign** [khalwat/seomatic#110]
On my homepage single, in the control panel, I get this error.

Undefined index: seoTitle

/Applications/MAMP/htdocs/xxxxxxxxxxxxxxxx.dev/app/craft/plugins/seomatic/services/SeomaticService.php(1046)

Turn devMode off and it goes away. No error in a structure section, just the homepage single.

**Comment by steve-holland** [comment]
I'm also having this problem, just with a single channel entry. All the other entries of this type seem to be behaving, it's just the first one.

**Comment by khalwat** [comment]
Weird.  My guess is maybe you didn't resave the section after upgrading to 1.1.21?  In any event, I checked in a fix to `develop` to avoid the issue:

https://github.com/nystudio107/seomatic/tree/develop
