### ISSUE TITLE
Google Analytics script added even though GA ID field is empty?

### ISSUE THREAD

**Issue by roberttolton** [khalwat/seomatic#111]
Hi,

It looks like this was addressed in a previous release, however I am running the latest version 1.1.25 and the tag is still being added to my header:

```
<script async="" src="//www.google-analytics.com/analytics.js"></script>
```

Even though everything related to GA is either off or blank in the settings.

Tested locally, in dev mode.

**Comment by khalwat** [comment]
That's not a tag that SEOmatic is adding, I don't believe.  Search through your templates to see if you're adding it somewhere?

**Comment by roberttolton** [comment]
Here's the entirety of my `<head>` in my layout:

```
<head>

        <!-- META -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% hook 'seomaticRender' %}

        <!-- FAVICON -->

        <!-- FONTS -->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,300italic,700,700italic|Sarala:700" rel="stylesheet" type="text/css">

        <!-- STYLES -->
        <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="{{ siteUrl }}assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="{{ siteUrl }}assets/css/rocket.min.css" rel="stylesheet">
        <link href="{{ siteUrl }}assets/css/swiper.min.css" rel="stylesheet">
        <link href="{{ siteUrl }}assets/css/video-js.min.css" rel="stylesheet">
        <link href="{{ siteUrl }}assets/css/theme-{{ siteDetails.siteTheme }}.css" rel="stylesheet">

        <!-- MODERNIZR -->
        <script src="{{ siteUrl }}assets/js/vendor/modernizr-2.8.3.min.js"></script>

</head>
```

It's coming in after the Humans.txt block:

![screen shot 2016-07-20 at 20 08 45](https://cloud.githubusercontent.com/assets/3510875/16999435/da18d6b8-4eb5-11e6-8b6e-58d747d21f29.png)

Though I just, to make sure, viewed the source of the page (not dev tools) and it's not there. Though I'm only using Google's suggested GA code down in my footer, and nothing else is touching GA - and it's a weird spot to inject a script tag, right in the middle of seoMatic's rendered meta?

**Comment by roberttolton** [comment]
Never mind, sorry, please nuke this issue. Of course it's GA's _actual_ behaviour, it just really threw me for a loop that it went in amongst all that other meta. Comparing my layout to my flat HTML design, it usually gets injected right at the end of `<head>` like it normally would do, just this time it's several lines higher and buried in an odd place.

**Comment by khalwat** [comment]
Yeah that's just how it works, it inserts it before the first `<script>` tag it finds in your `<head>`
