### ISSUE TITLE
Categories with seomatic field CException on opening

### ISSUE THREAD

**Issue by rubenwebs** [khalwat/seomatic#112]
I updated to your latest version.

But now I get a CException error when opening categories that have the seomatic field.

The error is:
The attribute "Craft\CategoryModel.postDate" is not defined.

If I disable SeoMatic I can open the category, but when I enable it I get the error.

**Comment by khalwat** [comment]
This is fixed in a build I checked into `develop`: 

https://github.com/nystudio107/seomatic/tree/develop
