### ISSUE TITLE
Character Count Gone

### ISSUE THREAD

**Issue by AbbeyDesign** [khalwat/seomatic#113]
Character Count is gone on Title and Description unless I resave a couple of times. Started after 1.1.26, 1.1.27 is the same

<img width="719" alt="melrose_mansion_hotel_-_carimi_construction__llc" src="https://cloud.githubusercontent.com/assets/11862097/17118845/fe5e5046-52c2-11e6-8118-9851734b1aef.png">

**Comment by AbbeyDesign** [comment]
Oops, might be just Chrome or my cache... I'll update you in a minute.

**Comment by AbbeyDesign** [comment]
It's Chrome and Safari... Firefox works as expected.

**Comment by khalwat** [comment]
hmmmm.  That's functionality provided by Craft.  If you view the Javascript console, do you see any Javascript errors?

**Comment by khalwat** [comment]
BTW, in the screenshot you posted, the first field shouldn't have any number counter in it, it's pulling from another field.  So that's just a preview of the text it's pulling in.

**Comment by khalwat** [comment]
I doubled-checked it today, and it's working for me:

![screen shot 2016-07-26 at 9 11 19 am](https://cloud.githubusercontent.com/assets/7570798/17139174/533e7854-5311-11e6-9cac-48c43827fc50.png)

Please check your Javascript error console in the browsers where it isn't working.
