### ISSUE TITLE
Error when adding image to Template Meta

### ISSUE THREAD

**Issue by andrewcgregory** [khalwat/seomatic#114]
After upgrade (I believe it started when upgrading from 1.125 to 1.126) I am receiving an error anytime I have an SEO Image selected in the Template Meta.

![error](https://cloud.githubusercontent.com/assets/1779776/17137221/04624c64-5308-11e6-9d2c-9541990566b8.png)

**Comment by khalwat** [comment]
Yeah, I don't understand this -- can you upgrade to 1.1.27 and let me know if it's still occurring?

**Comment by andrewcgregory** [comment]
Yes, I did the upgrade and it did not fix the issue.

**Comment by khalwat** [comment]
The thing I'm not understanding is that assuming the migrations ran, this migration creates that field:

https://github.com/nystudio107/seomatic/blob/master/migrations/m160715_000000_seomatic_addSeoImageTransforms.php

...in the `seomatic_meta` table.  And the field is defined in both the model, and the record:

https://github.com/nystudio107/seomatic/blob/master/models/Seomatic_MetaModel.php

https://github.com/nystudio107/seomatic/blob/master/records/Seomatic_MetaRecord.php

I can put something in there to protect against this, but I can't understand how it could be happening in the first place, if the migration ran.

**Comment by khalwat** [comment]
Okay I checked in a safeguard for this, if you want to re-download it and try it out.  But something is not right, it's acting as if the above migration didn't run.

**Comment by khalwat** [comment]
Go ahead and re-download SEOmatic, and see if it fixes it for you.

**Comment by andrewcgregory** [comment]
I re-downloaded it and it works fine now. Thanks.
