### ISSUE TITLE
Entry Keywords Meta does not pull in from Tags Field

### ISSUE THREAD

**Issue by admench** [khalwat/seomatic#116]
Hey,

Thanks for a great plugin Andrew.

1 issue when using Entry Meta Fieldtype:

When editing the seoMatic Fieldtype `blogMeta` in Settings->Fields, I set up the keywords meta Source _From Field_. I point to the `blogTags` Tags field. I then confirm that the entry does indeed have tags selected in the `blogTags` field.

When I then check the seoMeta Field in the entry, there are no auto filled keywords sourced from the tags field.

Another angle: I allow the keywords field source to be altered. I then select the tags field and they do populate using this method.

**Comment by khalwat** [comment]
This seems to be working for me?  Here's my Tags field:

<img width="643" alt="safariscreensnapz247" src="https://cloud.githubusercontent.com/assets/7570798/17175561/380110cc-53d6-11e6-99fc-d0bd40bb3404.png">

Here's my SEOmatic Meta field set to pull from that tag field:

<img width="643" alt="safariscreensnapz249" src="https://cloud.githubusercontent.com/assets/7570798/17175587/5c2b8b3a-53d6-11e6-8416-efa6fee9dd77.png">

...and here's the rendered Meta with those Keywords in it:

<img width="643" alt="safariscreensnapz250" src="https://cloud.githubusercontent.com/assets/7570798/17175599/68a8d5de-53d6-11e6-877e-6eaa8ffff4cd.png">

**Comment by khalwat** [comment]
Oh I see, you're saying that if you set it up to default to that field, it doesn't work.

My guess is that you added the SEOmatic FieldType post-facto.  That being the case, as per the documentation, you need to re-save your Section in order for the FieldType to be populated with data.  It's just how Craft works, newly added fields have no data in them.

**Comment by admench** [comment]
Thanks, Saving the Section fixed it!

I had tried that approach once and it didn't work, however returning to it just now and re-saving the section worked this time.
