### ISSUE TITLE
Missing somethign

### ISSUE THREAD

**Issue by stephhider** [khalwat/seomatic#118]
Hi I have installed the plugin but maybe I am missing a step or something I should be doing because I am not seeing any individual page entries at all. I am not able to find any under the fields area to move around in the sections entry type as well. Please advise.

Thanks!

**Comment by khalwat** [comment]
Did you create an SEOmatic Field, and add it to your entries where you want it to appear?

**Comment by stephhider** [comment]
Oh sorry I knew I was missing something I thought it automatically added in the entry field but you have to make one using the field type. Thanks!

**Comment by khalwat** [comment]
No problem!
