### ISSUE TITLE
Add option to add different images for Facebook and Twitter

### ISSUE THREAD

**Issue by joshangell** [khalwat/seomatic#120]
When filling in the Site Meta information you can add an image that gets used in Facebook Open Graph and Twitter Cards, however both platforms have different suggested image dimensions and ratios. It would be nice to be able to provide a different image for each service so we can have more appropriate ratios and dimensions.

I appreciate we can use the service specific transforms but that doesn’t cover needing a square one for Twitter and letterbox for Facebook.

Simply awesome plugin though!!

**Comment by khalwat** [comment]
So using the image transforms, you can't create a square one for Twitter that crops, and a rectangular transform for Facebook that fits?

The problem with having separate images for each service is that it sacrifices convenience.  For the majority, who just want to set one image, now they have to set 3.  I'd assumed that adding the transforms would solve the issue of different aspect ratios, etc. for different services?

**Comment by joshangell** [comment]
Well, I agree with you there - but what if I have a square version of my logo and a landscape one? Cropping the landscape one square chops the ends off and cropping the square one landscape chops the tops off.

So either way I would need an abstract enough image to serve both aspect ratios.

**Comment by joshangell** [comment]
And if I use the landscape version across both, it goes too small in a fitted square transform, i.e. there is too much whitespace above and below.

But I do appreciate the complexity it would add!

**Comment by joshangell** [comment]
And finally, I wonder if it can't be sorted that you set one master one, then have the option to override for the service specific ones?

**Comment by khalwat** [comment]
So you can already do all of this now, but you'd just need to do it via Twig:

```
  {% set twitter = seomaticMeta.twitter %}
  {% set twitter = twitter | merge({'image': someiImage}) %}
  {% set seomaticMeta = seomaticMeta | merge({'twitter': twitter}) %}
  {% set og = seomaticMeta.og %}
  {% set og = og | merge({'image': someiImage}) %}
  {% set seomaticMeta = seomaticMeta | merge({'og': og}) %}
```

**Comment by joshangell** [comment]
Right! I'm a dunce! This can be closed! Who needs more clutter eh? It must be the weekend already ...

**Comment by daniellelecomte** [comment]
+1 for something like this as I get requests for it often. Thx!

**Comment by AbbeyDesign** [comment]
Roughly on the same subject but it would be more important to have a separate social title for things like Facebook and Twitter. They allow for more text, but more importantly, they are two different intents.

Whereas I might create a keyword stuffed <title> with company name etc. separated by pipes, my social title should be something more familiar/colloquial. eg:

**SEO title**
Great Widgets | Shop for Widgets | The Widget Store

**Social title**
We've got great Widgets at the Widget Store, Check them Out!

Obviously this would fallback on the seotitle if I did not want to go the extra step in adding a social title. I would assume there are going to be SEO managers wanting something different for each social media service, but I think that just starts going down a rabbit hole. A simple socialtitle that falls back on the seotitle might satisfy 90% of the people who would want this sort of thing.

**Comment by AbbeyDesign** [comment]
Roughly on the same subject but it would be more important to have a separate social title for things like Facebook and Twitter. They allow for more text, but more importantly, they are two different intents.

Whereas I might create a keyword stuffed title with company name etc. separated by pipes, my social title should be something more familiar or colloquial. eg:

**SEO title**
Great Widgets | Shop for Widgets | The Widget Store

**Social title**
We've got great Widgets at the Widget Store, Check them Out!

Obviously this would fallback on the seotitle if I did not want to go the extra step in adding a social title. I would assume there are going to be SEO managers wanting something different for each social media service, but I think that just starts going down a rabbit hole. A simple socialtitle that falls back on the seotitle might satisfy 90% of the people who would want this sort of thing.

**Comment by khalwat** [comment]
@AbbeyDesign Do you want to create a separate feature request for this?

**Comment by AbbeyDesign** [comment]
@khalwat sure

**Comment by khalwat** [comment]
`[Added] Added the ability to set separate images for Twitter Cards and Facebook OpenGraph images` -- checked into `develop`:

https://github.com/nystudio107/seomatic/tree/develop

**Comment by khalwat** [comment]
<img width="759" alt="google chromescreensnapz045" src="https://cloud.githubusercontent.com/assets/7570798/18237276/693152ba-72fd-11e6-89a9-74eb3e5fdb1d.png">
