### ISSUE TITLE
Custom image

### ISSUE THREAD

**Issue by proximo7** [khalwat/seomatic#121]
I have a matrix field that contains the images for the entry. How can I pull the first image as the custom SEO Image? I've tried this but it just shows the default data.

```
{% for block in entry.contents.type('image').limit(1) %}
    {% set assetID = block.image.seoMeta.seoImageId %}
{% endfor %}
```

**Comment by khalwat** [comment]
It's not entirely clear to me what you're trying to do from the code you pasted in but basically, once you have the URL to the image you want:

```
{% set seomaticMeta = seomaticMeta | merge({'seoImage': someAsset.url }) %}
```

There are a bunch of examples in the docs:

https://github.com/nystudio107/seomatic/wiki/10.-Dynamic-Twig-SEO-Meta

**Comment by proximo7** [comment]
Thank you for that example. I tried this and several of the examples in the documentation. For some reason I'm still not getting this to work - I must be missing something. 

This is at the beginning of the entry template:
`{% for block in entry.contents.type('image').limit(1) %}
{% for image in block.image.limit(1) %} 
     {% set seomaticMeta = seomaticMeta | merge({'seoImage': image.url }) %}
{% endfor %}
{% endfor %}`

Just for fun I tried inserting a manual path to an image but it still showed the default image:
`{% set seomaticMeta = seomaticMeta | merge({'og': http://dev.domain.com/images/assets/_half/image.jpg }) %}`

I've got everything else working great and I'm very impressed with the quality of the plugin and the comprehensive SEO data that can be generated.

**Comment by khalwat** [comment]
Where is this code, exactly?  You need to do it _before_ the `{% hook 'seomaticRender' %}` is called; it's not always obvious how to do this:

https://straightupcraft.com/articles/twig-processing-order

Put your code at the top of your template that extends your `layout.html` but _not_ in a `{% block %}` (because those are executed later in the Twig parsing).
