### ISSUE TITLE
breadcrumb json-ld is rendered twice

### ISSUE THREAD

**Issue by dommmel** [khalwat/seomatic#122]
Hi there!

Once inside of the  section and once inside  section.

The first one also does not pick up any customization/changes via the seomaticMeta variable.

Thanks once again for the awesome plugin

EDIT: My current workaround is to do 
`{% set seomaticMainEntityOfPage = seomaticMainEntityOfPage|merge({breadcrumb: null}) %}
`
 in my templates

**Comment by khalwat** [comment]
It's rendering twice intentionally... if the `mainEntityOfPage` is a WebPage, it should have the breadcrumbs as a child.

The fact changes aren't being picked up sounds like a bug, though

**Comment by khalwat** [comment]
So what you should do is after you've modified the breadcrumbs however you want, do:

```
{% set myBreadcrumbs = {
    "Home": "http://nystudio107.dev/",
    "Books": "http://nystudio107.dev/books/",
    "Candide": "http://nystudio107.dev/books/candide",
} %}

{% set seomaticMeta = seomaticMeta | merge({'breadcrumbs': myBreadcrumbs }) %}

{% if seomaticMainEntityOfPage is defined and seomaticMainEntityOfPage.type == "WebPage" %}
    {% set seomaticMainEntityOfPage = seomaticMainEntityOfPage | merge({'breadcrumbs': myBreadcrumbs }) %}
{% endif %}
```
