### ISSUE TITLE
Don't run Content Analysis automatically

### ISSUE THREAD

**Issue by sjelfull** [khalwat/seomatic#124]
To set the scene: I'm running a site on Heroku, and i'm trying to update the SEOmatic settings.

When I access the SEOmatic cp section, it runs the Content Analysis automatically, and somehow crashes the webserver / process.

Would be great if it wasn't automatic / wasn't the default tab.

**Comment by khalwat** [comment]
Hmmm.  Well, I made it the default tab on purpose, because I thought it was something that people would be coming back to.

I'm having a hard time understanding how it could crash a web server though?

**Comment by khalwat** [comment]
Are you able to replicate this?

**Comment by sjelfull** [comment]
Yeah, I agree that it makes sense.

Digging into the logs, and it looks like the request is timing out.

Since it's doing requests to Pagespeed etc. as well, would it be a good idea to split them up, so they update the results as they come in? More complex, but quicker feedback?

**Comment by AbbeyDesign** [comment]
I'm not crashing, but the feature is a little annoying. It's the first tab so any time I go into the plugin, regardless of what I want to do, it runs the test which for the site I am on is 10-15 seconds of spinning icon. I love the feature, I like it there, but I'd rather it wait until/if I click "Analyze".

**Comment by khalwat** [comment]
You should be able to click off to any section while it's waiting to load, no?  Or is it blocking?

I can easily make it not analyze until you click the button.  It's actually removing 1 line of code :)

**Comment by sjelfull** [comment]
In my case, it froze the PHP process (?), so it was actually blocking.

Maybe you can make it a setting? I agree that it's useful.

**Comment by AbbeyDesign** [comment]
In my case, if I click off to another section, or try to exit the plugin, it has to wait until the scan is done.

**Comment by VadimBrodsky** [comment]
+1, on my shared host it crashes the site when I open seomatic tab in the sidebar.

**Comment by khalwat** [comment]
That's crazy.  All I'm doing is some `curl`s to fetch data.  Anyway yeah I'll make it so that you have to click the button to load it.

But I do want to fix whatever is "crashing" a web host.  That definitely should not be happening.

**Comment by khalwat** [comment]
Okay guys, just checked into `develop`:
- [Improved] The SEOmetrics tab in the AdminCP now doesn't start analyzing until you click Analyze
- [Improved] Improved SEOmetric's sitemap.xml detection

https://github.com/nystudio107/seomatic/tree/develop
