### ISSUE TITLE
HTML5 Meta UTF-8

### ISSUE THREAD

**Issue by josefarrugia** [khalwat/seomatic#126]
Found an error on W3C. 

`<meta http-equiv="content-type" content="text/html; charset=UTF-8">` should be changed to `<meta charset="UTF-8">`.

**Comment by khalwat** [comment]
This actually isn't an error; it's because you have another `<meta charset>` tag.  Remove that extra tag, and you'll be golden.

**Comment by josefarrugia** [comment]
@khalwat You're a wizard, why didn't I spot that? I was going through the W3schools and this caught my attention - http://www.w3schools.com/tags/att_meta_http_equiv.asp
