### ISSUE TITLE
Config items should use `null` to mean "no value" rather than empty strings

### ISSUE THREAD

**Issue by michaelrog** [khalwat/seomatic#128]
This is relevant to the `globalMetaOverride` item in the plugin config, and anywhere else SEOmatic sets a config that may later be overwritten by a customer or environment.

The instructions in the comments for that item read: "Leave any value in the array blank to cause it to not override."

A true `null` should be used to represent "no value" (i.e. "do not override") rather than a blank string. (Any string — even an empty one — _is a value_. Use case: What if I _want_ to override a particular value with an empty string?)

**Comment by khalwat** [comment]
Do you want to override a particular value with an empty string?

The underlying reason is we're using `array_merge` in a number of places to build the cascading settings, and this is its behavior with `""` strings.
