### ISSUE TITLE
SEO images not updating in entry meta 

### ISSUE THREAD

**Issue by danieltott** [khalwat/seomatic#129]
I have entries that all have SEO entry fields for them, but the SEO image is not updating when changed. This is across all of my different entries (some of which have different SEO fields). They seem to have frozen at some point - some are using the default site seo image, some are using an older version of the correct image. I am sure I've missed something, but I've been working on this for a few hours over a couple days and can't seem to figure anything out. i've cleared the cache, deleted the entire storage directory, etc.

Hopefully this is something simple that I messed up. Please let me know what info I can provide.

**Comment by khalwat** [comment]
So can you provide me with some more information?  Craft version?  SEOmatic version?

Screenshot of how your SEOmatic field is configured?  Is it pulling from other image fields?

**Comment by danieltott** [comment]
Absolutely:
Craft 2.6.2911
SEOMatic  1.1.31

Here's the field settings:
![screencapture-thefrontporchpeople-admin-settings-fields-edit-64-1472060884619](https://cloud.githubusercontent.com/assets/360261/17941502/9f2f6956-6a01-11e6-8e5a-6b4508251b99.png)

**Comment by khalwat** [comment]
Okay so it's pulling from the Hero image.  And you're saying that when you change the Hero Image field in a particular entry, click on Save, and then look at the entry again, what is shown in the SEOmatic FieldType image field is not correct?

**Comment by danieltott** [comment]
No - the entry looks correct in the admin, but the seo output (including the preview) is using the default site settings for the seo image

Entry settings:
![image](https://cloud.githubusercontent.com/assets/360261/17942569/f6af96de-6a05-11e6-951a-867e45ee5c71.png)

SEO preview:
![image](https://cloud.githubusercontent.com/assets/360261/17942615/234032a8-6a06-11e6-9aff-78c97bf48c43.png)

**Comment by khalwat** [comment]
Any chance you can come to the Craft Slack and Direct Message me so we can sort this out?

If you don't have an invite, you can get one here: 

https://craftcms.com/community

My handle on there is `khalwat`

**Comment by khalwat** [comment]
You are clicking on Save after you change the image, but before you preview it, yes?

**Comment by danieltott** [comment]
Yes to both

**Comment by khalwat** [comment]
So this ended up being that multiple SEOmatic FieldTypes were added to this Section's EntryType, but were later removed.  Craft keeps data from fields that are removed from field layouts in entries, in case you add them back in later.

This caused the multiple SEOmatic FieldTypes to stomp on each other, resulting in the missing images in question.

I checked a fix into `develop`:

https://github.com/nystudio107/seomatic/tree/develop

Please let me know how it works for you.

**Comment by danieltott** [comment]
Yes, this fix worked perfectly.
