### ISSUE TITLE
Weird Error on Mediatemple hosting

### ISSUE THREAD

**Issue by karloestrada** [khalwat/seomatic#130]
First, this error happens on clicking "Get Started":
Use of undefined constant ENT_HTML401 - assumed 'ENT_HTML401'

Second, this error happens on clicking "Analyze":
curl_setopt() [<a href='function.curl-setopt'>function.curl-setopt</a>]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set

So I try to resolve it by adding open_basedir="" on the php.ini but still error occurs like Parse error syntax. 

Anyone, had the same issue or in the same hosting?

Thanks!

**Comment by khalwat** [comment]
What version of PHP are you using? It sounds like you're using PHP 5.3, you'll need to upgrade to 5.4 or later.
