### ISSUE TITLE
Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

### ISSUE THREAD

**Issue by phaetons** [khalwat/seomatic#131]
Hi, when i click the 'Analyze'-Button i get following error:

`PHP warning
curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set`

Server is Virtual Hosting, therefor the open_basedir ist set to the directory of the virtual host.

Best regards
Stephan

**Comment by khalwat** [comment]
Are you running PHP 5.3?  Is safe mode on?  Here are some solutions you can try:

http://stackoverflow.com/questions/6352927/curlopt-followlocation-cannot-be-activated

**Comment by phaetons** [comment]
I'm using PHP 5.5. where safemode is removed. This issue is still not solved.

**Comment by khalwat** [comment]
I checked a build into `develop` that I believe will solve the issue for you:

https://github.com/nystudio107/seomatic/tree/develop

Let me know?

**Comment by phaetons** [comment]
Hey, thank you. I will test it tomorrow morning and report to you

**Comment by khalwat** [comment]
Any word?

**Comment by phaetons** [comment]
Hi, now it does start the Analyze process, but at some point i get a new error "Trying to get property of non-object". Maybe it tries to analyze a non-html page? I added a screenshot.

I would like to check it further, but are very busy the next two weeks. Maybe you can implement a little debug-logging at that point, so i would check why there is no object. Or i will do it in two weeks, when i have a little more time.

![screencapture_seometrics](https://cloud.githubusercontent.com/assets/7963541/18380287/ed96cab8-7676-11e6-8e8d-2f97ca89e831.png)

**Comment by khalwat** [comment]
Okay, let's follow up when you have the bandwidth to do some testing.  Because it looks like this is pretty specific to your environment.

Is it possible that your webpage has no `<title>` tag in it?
