### ISSUE TITLE
SEO Description and Keywords are not transferred from "Source: From Field"

### ISSUE THREAD

**Issue by ClemensSchneider** [khalwat/seomatic#132]
I tried setting up SEOmatic `1.1.33` on Craft `2.6.2797` and it seems to work fine with one exception.

I created a field of type `SEOmatic Meta` and configured it to let the content of SEO Title, Description, Keywords and Image be populated from field-contents. This works fine for Title and Image but not so for Description and Keywords. These are configured to be populated from field `body` but in case `body` exceeds the limit of 160 (Description) or 200 (Keywords), nothing is getting written to the SEO fields.

I would expect the auto-extraction to internally use the `extractSummary` and `extractKeywords` functionality to populate the SEO-fields? Is there any way to setup the plugin in this way?

**Comment by khalwat** [comment]
Yep, I set up the plugin to do that all the time.  SEOmatic will automatically truncate the field data as appropriate.

If you want keywords, you'll need to select "Keywords from Field"; here's an example site where I do what you're trying to do:

![google chromescreensnapz096](https://cloud.githubusercontent.com/assets/7570798/18208044/d0bfa200-70fb-11e6-8b4b-0733d42197bc.png)

**Comment by ClemensSchneider** [comment]
Well this is exactly what I was expecting but what is not wotking in my case.. Nothing gets transferred to the SEO fields in case the field-content exceeds their maximum length.. Could this be somehow related to #108? Although I doubt it, as #108 occurs client-side..

**Comment by khalwat** [comment]
The amount of data in the source fields doesn't matter; SEOmatic will truncate it automatically.

**Comment by khalwat** [comment]
Did you try re-saving your section after adding the SEOmatic field, as per:

https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

> If you add an SEOmatic FieldType to an existing Section that already has entries in it, you'll need to re-save the Section to populate the newly added SEOmatic FieldType with data. You can do this via Settings → Edit My Section → hit Save.

**Comment by ClemensSchneider** [comment]
Yes, I did..
- created a completely new entry to see if it's only related to existing entries
- deleted the SEO Meta field and re-added it
- re-saved the section

All works fine if the length of the source-field is smaller than the max-length of the seo field. The contents are copied over as expected then.

I will have a closer look at it on monday, could it be related to an older PHP version?

**Comment by khalwat** [comment]
hrm, well, if it is, then it's definitely a bug.  Because that should not be happening.  We can take a closer look at it next week.

**Comment by ClemensSchneider** [comment]
Just for the record: my local development environment consists of `Apache/2.4.4 (Win32) OpenSSL/1.0.1e PHP/5.5.3`

**Comment by khalwat** [comment]
So this is what happens when an entry is saved:

https://github.com/nystudio107/seomatic/blob/master/fieldtypes/Seomatic_MetaFieldType.php#L388

It checks the source field, and then truncates the text based on it.

I set up some local tests, and was unable to replicate your bug.  We'll have to sync up so I can see it happening on your setup.

**Comment by ClemensSchneider** [comment]
I tried to simply replace the switch-statement for the `seoDescriptionSource` with `$value->seoDescription = "Hard-Coded";` and I expected the value 'Hard-Coded' to be written to the SEO Description field upon the next save. But instead I got the value 'Not-Hard-Coded' which is the content of the source field...

Does this make any sense?

**Comment by ClemensSchneider** [comment]
I guess I found a way to replicate the bug. It seems like the contained link in the fields content causes truncateStringOnWord to fail.

Does work:

```
<p>This field-content is more than 160 chars long and contains a Link. This seems to break the truncateStringOnWord-function provided by SEOmatic</p>
```

Does not work:

```
<p>This field-content is more than 160 chars long and contains a <a href="http://www.example.com/" class="urlextern" target="_blank" title="http://www.example.com/">Link</a>. This seems to break the truncateStringOnWord-function provided by SEOmatic</p>
```

**Comment by ClemensSchneider** [comment]
Seems like a field-content like this does break the functionality, too:

```
<p>This field-content is more than onehunderedandsixty&nbsp;chars long and contains an entity-encode. This seems to break the truncateStringOnWord-function provided by SEOmatic.</p>
```

While investigating the causes I found out, that #108 fails the same time the exctraction-functionality fails, too. When removing the `&nbsp;` in the example above, everything works as expected.

**Comment by ClemensSchneider** [comment]
I setup a local environment running PHP 5.6.19 and PHP 7 and the problem (#108 too) does not appear. So it seems to be related to the PHP version being used..

**Comment by khalwat** [comment]
That's strange, we do a `strip_tags()` before truncating things.  What version of PHP are you seeing this fail with?

**Comment by khalwat** [comment]
I checked a build into `develop` that you can try:

https://github.com/nystudio107/seomatic/tree/develop

`[Improved] Added html_entity_decode() to the _cleanupText() method`

I'm not sure if this will help your version of PHP or not.  What version is it?

**Comment by ClemensSchneider** [comment]
Thanks for your efforts. As already noted above, my local setup is `Apache/2.4.4 (Win32) OpenSSL/1.0.1e PHP/5.5.3`.

The bug wasn't resolved by your change in `develop`.

**Comment by khalwat** [comment]
I'm not sure what to say; I have it `html_entity_decode()`'ing the text now.

**Comment by ClemensSchneider** [comment]
I narrowed down the source of the bug to be this line in `_cleanupText`:

```
$text = preg_replace('/\s+/', ' ', $text);
```

Replacing it with

```
$text = preg_replace('/\s{2,}/', ' ', $text);
```

Fixes the issue although it should do exactly the same in terms of regexp....

Using `html_entity_decode` does not seem to be necessary here then.

This directly correlates with #108 (at least in my case).

**Comment by khalwat** [comment]
NICE!  I will roll it in.  So the interesting thing to me is that this actually likely has nothing to do with PHP version, but rather whether `iconv` is installed and of a proper version.

**Comment by khalwat** [comment]
I rolled it into 1.1.36 -> https://github.com/nystudio107/seomatic

Hopefully you can download it from there, and ensure it works for you.

**Comment by khalwat** [comment]
Thanks for your help!
