### ISSUE TITLE
[Feature Request] Facebook Pixel Field 

### ISSUE THREAD

**Issue by mcclaskiem** [khalwat/seomatic#133]
It would be awesome to have seomatic manage the facebook pixel installation. Granted this is usually something that is only on production, potentially managing it between a staging and production environment would allow for testing and more control.

**Comment by khalwat** [comment]
So mainly, I wonder what advantage there is to putting this into the settings in SEOmatic, as opposed to just including in your `layout.twg` template?

Granted, the same argument could be made re: Google Analytics, and Google Tag Manager, which are included in SEOmatic, tho.

**Comment by mcclaskiem** [comment]
I think its definitely a nice to have feature simply for the sake of managing as much as you can in one place. Also allowing non-developers the ability to change the facebook pixel on the fly based on what campaigns they are running, etc.

**Comment by dperrera** [comment]
This would be a swell addition. More clients seem to be requesting FB Pixel integration and it'd be great to have it be an easy integration with Seomatic.

**Comment by hahnzilla** [comment]
For what it's worth, I typically use Tag Manager to accomplish this. It seems much cleaner to keep all third party tags there (I also put analytics in GTM).

**Comment by khalwat** [comment]
Yeah so what I'm going to suggest for SEOmatic 1.x/Craft 2.x is that you use Google Tag Manager for this type of thing, which SEOmatic supports, and it's free.

In SEOmatic 3.x for Craft 3, I'll have support for this type of thing.

**Comment by hahnzilla** [comment]
I remember seeing this thread awhile ago and I figured I'd post about the fbpixel plugin I wrote:: https://github.com/Moment-Inc/craft-fbpixel
