### ISSUE TITLE
Error if site, or locale, doesn't have a homepage

### ISSUE THREAD

**Issue by aelvan** [khalwat/seomatic#135]
The code in getDefaultBreadcrumbs() in SeomaticService, assumes that there is a page that's marked as homepage. This might not be the case, for instance if you have a site that's mostly in one language, but have some pages, but not the homepage, in other locales. We then get an error on line 1093 of SeomaticService saying `Trying to get property of non-object`, because there is no element with uri `__home__`.

This can be fixed by adding a check for element on line 1091:

`if ($this->lastElement && $element)`

But, it's worth noting that the generated JSON-LD breadcrumb in the front-end code, will actually be wrong, because it adds the base url as the first item in the list, even though it doesn'r really exists. But, I get that's a more fundamental issue with automatic breadcrumbs..

**Comment by khalwat** [comment]
Yeah this is fixed in the branch checked into `develop`

https://github.com/nystudio107/seomatic/tree/develop
