### ISSUE TITLE
No option for using absolute paths?

### ISSUE THREAD

**Issue by willi828** [khalwat/seomatic#136]
My facebook og:url tag needs to be absolute.  Is the only way to accomplish this to create a template and re-write all the meta tags manually?  Is this an option somewhere and I'm missing it?

**Comment by khalwat** [comment]
SEOmatic should convert these to absolute URLs for you.

**Comment by julienhoste** [comment]
Same probleme here. og image url includes the local.. How do we get an absolute path without language local?
