### ISSUE TITLE
Can't access seo field in templates

### ISSUE THREAD

**Issue by nexflo** [khalwat/seomatic#137]
Hey,

inside the twig templates the seo fields are always returning empty..and not the text and description added to the plugin?

Thanks

Flo

**Comment by khalwat** [comment]
Did you re-save your section after adding the SEOmatic FieldType to it as per: https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

> If you add an SEOmatic FieldType to an existing Section that already has entries in it, you'll need to re-save the Section to populate the newly added SEOmatic FieldType with data. You can do this via Settings → Edit My Section → hit Save.

?

**Comment by nexflo** [comment]
lol...i posted in the wrong SEO repo plugin...sorry man.

**Comment by khalwat** [comment]
aha, but you found the right plugin.  SEOmatic will give you a ton more SEO goodness than the plugin you're looking at.
