### ISSUE TITLE
Template Error in Craft 2.4

### ISSUE THREAD

**Issue by jameswbutts** [khalwat/seomatic#139]
**Error:** 

```
Variable "continueEditingUrl" does not exist
/craft/plugins/seomatic/templates/settings.twig(40)
```

**Location:** /admin/seomatic/settings
**Craft:** 2.4.2679
**SEOmatic:** 1.1.36
**PHP:** 5.5.30

Thanks!

**Comment by khalwat** [comment]
I checked a fix for this into `develop`:

https://github.com/nystudio107/seomatic/tree/develop

[Fixed] The Settings template now works with Craft < 2.5

**Comment by jameswbutts** [comment]
Looks good, thank you!
