### ISSUE TITLE
SEO Image — Crop Options

### ISSUE THREAD

**Issue by davidhellmann** [khalwat/seomatic#14]
Hey, 

great Plugin! 

One thing… The SEO Images, is it possible to add a Crop Option there. It would be nice to use "From Field" and this Image will cropped in the right format. 

Just an Idea, maybe it's interesting to implement it.

best
david

**Comment by khalwat** [comment]
Yeah, some way to handle this is on my radar.  I just haven't figured out the best way to do it.

Some people like that SEOmatic is simple to set up, and there's one SEO Image field that gets propagated.  Other people want separate fields for Twitter & Facebook images (and support for multiple images when it comes to Facebook).

It's a balance between keeping things simple/usable, and giving people the control they need.  The good news is that you can do absolutely whatever you want from within Twig, you can do something like this:

```
{% set thumb = {
    mode: 'crop',
    width: 100,
    height: 100,
    quality: 75,
    position: 'top-center'
} %}

{% set seomaticMeta = seomaticMeta | merge({
    twitter: {
        card: seomaticMeta.twitter.card,
        site: seomaticMeta.twitter.site,
        creator: seomaticMeta.twitter.creator,
        title: seomaticMeta.twitter.title,
        description: seomaticMeta.twitter.summary,
        image: entry.asset.getUrl(thumb)
    }
}) %}
```

**Comment by davidhellmann** [comment]
Yes understand it and I'm with you it must be simple and not to many options. This post is the same topic as in the other post. I try it out.

Thank u!
