### ISSUE TITLE
Blank CP screens

### ISSUE THREAD

**Issue by dguillory** [khalwat/seomatic#140]
After upgrading to 1.1.36, I'm getting blank CP screens for all SEOmatic pages except SEOmetrics and Template Meta. Running Craft 2.6.2930 with PHP 5.4.14 and a memory_limit of 512M. Nothing notable is showing up in Apache, Craft or SEOmatic logs; still trying to get to the PHP error logs.

**Comment by khalwat** [comment]
Check in `craft/plugins/seomatic/templates` and see if all of the templates are there.  It sounds like something went wrong with the install; maybe something .gitignore related?

**Comment by dguillory** [comment]
Looks like everything is there…

**Comment by khalwat** [comment]
Try re-installing it, and if that fails, try enabling `devMode` and see if you are able to get any errors.

**Comment by dguillory** [comment]
OK, re-installed and no dice, but dev mode reveals this on /admin/seomatic/site:

`Fatal error: Can't use function return value in write context in […]/craft/plugins/seomatic/controllers/SeomaticController.php on line 123`

`Fatal error: Interface 'Craft\Iterator' not found in […]/craft/app/framework/collections/CListIterator.php on line 21`

**Comment by tjFogarty** [comment]
Hi @dguillory we had the exact same issue about an hour ago. We updated PHP to 5.6 and the issue was resolved, but not sure why just yet. Hopefully we can learn more.

**Comment by dguillory** [comment]
Thanks @tjFogarty. I think it's an issue affecting PHP <5.5, [according to this](http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context/4328049#4328049).

**Comment by khalwat** [comment]
Wow, that's very interesting.  So you get a blank screen just by going to one of those template pages?  Or after trying to save something on them?

**Comment by tjFogarty** [comment]
@dguillory thanks for that! So it's a parse error as it's calling `empty()` on a function's return value from `if (empty(ini_get('open_basedir')))` on line 123 of SeomaticController.php.

**Comment by dguillory** [comment]
Just by going. I don't have any `open_basedir` issues, so I went ahead and commented out lines 123-124 in `/seomatic/controllers/SeomaticController.php` and everything's working fine now.

I'm pretty sure this is the only site I have that's running PHP 5.4, so let me know if you need me to test anything on it.

**Comment by khalwat** [comment]
I pushed a fix to `develop` that should take care of it for you:

https://github.com/nystudio107/seomatic/tree/develop

Let me know?

**Comment by dguillory** [comment]
Yep, that fixes it, thanks! Learned something obscure today…

**Comment by dguillory** [comment]
Of course, I _guarantee_ I will forget this at some point in the future and pass a function return directly into `empty()`anyway.

**Comment by khalwat** [comment]
Great, thanks!  I'll push a release out shortly, so no one else runs into this.  Very odd.

**Comment by joepagan** [comment]
Also just got this on php5.4, dev tree version fixed.
