### ISSUE TITLE
Multiple Opening Hours for a day

### ISSUE THREAD

**Issue by joepagan** [khalwat/seomatic#141]
Hi Dude,

First time I've tried Seomatic, seems good so far!

Wondering if you've faced dealing with multiple opening hours before?

It appears that your plugin outputs data within a `openingHoursSpecification` specifying a `OpeningHoursSpecification` "type" for each day. 

I know there is really limited information on the best way to do this with schema (as I have looked), but, previously I have set that like this:

```
    "openingHours": [
        "Mo,Tu,We,Th,Fr 07:00-08:00",
        "Mo,Tu,We,Th,Fr 18:00-21:00",
        "Sa,Su 08:00-16:00"
    ]
```

One idea was to almost create a matrix type thing for this area, though I'd imagine you've already thought of that:
![image](https://cloud.githubusercontent.com/assets/2337910/18452907/b9a9be5c-7934-11e6-8f4b-fad5bf74cc68.png)
Where you could select the day/opening time/closing time, so multiple days could exist? Maybe that would work well with the current setup?

I'm not sure how I would be able to override this within my twig template? This doesn't appear to alter anything:

```
{% set seomaticMeta = seomaticMeta | merge({ "openingHoursSpecification":
    [
        {
            "@type": "OpeningHoursSpecification",
            "closes": "21:00:00",
            "dayOfWeek": ["Monday"],
            "opens": "18:00:00"
        }
    ]
}) %}

{% hook 'seomaticRender' %}
```

Have you any suggestions?

Many thanks

**Comment by khalwat** [comment]
Yeah so you have the right idea... but the opening hours are actually part of the `seomaticIdentity` variable.  If you go to the Site Meta tab, and click on **Preview Meta Tags** I think you'll see how to do it.

**Comment by joepagan** [comment]
Ah thank you, that mostly works! Though it appears to be missing out my merged hours within the "place" schema type:

```
<!-- Place -->

<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Place",
```

What variable would I need to update that? Also is there a list of these variables somewhere?

Many thanks

**Comment by khalwat** [comment]
Yeah go to SEOmatic->Site Meta and then click on the **Preview Meta Tags** button and you'll see all of the variables that are being injected.
