### ISSUE TITLE
Variable "seomaticMainEntityOfPage" does not exist

### ISSUE THREAD

**Issue by joepagan** [khalwat/seomatic#143]
Sorry if this has been posted before, bit new to your plugin, but, I couldn't find anything.

I've setup an SEOmatic field on a blog post, it's saved:
![image](https://cloud.githubusercontent.com/assets/2337910/18581281/cb86779e-7bf7-11e6-87de-2627b4ddd9a1.png)

When I click "Preview SEO Meta Tags", I can see the example object `seomaticMainEntityOfPage`, but, when I edit my template dump the variable & visit it, I get the message `Variable "seomaticMainEntityOfPage" does not exist`.

If I look at the normal schema that is output, it appears to be completely missing the `seomaticMainEntityOfPage` data I could preview on the entry.

I have tried doing this before & after the hook, but, doesn't make a difference, and, tried dumping it within the body of an entry template.

Am I missing something here? Or is this a bug?

**Comment by joepagan** [comment]
Figured out the issue here: 

If you select a default "Main Entity of Page" using the dropdowns when setting up an SEOmatic field, it does not honour it when the field is applied to an existing entry, if you change the value, then change it back to the one you want, it will output data.

**Comment by khalwat** [comment]
Hrm, I'm not sure that's right, it's probably that the section needs to be re-saved when adding an SEOmatic field to it?

**Comment by joepagan** [comment]
Maybe you're right and it was that, rather than selecting a new main entity. But, if I add a SEOmatic field to a new section, I would hope that I wouldn't have to potentially re-save hundreds of entries and that it would apply the defaults set to that field?

**Comment by khalwat** [comment]
No, if you add a field, the way Craft works (this isn't an SEOmatic thing) is that an empty field is added with no data.  You need to re-save the Section in order to populate newly added fields like SEOmatic with data.

This is in the documentation: https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

> If you add an SEOmatic FieldType to an existing Section that already has entries in it, you'll need to re-save the Section to populate the newly added SEOmatic FieldType with data. You can do this via Settings → Edit My Section → hit Save.

So you don't need to re-save each entry, just the Section -- that kicks off a Craft task that re-saves each entry for you.
