### ISSUE TITLE
add return false to button

### ISSUE THREAD

**Issue by joepagan** [khalwat/seomatic#145]
Not the end of the world but... on the page `/admin/seomatic/seometrics` clicking analytics adds a `#` to the url

Alternatively you could make it a `<button>`
![image](https://cloud.githubusercontent.com/assets/2337910/18608476/385049be-7ce2-11e6-9b0a-fe8a0ea136cd.png)

**Comment by khalwat** [comment]
Added the fix to `develop`:

https://github.com/nystudio107/seomatic/tree/develop

`[Improved] The Javascript for the SEOmetrics`Analyze`button now returns false to eliminate the #`
