### ISSUE TITLE
Migration added in v1.1.38 gets skipped

### ISSUE THREAD

**Issue by epfremmer** [khalwat/seomatic#146]
Ran into this issue while updating the plugin today. After updating the plugin code from v1.1.37 to v1.1.38 got a PHP Notice:

```
Undefined index: siteSeoTwitterImageId
/var/www/craft/plugins/seomatic/services/SeomaticService.php(1316)

1304         $siteMeta = array();
1305 
1306         $siteMeta['locale'] = $settings['locale'];
1307 
1308         $siteMeta['siteSeoName'] = $settings['siteSeoName'];
1309         $siteMeta['siteSeoTitle'] = $settings['siteSeoTitle'];
1310         $siteMeta['siteSeoTitleSeparator'] = $settings['siteSeoTitleSeparator'];
1311         $siteMeta['siteSeoTitlePlacement'] = $settings['siteSeoTitlePlacement'];
1312         $siteMeta['siteDevModeTitle'] = craft()->config->get("siteDevModeTitle", "seomatic");
1313         $siteMeta['siteSeoDescription'] = $settings['siteSeoDescription'];
1314         $siteMeta['siteSeoKeywords'] = $settings['siteSeoKeywords'];
1315         $siteMeta['siteSeoImageId'] = $settings['siteSeoImageId'];
1316         $siteMeta['siteSeoTwitterImageId'] = $settings['siteSeoTwitterImageId'];
1317         $siteMeta['siteSeoFacebookImageId'] = $settings['siteSeoFacebookImageId'];
1318         $siteMeta['siteSeoImageTransform'] = $settings['siteSeoImageTransform'];
1319         $siteMeta['siteSeoFacebookImageTransform'] = $settings['siteSeoFacebookImageTransform'];
1320         $siteMeta['siteSeoTwitterImageTransform'] = $settings['siteSeoTwitterImageTransform'];
1321 
1322         if (isset($settings['siteRobots']))
1323             $siteMeta['siteRobots'] = $settings['siteRobots'];
1324         else
1325             $siteMeta['siteRobots'] = '';
1326 
1327 /* -- Handle the organization contact points */
```

I was able to log into the admin without being prompted to "Finish Up" changes.

After a bit of research it looks like craft didn't run migration _m160904_000000_seomatic_addTwitterFacebookImages_ even after going to  the craft admin. 

I was able to work around this by running the `yiic migrate up seomatic` command on this plugin manually, but i have to imagine that other people may run into the same issue.

**Comment by khalwat** [comment]
Any indication as to why this migration didn't run?  I've seen it run on a few different installs...?

**Comment by epfremmer** [comment]
I can't figure out the commonality that causes this not to run. My closest guess, and the only way I was able to cause this was when I upgraded from v1.1.37 to v1.1.38 specifically.

Craft just doesn't seem to see the migration. I will try to put together a slimmed down example so we can test this in isolation and hopefully be able to reproduce this more reliably.

**Comment by khalwat** [comment]
Okay let me know if you can.  It's a little strange to me.

**Comment by epfremmer** [comment]
Well no luck reproducing this in isolation. I'm gonna chalk this one up to a fluke. Could very easily been something on my end as I was updating several plugins for this application yesterday.

Everything I tested on my vanilla craft install handled the plugin updates without issue. 

Closing issue. Thanks for the help!
