### ISSUE TITLE
Multi lingual meta data

### ISSUE THREAD

**Issue by alanski66** [khalwat/seomatic#147]
I have seven languages on site and seomatic 1.1.36
The meta title for each page gets the wrong language. Indeed the wrong meta title persists afterwards, seemingly in a random language.

I know localisation might not be complete but is there a way of preventing this happening?

I am implementing using seomatic field settings and rendering in template with  
{% hook 'seomaticRender' %}

cheers

**Comment by khalwat** [comment]
No, it is fully localized for such things.  Have a look:

https://www.43north.jp

https://www.43north.jp/ja/

**Comment by alanski66** [comment]
Great!
Glad its fully localized. Any ideas on the issue?

**Comment by khalwat** [comment]
Maybe you didn't set your SEOmatic field to be localizable?  I really don't know, without seeing exactly how you've set everything up.

**Comment by alanski66** [comment]
its friday I am an idiot.
Is there any way around having to open every localisation and save it in order for seomatic to 'see' the updated localisations?
[thx for your quick replies]

**Comment by khalwat** [comment]
That's not SEOmatic, that's just the way that Craft works.  You can try re-saving your sections that have SEOmatic fields in them, and see if that helps.
