### ISSUE TITLE
Error when using entry meta with eager loading

### ISSUE THREAD

**Issue by joshangell** [khalwat/seomatic#149]
If I loop over a channel and want to access the entry meta of an element whilst doing so, that’s fine. But if I eager load a field that is being used by SEOmatic to populate an SEO field (for example  when using an image field to populate the SEO Image field) then I get the following error: `Call to a member function first() on array`

![screen shot 2016-09-28 at 11 02 08](https://cloud.githubusercontent.com/assets/404219/18909332/1738dca0-856b-11e6-8d9d-292d82f28d50.png)

**Comment by khalwat** [comment]
Pushed a **completely untested** fix to `develop`:

https://github.com/nystudio107/seomatic/tree/develop
