### ISSUE TITLE
Make humans.txt optional?

### ISSUE THREAD

**Issue by jack-pallot** [khalwat/seomatic#150]
I generally like the idea of humans.txt, but I feel it should be optional, as some sites don't want to specify what's being used. When you clear this field out, it's automatically re-generated, and there doesn't seem to be a way around this. Would it be possible to have this as an optional field, that doesn't output if the field is empty?

**Comment by khalwat** [comment]
If it's empty, it defaults back to the original as a way for people to revert back to it in case they messed something up.

If you don't want it to display anything, just put a single space in the field.  It won't think it's empty then.
