### ISSUE TITLE
getFullyQualifiedUrl() doesn't respect URLs with no protocol

### ISSUE THREAD

**Issue by jameswbutts** [khalwat/seomatic#153]
"`//example.com/`" will get set to the relative root "`/`" instead of a fully qualified URL with no protocol.

See line 2945 of SeomaticService.php

SEOmatic version 1.1.37
Craft Pro 2.4.2679

Thanks!

**Comment by jameswbutts** [comment]
For now, it looks like I can use `siteUrlOverride` in the config file. It's not as clean as automatically using the `siteUrl`, but it should be a sufficient stopgap.

Thanks!

**Comment by khalwat** [comment]
Hrm.  The code looks like this:

```
    if (UrlHelper::isAbsoluteUrl($url) || UrlHelper::isProtocolRelativeUrl($url))
    {
/* -- The URL is already a fully qualfied URL, do nothing */
    }
```

So it should leave protocol-relative URLs alone.  Are you still seeing this issue with 1.1.39?

**Comment by jbutts-nerdery** [comment]
Sorry for the delay. I'm now running 1.1.40. I'll clear my override and update here if I run into issues again. Thank you!

**Comment by khalwat** [comment]
Okay cool, let me know.
