### ISSUE TITLE
SEOmatic causing entry forms to fail to load

### ISSUE THREAD

**Issue by afairhurst** [khalwat/seomatic#154]
Firstly thanks for the amazing plugin. Much appreciated.

I'm encountering an issue with SEOmatic causing entry forms to fail to load. See the attached screenshot. I think it's caused by the SEOmatic Fieldtype. Specifically the 'SEO Keywords' -> 'Keywords from Field' option. It seems like if the process of generating suggested keywords is failing... possibly a server issue? Maybe insufficient memory? The result is an entry form, which fails to load, effectively locking me out of making any further edits, which might resolve the issue.

Clearing Crafts cache doesn't resolve the problem. Might I be able to edit a database entry to clear the problem?

Any advice would be appreciated.

Thanks!

![craft-cms](https://cloud.githubusercontent.com/assets/4739932/19123086/3796806e-8b25-11e6-912d-86c9dfd5921a.png)

**Comment by khalwat** [comment]
It is very likely the Keywords generation, I use a third party library, and it doesn't seem very happy with PHP versions < 5.4 -- my guess is you'd be using PHP 5.3?

**Comment by afairhurst** [comment]
Hi. Thanks for your swift reply. PHP version is 5.6.24. I've got the entries working again, by downloading the database to local, where there isn't an issue. I then resaved each of the offending entries and then re-uploaded the database to live and voila... each entry form now loads. Not sure of the cause, however it's likely the poor hosting environment, which I'm tied to.

**Comment by khalwat** [comment]
hrm yeah it could be that the full PHP isn't installed, you can check the errors in your `craft.log` file to determine what it is.  I've seen `iconv` not be installed, and I've also seen some UTF-8 extensions not be installed, which can cause issues with this library.
