### ISSUE TITLE
Feature request - Can the [devMode] title prefix be optional?

### ISSUE THREAD

**Issue by joepagan** [khalwat/seomatic#155]
![image](https://cloud.githubusercontent.com/assets/2337910/19213230/844436f6-8d5d-11e6-880c-aefa952d88f0.png)

I find it quite unhelpful sometimes, as it even hides short page titles!

Maybe a devMode favicon would be more suitable for this feature? Regardless it would be very helpful to turn this off in the settings somewhere.

Thanks

**Comment by khalwat** [comment]
You can change this to be whatever you want via the `config.php` file:

```
/**
 * Determines the string prepended to the <title> tag when devMode is on.
 */
    "siteDevModeTitle" => '[devMode]',

```

**Comment by joepagan** [comment]
Thank you!
