### ISSUE TITLE
Feature request: Add support for Focal Point

### ISSUE THREAD

**Issue by sjelfull** [khalwat/seomatic#157]
Using image fields for the og:image is working well, but there's a big problem with it right now: We're currently using the Focal Point fieldtype to avoid cropping off heads and the like, but SEOmatic doesn't take that into consideration.

Would it be possible to add support for [Focal Point](https://github.com/aelvan/FocalPointField-Craft)? Maybe it makes sense to also add support for [Focus Point](https://github.com/smcyr/Craft-FocusPoint) then?

**Comment by khalwat** [comment]
The problem is that the native transform functions do not support the idea of cropping based on a percentage

**Comment by khalwat** [comment]
The best thing I can recommend is that you use Imager to create the actual transformed images, and then set them via Twig
