### ISSUE TITLE
Dealing with meta data on page where entry variable has been manually set

### ISSUE THREAD

**Issue by joepagan** [khalwat/seomatic#158]
Hey dude,

I am attempting to setup some AMP pages, I have setup a route in Craft like this:

![image](https://cloud.githubusercontent.com/assets/2337910/19417532/49be50c0-93a7-11e6-8eb3-70a3772a2ff0.png)

So in my `_amp` template I have set the `entry` variable like so:

```
{% set blogEntrySlug = craft.request.getSegment(2) %}
{% set entry = craft.entries.sectionId(3).slug(blogEntrySlug).first() %}
```

It appears that seomatic doesn't seem to use this entry variable. And serves the default site meta on these templates. 
I have managed to update the `seomaticMainEntityOfPage` variable like so (where blogMeta is my seomatic fieldtype handle):

```
{% set seomaticMainEntityOfPage = entry.blogMeta.getJsonLD(entry) %}
```

Is there another method I could use to accomplish this? Where seomatic would take the manually set `entry` variable?
Alternatively could I redefine all the other seomatic variables too in an easy way like the 1 line example above?

**Comment by khalwat** [comment]
Correct, it will only use `entry` if it was injected into the template by Craft.

I took a similar route you did for my AMP pages; just using Twig to set things the way I wanted them to be.
