### ISSUE TITLE
The attribute publisher.itemtype has an invalid value.

### ISSUE THREAD

**Issue by joepagan** [khalwat/seomatic#159]
On my blog posts at the moment (using the `blogPosting` mainEntityOfPage), it appears that google's validation tool does not like the "publisher" itemtype to be set as a "Person", [even though schema.org suggests this can be a "Person", or an "Organization"](https://schema.org/publisher).

![image](https://cloud.githubusercontent.com/assets/2337910/19618699/fc5cdc1e-9849-11e6-879e-75bb6c7002e5.png)

Have you experienced this before? When I edit the markup in the Schema tool, it seems to accept "Organization" if I change it manually, but, not "Person".

[Here is one of my posts in Google's schema tester tool so you can see](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.joe-pagan.com%2Fblog%2Fgoogle-pagespeed-optimising-decorative-template-images)

[Here is the post](https://www.joe-pagan.com/blog/google-pagespeed-optimising-decorative-template-images).

Let me know if you need anything else,

Many thanks

**Comment by khalwat** [comment]
That "Person" schema validates just fine on it's own; I'm not sure why Google would claim at the publisher can't be a @Person -- but I will say that although Google _uses_ the schema.org datatypes, what it wants in them can be a subset of what is _allowed_ to be in them.

This one doesn't make sense to me though, it seems perfectly valid for a Publisher to be a person.

**Comment by joepagan** [comment]
I will try find someone at google to speak to about this. My Search Console doesn't actually seem to show any `blogPosting` data types under the Search Appearance > Structured Data, despite me submitting all my blog posts to be indexed under the Crawl area, I don't think the schema on my posts are being picked up because of this.

**Comment by khalwat** [comment]
If Google parses it, but doesn't think it's valid, it'll list it that way in the Rich Snippets testing tool in your search console.

**Comment by joepagan** [comment]
Did you mean the Structured data area?

![image](https://cloud.githubusercontent.com/assets/2337910/19737626/0cf906f0-9bac-11e6-976e-5ed746aa3d6f.png)

Or the "Rich cards" area?

![image](https://cloud.githubusercontent.com/assets/2337910/19737123/1d14b450-9baa-11e6-96b2-7aace791566d.png)

I thought this was only for "cards" or amp pages? After looking a bit more I am thinking I should be seeing more data here like [Breadcrumbs](https://developers.google.com/search/docs/data-types/breadcrumbs).

**Comment by joepagan** [comment]
Google only allow `Organization` for `publisher` on schema.org types: `Article`,`NewsArticle`, `BlogPosting`, or `VideoObject`.
https://developers.google.com/search/docs/data-types/articles
