### ISSUE TITLE
Fieldtype Confusion

### ISSUE THREAD

**Issue by sg-modlab** [khalwat/seomatic#16]
I get the title, keywords, image, and description treatment for the field type .. though find them confusing a bit for clients potentially which goes against Craft interface elegance.

I don't get the implementation for Twitter Card Type, Open Graph Type, and Robot Meta.

a) Both Twitter Card Type and Open Graph Type both don't have a null value. So you are forced to override. This seems like a dealbreaker for usage ... unless I am missing something.

b) Seems odd that all three of these would be common per entry override options and because they won't be for most content added regularly (blog or news for example) feel they create more confusion for a client than value. This, thought not a dealbreak, does cause me pause with this plugin ... I love Craft because of power and ease of use/clarity. I'll choose plugins that match as you have an eye for eventually selling it ... b would cause me to reconsider purchase among some other small quibbles.

Hope this doesn't come across as too negative ... I do appreciate what you are cooking and becuase of that I share the feedback FWIW. For now, opting not to sue the fieldtype and just rolling my own fields that will overwrite your template defaults ... which frankly seems more Crafty to me.

**Comment by khalwat** [comment]
Thanks for the feedback!

Regarding the issues you raise:

a) You're right, they should have a null value for both.  I'll fix that in the next update.

b) The reason they are all there is consistency.  Anything you set in the SEO Site Meta you can override in SEO Template Meta, which you can override in SEO Entry Meta (and obviously Twig has free reign to override anything)

I do plan to add some additional things to the field type to make them more useful, including default settings for each field, set asset sources, and also very likely the ability to hide fields.

I do agree with you that using Twig to set some of this stuff is the more Craft-y way to do it, and it does give you total control.  But non-developers and also some developers really do benefit from the GUI, so I plan to improve it.

I definitely appreciate all of your feedback.  I'm going to leave this issue open until I get to some of the points raised.  They are all on my radar.

**Comment by sg-modlab** [comment]
I'd also add a wishlist item.

That elements in your fieldtype couldbe shown in entry views in Craft 2.5. For example if I want to see the entry title alongside it's overridden description and image to help me review my content at a glance and see which need editing.

Here's a view to showcase when I use my own custom fields to then override your templates. Love that I can do this.

![craft_2 5](https://cloud.githubusercontent.com/assets/529067/12582946/233ab4ac-c40e-11e5-9b26-b5b006215efa.png)

**Comment by khalwat** [comment]
@sg-modlab Yeah I think it'd be possible to do that.

**Comment by khalwat** [comment]
Small update for you... in the next build:

-- Both Twitter Card Type and Open Graph Type have null values
-- I'm looking into the ElementIndex views you want; I'm just not sure how to implement that in a way that doesn't break SEOmatic working on Craft 2.4.x

**Comment by sg-modlab** [comment]
Thank you, sounds good.

On Tue, Feb 2, 2016 at 12:41 PM, khalwat notifications@github.com wrote:

> Small update for you... in the next build:
> 
> -- Both Twitter Card Type and Open Graph Type have null values
> -- I'm looking into the ElementIndex views you want; I'm just not sure how
> to implement that in a way that doesn't break SEOmatic working on Craft
> 2.4.x
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nystudio107/seomatic/issues/16#issuecomment-178708254
> .

## 

seth giammanco
seth@mod-lab.com
ph 718.858.1066

minds on design lab
www.mod-lab.com
Subscribe to our Mailing List
https://confirmsubscription.com/h/y/12431274F3870FEA

**Comment by khalwat** [comment]
@sg-modlab you will probably like this:
![safariscreensnapz190](https://cloud.githubusercontent.com/assets/7570798/12790939/becf48aa-ca72-11e5-9f7e-d04deeee7a1f.png)

**Comment by khalwat** [comment]
...and this.  These are all global FieldType settings for the SEOmatic FieldType.
![safariscreensnapz198](https://cloud.githubusercontent.com/assets/7570798/12791029/368343a6-ca73-11e5-8cee-66d589ccd6f3.png)

**Comment by sg-modlab** [comment]
That all looks smart.

On Wed, Feb 3, 2016 at 12:39 PM, khalwat notifications@github.com wrote:

> ...and this. These are all global FieldType settings for the SEOmatic
> FieldType.
> [image: safariscreensnapz198]
> https://cloud.githubusercontent.com/assets/7570798/12791029/368343a6-ca73-11e5-8cee-66d589ccd6f3.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nystudio107/seomatic/issues/16#issuecomment-179366245
> .

## 

seth giammanco
seth@mod-lab.com
ph 718.858.1066

minds on design lab
www.mod-lab.com
Subscribe to our Mailing List
https://confirmsubscription.com/h/y/12431274F3870FEA

**Comment by khalwat** [comment]
You can't see it in the screenshot, but all of them allow for null values too, both in the defaults, and in the entry itself.

**Comment by sg-modlab** [comment]
Right on!

On Wed, Feb 3, 2016 at 12:45 PM, khalwat notifications@github.com wrote:

> You can't see it in the screenshot, but all of them allow for null values
> too, both in the defaults, and in the entry itself.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nystudio107/seomatic/issues/16#issuecomment-179370120
> .

## 

seth giammanco
seth@mod-lab.com
ph 718.858.1066

minds on design lab
www.mod-lab.com
Subscribe to our Mailing List
https://confirmsubscription.com/h/y/12431274F3870FEA

**Comment by khalwat** [comment]
Most of your suggestions have been implemented in version 1.1.0, which is now released.

If you want to file a new issue for the Element Index, please do.  I didn't get to it for this release.
