### ISSUE TITLE
How to enable SEO for parent section of Structure entires

### ISSUE THREAD

**Issue by danchristian** [khalwat/seomatic#164]
I have SEOMatic working for Single entries and entries of Sections created as 'Structure', but how can I enter individual page titles/descriptions etc for those parent pages?

For example `Home > Services > Service`, I can access the SEO tab for `Home` and `Service` fine, but how can I edit the SEO for the `Services` section? Currently the page just pulls in the default.

**Comment by khalwat** [comment]
You can either add a FieldType to the Single for the index pages (if one exists) or you can use Template Meta:

https://github.com/nystudio107/seomatic/wiki/04.-SEO-Template-Meta
