### ISSUE TITLE
Strange behavior of Google Analytics script rendering

### ISSUE THREAD

**Issue by ohlincik** [khalwat/seomatic#165]
I'm testing the SEOmatic plugin and I'm experiencing a very strange behavior that I was not able to debug.

I have a very simple website with 4 pages that are all singles:

- Home Page
- FAQs
- Features
- Contact

When I enable the Google Analytics script rendering by specifying the Google Analytics Tracking ID under Site Identity in SEOmatic, the analytics code is rendered on Home Page and Contact. It is not rendered on the FAQs and Features pages although all singles are setup exactly the same way. 

When I go to the affected pages in Control Panel and view the 'Preview SEO Meta Tags', the analytics script appears there:

![screenshot 2016-11-20 14 02 07](https://cloud.githubusercontent.com/assets/1297647/20465404/5ec70036-af2a-11e6-831d-760150fa9837.png)

But it is not returned as a part of the page source when I check in the browser:

![screenshot 2016-11-20 14 02 41](https://cloud.githubusercontent.com/assets/1297647/20465405/5ec7f6e4-af2a-11e6-8fec-76122c9d80af.png)

**Comment by khalwat** [comment]
Something isn't right; the SEO meta is just a template that renders; here's the code for the Google Analytics part:

```
{% if not craft.config.devMode and not craft.request.isLivePreview %}{{ craft.seomatic.renderGoogleAnalytics() |raw }}{% else %}<!-- Google Analytics script is NOT included in LivePreview or if devMode is on -->{% endif %}
```

So it won't render it if you're in `devMode` or if the if it's a Live Preview request.  There's nothing in there that should be dependent on what page you happen to be on.

I suspect something else is amiss.

**Comment by ohlincik** [comment]
Yes, that's exactly my point. This is just a straight-forward Craft setup:
- all 4 pages are generated through a shared base layout
- all 4 pages are using the same SEOmatic entry field
- all 4 pages have very simplistic content

Yet, the analytics script is rendered for only 2 of them. Any ideas what else I could check?

I really like this plugin a lot. It's incredibly well done and very useful. I'd like to get to the bottom of this issue.

**Comment by khalwat** [comment]
It really doesn't make any sense to me.  I suppose you could try putting some debugging code in:

`craft/plugins/seomatic/templates/_seo_meta.twig`

...to see why it might not be rendering it.  But it makes no sense to me at all that it would render on some pages, but not others.  I don't see anywhere that it could fail selectively like that, and I've never heard of this before.

**Comment by ohlincik** [comment]
So, I've done a lot of debugging and the issue seems to be pointing in the direction of some unexplained caching. I manually changed the output code of the SEOmatic plugin templates and nothing changed after hard-reloading the page. I have to actually change something in the SEOmatic meta contents through the entry in the CP to re-generate the meta output. Any insights?

**Comment by ohlincik** [comment]
Clearing the chaches under the Settings in CP seems to do the trick. Apparently, the SEOmatic output generation code gets cached somewhere along the way by Craft.

**Comment by khalwat** [comment]
hmmm, it's probably being cached by SEOmatic itself.  It generates a hash from the actual meta that it outputs.  I wonder why it's not being broken in this case.  Very interesting, nice sleuthing @ohlincik

**Comment by ohlincik** [comment]
Thanks. It actually makes sense that the SEOmatic cache would not be broken in my case. The analytics output is controlled by the main plugin settings and/or the configuration values. Once these are set it makes little sense to break the cache until the settings themselves are changed. In my case, I was not changing the settings but simply exploring the right format for multi-environment  SEOmatic config. I believe that what I experienced would not be an issue with regular usage.
