### ISSUE TITLE
Seomatic fields not rendering with Commerce Digital Products

### ISSUE THREAD

**Issue by Floriswijgergangs** [khalwat/seomatic#166]
The SEOmatic fields are not working in combination with the Digital Products entries. It's using the fallback data. This also happens when viewing the preview data inside the entry. 

Is it possible that you're awesome plugin will be compatible with it, or is there a known work-around for this issue?

**Comment by khalwat** [comment]
Thanks, I will have to look into this to see if there is something special about the digital products.

**Comment by khalwat** [comment]
I have this fixed in the `develop` branch. You can see it in action here: https://bradsformen.com/store/brads-mix-tape

It'll be rolled into the 1.1.40 release (soon-ish)
