### ISSUE TITLE
Installing with Composer errors

### ISSUE THREAD

**Issue by danlake** [khalwat/seomatic#168]
Installing this with composer currently errors as follows:

    Your requirements could not be resolved to an installable set of packages.

    Problem 1
    - nystudio107/seomatic 1.1.9 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.8 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.7 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.6 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.5 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.4 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.39 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.38 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.37 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.36 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.35 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.34 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.32 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.31 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.30 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.3 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.29 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.28 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.27 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.26 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.25 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.24 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.23 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.22 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.21 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.20 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.19 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.18 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.17 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.16 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.15 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.14 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.13 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.12 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.11 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.10 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.1 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - nystudio107/seomatic 1.1.0 requires crodas/text-rank dev-master -> satisfiable by crodas/text-rank[dev-master] but these conflict with your requirements or minimum-stability.
    - Installation request for nystudio107/seomatic ^1.1 -> satisfiable by nystudio107/seomatic[1.1.0, 1.1.1, 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.1.19, 1.1.20, 1.1.21, 1.1.22, 1.1.23, 1.1.24, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.29, 1.1.3, 1.1.30, 1.1.31, 1.1.32, 1.1.34, 1.1.35, 1.1.36, 1.1.37, 1.1.38, 1.1.39, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9].

**Comment by khalwat** [comment]
Yeah, you can see the answer to this here:

https://github.com/nystudio107/seomatic/issues/160
