### ISSUE TITLE
Upgrade doesnt work - DB errors?

### ISSUE THREAD

**Issue by nexflo** [khalwat/seomatic#17]
2016-01-27 13:46:14

Level   error
Category    application
Message Migration failed for plugin Seomatic. All later Seomatic migrations are canceled.
2016-01-27 13:46:14

Level   error
Category    application
Message Failed to apply migration: m151225_000000_seomatic_addHumansField (time: 0.003s)
2016-01-27 13:46:14

Level   error
Category    application
Message #0 /var/www/html/releases/1445249274/craft/app/etc/db/DbCommand.php(618): CDbCommand->execute()
2016-01-27 13:46:14

Level   error
Category    application
Message CDbCommand konnte das SQL-Statement nicht ausführen: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft_seomatic_settings' doesn't exist (/var/www/html/releases/1445249274/craft/app/framework/db/CDbCommand.php:358)
2016-01-27 13:46:14

Level   error
Category    system.db.CDbCommand
Message CDbCommand::execute() fehlgeschlagen: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft_seomatic_settings' doesn't exist. Der SQL-Ausdruck war: ALTER TABLE `craft_seomatic_settings` ADD `genericCreatorHumansTxt` text NOT NULL AFTER `personCreatorBirthPlace`.

**Comment by khalwat** [comment]
Basically, it's saying that a database table that SEOmatic creates on install doesn't exist.  I'm not sure how the db could be in this state, because none of the settings should work if that's the case.

Did you restore the db from a backup or something?

**Comment by khalwat** [comment]
In any event, you'll need to restore your database to one that has SEOmatic installed, or, uninstall and re-install SEOmatic.
