### ISSUE TITLE
Provide an better way to set entry/filed seomaticMeta from the template

### ISSUE THREAD

**Issue by timkelty** [khalwat/seomatic#170]
A common example for this need might be if you have a 404 single with an SEOmatic field.
SEOmatic wont work naturally, as the `entry` variable isn't automatically set in the template, and it usually set manually, e.g. `{% set entry = craft.entries.uri('404').first() %}`. The result is your default site meta is loaded, not the one set for that entry/single.

My interim solution is to create my own method  that calls SEOmatic:
`craft/plugins/custom/variables/CustomVariable.php`
```
	public function getElementMeta($element, $url = null, $locale = null)
	{
		$metaModel = craft()->seomatic->getMetaFromElement($element);

		craft()->seomatic->setEntryMeta($metaModel, $url ?? $element->url);
		$meta = craft()->seomatic->getGlobals('', $locale ?? craft()->language);

		return $meta['seomaticMeta'] ?? [];
	}
```

Example `404.twig`:
```
{% extends '_pages/types/default' %}
{% set entry = craft.entries.uri('404').first() %}
{% set seomaticMeta = seomaticMeta|merge(craft.custom.getElementMeta(entry)) %}
```

Works great, it would just be nice if it were possible to do without a custom plugin.

**Comment by khalwat** [comment]
Yeah I have plans for this in 2.0. It probably won't happen in the 1.x branch.
