### ISSUE TITLE
SEO Metrics in live Preview have lost their CSS styles

### ISSUE THREAD

**Issue by matt-adigital** [khalwat/seomatic#171]
Hi,

We have used this on a few sites now and had zero issues and absolutely love using it. But recently on one of our sites we have noticed that the SEO Metrics have stopped working in the live preview mode. The functionality is still there but all of the styling has disappeared. Here is an example of what we are now seeing:

![screen shot 2016-12-12 at 16 45 29](https://cloud.githubusercontent.com/assets/15085874/21108324/ba1c5012-c08c-11e6-84d2-54df892bd25e.png)

This sits at the bottom of the page after scrolling all the way down and isn't breaking the rest of the live preview thankfully. But as you can see from the inspector we have no JS issues in the console and we are running on PHP version 7.0.14 with Seomatic version 1.1.39 and Craft version 2.6.2954.

We have had a look around and reuploaded a fresh set of files for the addon but cannot seem to get the issue fixed. The same version is running without issues on another of our sites so I'd just like to ask if you have seen this issue before or have any idea of the cause of it? Thank you for your time, loving the blog posts by the way!

**Comment by khalwat** [comment]
So, I've never seen this happen before; since it's only happening for you one one site, perhaps there are issues with the Javascript or CSS on that site in particular?
