### ISSUE TITLE
writing invalid meta tags

### ISSUE THREAD

**Issue by achord** [khalwat/seomatic#172]
Is there a way to configure this tag? It is current invalid:

**Error: A document must not include both a meta element with an http-equiv attribute whose value is content-type, and a meta element with a charset attribute.**
From line 5, column 104; to line 6, column 63
LC</title><meta↩http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta↩

**Comment by khalwat** [comment]
The tag is correct; you must just have another `<meta charset` tag somewhere in your `<head>`

Remove it, and all will be well.
