### ISSUE TITLE
Outputting non-valid html meta code

### ISSUE THREAD

**Issue by KnutSv** [khalwat/seomatic#174]
If I use SEOmatic and try to validate the page's html code I get this:

```
A document must not include both a meta element with an http-equiv attribute whose value is content-type, and a meta element with a charset attribute.
From line 15, column 1; to line 15, column 69
 SEO -->↩↩<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />↩<meta
```

A bit annoying since it's the only part of the site not validating.

**Comment by khalwat** [comment]
This is because you have an additional `<meta charset` tag somewhere in your `<head>` -- remove it, and all will be well.
