### ISSUE TITLE
where is the PHP-XML extension

### ISSUE THREAD

**Issue by bevans** [khalwat/seomatic#177]
In the installation instructions we are told that "The SEOmetrics feature requires PHP 5.4 or later and that you have the php-xml extension installed." WHen I click the link for "php-xml extension I am taken to http://osticket.com/forum/discussion/8702/php-fatal-error-call-to-undefined-function-utf8-encode-error-message
There is nothing on that page for an xml extension. This seems to be an incorrect link. Where do I get the php-xml extension from?

**Comment by khalwat** [comment]
That is the correct page; basically your sysadmin (or you) needs to build PHP with that extension added. It's a requirement from a library that SEOmatic uses, not SEOmatic itself.
