### ISSUE TITLE
Google meta verification error

### ISSUE THREAD

**Issue by admench** [khalwat/seomatic#18]
Hi

I'm having a problem with the google meta tag for verifying the site.

At the top of the page body just after the <body> tag, adding the meta tag to seomatic results in:

```
"" />
"
<!-- Identity -->
```

And the google verifier does not work. I've uploaded the html file manually for now.

Thanks for such a great plugin!

**Comment by khalwat** [comment]
hmmmm.  What do you mean by "adding the meta tag to seomatic"?

You're only supposed to put the code in the fields in SEOmatic, not the entire tag...

**Comment by khalwat** [comment]
I've clarified things in the UI & docs for the latest build:

For the `<meta name='google-site-verification'>` tag. Only enter the code in the `content=''`, not the entire tag. [Here's how to get it.](https://www.google.com/webmasters/verification/)

**Comment by admench** [comment]
Ah, ok that's great! Thanks
