### ISSUE TITLE
Multiple GA Properties?

### ISSUE THREAD

**Issue by tkammerer2** [khalwat/seomatic#180]
Currently SEOMatic is only handling 1 GA property within the module.

Is there a way to support multiple properties through the plugin?  And if not can we configure this so the plugin does not overwrite our raw edits?  

https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers

**Comment by tkammerer2** [comment]
Will use the Tag Manager implementation for this as the solution.  But having this support built into that Analytics Module would still be pretty sweet.

**Comment by khalwat** [comment]
Yeah so this is something that won't happen in the 1.x branch of SEOmatic.

If you do need something more custom, I'd suggest either using GTM (as you are) or just disabling Google Analytics in SEOmatic, and "rolling your own" as normal.
