### ISSUE TITLE
Accentuated 'a' followed by a space returns an empty string when defining a value from a Twig template

### ISSUE THREAD

**Issue by pierrestoffe** [khalwat/seomatic#181]
Hi,

I just installed this plugin today and I'm running into the following issue:

If I use `{% set seomaticMeta = seomaticMeta|merge({'seoTitle': 'Bonjour a tous'}) %}` in my template, the seoTitle will indeed be replaced with that 'Bonjour a tous' string. If I were to use 'Bonjour à tous' though (mind the accent over the A), that string would simply return an empty seoTitle.

The funny thing is that 'Bonjour àtous' (without the second space) works, but 'Bonjourà tous' doesn't either.

So my understanding is that when a `à` is followed by a space, the plugin returns an empty string. Note that I didn't encounter this issue when testing with other accentuated characters (û, ö,...).

Let me know if I can help you debug this issue.

**Comment by khalwat** [comment]
Very strange. I will have a look.

**Comment by khalwat** [comment]
What version of PHP are you running, and in the `admin/utils` page, does it report that the `iconv` you have installed is faulty?

**Comment by pierrestoffe** [comment]
I'm using PHP 7.0.12. And indeed, the iconv version included is buggy (see attachment)
I guess this is out of our hands and we'll just have to wait (not an issue at all, I really don't depend on this).

![iconv support in Craft CMS](https://d17oy1vhnax1f7.cloudfront.net/items/2s1O2G0v0m2b2R3b0p3z/Screen%20Shot%202017-01-19%20at%2009.59.23.png?v=105a945d)

**Comment by khalwat** [comment]
From what I understand, the bugginess of iconv is independent of the php version, as it's a system lib.

**Comment by khalwat** [comment]
@pierrestoffe So I finally got around to testing this (sorry for the delay).

I'm not seeing this behavior on my setup. Here's what I put in my template:

```
{% set seomaticMeta = seomaticMeta|merge({'seoTitle': 'Bonjour à tous'}) %}
```

And here's the generated title:

```
    <!-- BEGIN SEOmatic rendered SEO Meta -->

<title>[devMode] nystudio107 | Bonjour à tous</title>
```

So I'd have to guess that this is something specific to your PHP setup.
