### ISSUE TITLE
Error when creating a new page

### ISSUE THREAD

**Issue by KnutSv** [khalwat/seomatic#182]
Just updated the plugin. When I save a new entry I get a PHP Notice `iconv(): Unknown error (22)`

Running PHP 5.6.7 in MAMP.

Note: This only happens when using the automatic keyword extraction function.

![image](https://cloud.githubusercontent.com/assets/821570/21929666/47a12a7a-d992-11e6-8462-bde3267157b0.png)

**Comment by khalwat** [comment]
You must not have `iconv()` installed in your local PHP setup.

**Comment by KnutSv** [comment]
I do have it installed. And the plugin worked fine before the update.

**Comment by khalwat** [comment]
You updated the plugin from what version, to what version?

I don't recall changing this section of the code at all in a very long time, but you can check the commit history to see what changed.

All I was able to find that seems relevant is: https://github.com/roundcube/roundcubemail/issues/2590

**Comment by KnutSv** [comment]
Odd, after re-starting the system i no longer get the issue. Guess MAMP was acting up. Sorry for the inconvenience.
