### ISSUE TITLE
Bug - Articles to have image associated with them

### ISSUE THREAD

**Issue by nkpindolia** [khalwat/seomatic#183]
I ran a couple tests using Google's Structured Data Tool where the main entity of the page is selected as NewsArticle and the tool said that image is required for articles `	A value for the image field is required.`

**Comment by nkpindolia** [comment]
updating title

**Comment by khalwat** [comment]
From looking at the code, if there is an SEO Image set for an entry, it will create an `image` for the `mainEntityOfPage` ->

https://github.com/nystudio107/seomatic/blob/master/services/SeomaticService.php#L2099
