### ISSUE TITLE
Bug - Accented character in text throws error "iconv(): Unknown error (22)" (through ElementApi)

### ISSUE THREAD

**Issue by Ticolyle** [khalwat/seomatic#184]
This may be related to [Issue #181](https://github.com/nystudio107/seomatic/issues/181) but I'm opening a new issue since I have a specific error message.

We configured an SEOmatic field to automatically generate keywords using our main body rich text field. The  particular article in question with the error happens to be about Iceland and has some non-english accents included for city names. Examples: `Háifoss, Reykjavík, Gló`

We did not see this error in the actual template, but when we were fetching the entry using the Element API plugin. We include the description and are fetching it from the SEOmatic field itself as follows (`'desc' => $entry->postSeo->seoDescription`).

Normally I wouldn't open an issue for conflicting plugins, but this seems to be de-coupled from the interaction of the two.

When it tried to process the entry, the elmentAPI response  threw the `iconv()` error: 
```
iconv(): Unknown error (22)
```

And the craft stack trace errors on `cleanupText($text)`
```
3003         try
3004         {
3005             $keywords = $textRank->getKeywords(
3006                 $this->_cleanupText($text)
3007             );
3008         }
```

When it calls `iconv()`
```
3110 /* -- convert to UTF-8 */
3111 
3112         if (function_exists('iconv'))
3113             {
3114                 $text = iconv(mb_detect_encoding($text, mb_detect_order(), true), "UTF-8//IGNORE", $text);
3115             }
3116             else {
3117                 ini_set('mbstring.substitute_character', "none");
3118                 $text = mb_convert_encoding($text, 'UTF-8', 'UTF-8');
3119             }
3120 
```

This behavior disappeared after I removed the generated keyword `Háifoss`.

**Comment by khalwat** [comment]
This very likely is an issue with the `iconv` you have installed.

**Comment by khalwat** [comment]
What version of PHP are you running, and in the `admin/utils` page, does it report that the `iconv` you have installed is faulty?

**Comment by Ticolyle** [comment]
Oh dang, your absolutely right. I should have checked this before reporting a bug (doh).

Although neither self-report as faulty, my local and staging environment are mis-matched.  I'm running 7.1 locally and staging is still on 5.3. 

Local has implemented iconv() through `libiconv` and staging through `glibc` so of course my results are different. Interestingly, its my local 7.1 version with `libiconv` that seems to be throwing the error, not `glibc` on staging.

We're going to proceed with our updates as planned, and I will test again after we make those changes. Is there a preferred version of the iconv implementation you suggest?

Thanks again for your help @khalwat
