### ISSUE TITLE
Is there a built in way to override og:title, og:description and twitter equiv in entry meta? 

### ISSUE THREAD

**Issue by mischacolley** [khalwat/seomatic#185]
I'm not sure if I've missed how you can override these in the docs or it just isn't a feature? If it's not a feature is it planned or do you have a suggested approach?

**Comment by Emkaytoo** [comment]
I've been meaning to write this issue, too. 

Sometimes you want a different OG title/description. SERPs and social media have different audiences. SERPs are typically people *looking* for a solution, whereas Facebook/LinkedIn are usually more passive audiences. The same piece of content could be relevant for both audiences, but they have different triggers/cues to help them find it.

**Comment by khalwat** [comment]
These things can always be overridden via Twig:

https://github.com/nystudio107/seomatic/wiki/10.-Dynamic-Twig-SEO-Meta
