### ISSUE TITLE
"Look up Latitude/Longitude"

### ISSUE THREAD

**Issue by lindseydiloreto** [khalwat/seomatic#186]
You may want to put the lat/lng & lookup _below_ the address fields.

Otherwise, it's confusing to know what the lookup is based on (and will inevitably fail because the user hasn't reached those fields yet).

<img width="716" alt="Look up Latitude/Longitude" src="https://cloud.githubusercontent.com/assets/5309692/22224519/ca11ec2c-e173-11e6-986c-6b766d2fecd2.png">

**Comment by khalwat** [comment]
hrm yeah, but the coords that it looks up are above the button. It might be even weirder if you clicked the button, and nothing appeared to happen because the Latitude/Longitude fields were off of the screen, no?

**Comment by khalwat** [comment]
I'll shuffle the whole block around for the next release.

**Comment by khalwat** [comment]
Implemented in 1.1.42: https://github.com/nystudio107/seomatic/releases/tag/1.1.42

**Comment by lindseydiloreto** [comment]
Fantastic, much better!

If I had to nitpick, I'd mention the spacing between the fields & button... But that's incredibly minor, so feel free to ignore it. :)

Thanks man!
