### ISSUE TITLE
Image URL based on server root, not siteUrl

### ISSUE THREAD

**Issue by haabe** [khalwat/seomatic#187]
If the site is within a subfolder, the image path turns out wrong. The plugin clearly believes it should be on root level.

The image path should have {{ siteUrl }} as a prefix.

**Comment by khalwat** [comment]
Can you be more specific? I'm not exactly clear on what you're saying?

**Comment by haabe** [comment]
If I install the CraftCMS index.php at somehost.com/somedirectory/index.php and set the uploads folder to ". /myuploads", ie somehost.com/somedirectory/myuploads/, seomatic thinks the uploads path is somehost.com/myuploads/.

**Comment by khalwat** [comment]
Are you sure that your asset URLs are correct? Looking at the code, SEOmatic is just taking the asset URL and ensuring that it is fully qualified.

I also need more information in terms of where the image URL is coming from? Are we talking about an SEOmatic FieldType or...?

**Comment by haabe** [comment]
Yep, you're right. I reconfigured the public url field for the uploads, and seomatic used the correct urls. My bad.
