### ISSUE TITLE
Google analytics gets called twice

### ISSUE THREAD

**Issue by pierrestoffe** [khalwat/seomatic#190]
I have this issue where the analytics js file is called twice by seomatic. Note that it was also outputted (only once then) when I had not entered my tracking code in seomatic just yet.
<img width="519" alt="screen shot 2017-02-04 at 22 44 32" src="https://cloud.githubusercontent.com/assets/1706605/22621838/483d2950-eb2d-11e6-9616-35378abe1436.png">

**Comment by khalwat** [comment]
It is very likely not an issue with SEOmatic; what's very likely going on is elsewhere in your templates, you are including the GA JavaScript
