### ISSUE TITLE
Add `sameAs` for Wikipedia

### ISSUE THREAD

**Issue by lindseydiloreto** [khalwat/seomatic#193]
My client has requested a `sameAs` reference for Wikipedia. Apparently this is suggested practice if a company has a corresponding Wikipedia page.

http://searchengineland.com/leveraging-wikidata-gain-google-knowledge-graph-result-219706

https://schema.org/sameAs

If that seems excessive, then perhaps we need a generic way to add _whatever_ `sameAs` links are needed?

**Comment by khalwat** [comment]
Implemented in 1.1.42: https://github.com/nystudio107/seomatic/releases/tag/1.1.42

![google chromescreensnapz348](https://cloud.githubusercontent.com/assets/7570798/22866376/9a9fa526-f143-11e6-8f09-79a2f5bb8e4f.png)

**Comment by lindseydiloreto** [comment]
Working perfectly, thanks man!
