### ISSUE TITLE
Undefined index: googleAnalyticsAnonymizeIp

### ISSUE THREAD

**Issue by bennobo** [khalwat/seomatic#195]
Hi there,

I geht the following error message after updating to the latest version (1.1.42):

> Internal Server Error
> 
> Undefined index: googleAnalyticsAnonymizeIp

Any hint how to fix that?

Regards
Ben

**Comment by khalwat** [comment]
It looks like the migrations didn't run. Can you get them to run?

**Comment by khalwat** [comment]
https://craftcms.com/classreference/consolecommands/MigrateCommand

**Comment by khalwat** [comment]
This means that the migrations didn't run, or somehow didn't complete.

Can you please check the `seomatic.log` file in `craft/storage/runtime/logs/` to see if you see lines like this:

```
******************************************************************************************************
2017/02/13 18:13:47 [info] [plugin] [Forced] Created the `googleAnalyticsAnonymizeIp` in the `seomatic_settings` table.
in /home/vagrant/sites/nystudio107/craft/app/etc/plugins/BasePlugin.php (65)
in /home/vagrant/webdev/craft/seomatic/migrations/m170212_000000_seomatic_addGoogleAnalyticsAnonymizeIp.php (44)
in /home/vagrant/webdev/craft/seomatic/migrations/m170212_000000_seomatic_addGoogleAnalyticsAnonymizeIp.php (21)
2017/02/13 18:13:47 [info] [plugin] [Forced] Created the `wikipediaUrl` in the `seomatic_settings` table.
in /home/vagrant/sites/nystudio107/craft/app/etc/plugins/BasePlugin.php (65)
in /home/vagrant/webdev/craft/seomatic/migrations/m170212_000000_seomatic_addWikipedia.php (45)
in /home/vagrant/webdev/craft/seomatic/migrations/m170212_000000_seomatic_addWikipedia.php (21)

******************************************************************************************************
```

I just ran the upgrade on another install, and it worked without issue.

**Comment by khalwat** [comment]
I've heard from a number of people who _are_ able to update without issue.

Those of you having problems, can you post your MySQL and PHP versions?

**Comment by bennobo** [comment]
- MySQL 5.6.19
- PHP Version 5.6.21

Both log files don't show anything alike and it seems to be something on our side as nobody else is complaining. Therefore I reinstalled as I have to move on.

**Comment by kouk** [comment]
i faced the same problem today:
```
ii  mysql-server-core-5.5            5.5.54-0+deb8u1             amd64        MySQL database server binaries
ii  php5-mysql                       5.6.30+dfsg-0+deb8u1        amd64        MySQL module for php5
ii  php5                             5.6.30+dfsg-0+deb8u1        all          server-side, HTML-embedded scripting language (metapackage)
```

**Comment by kouk** [comment]
upgraded from 1.1.39 to 1.1.43

**Comment by khalwat** [comment]
@kouk for whatever reason, the update migrations didn't run. It's some kind of a local setup issue, but I don't know what it would be in your specific case.

You can try to manually run the migration in the `craft/plugins/seomatic/migrations` directory, or you can uninstall and re-install the plugin.
