### ISSUE TITLE
Being able to better filter what end users see in the SEOmatic field (Feature request)

### ISSUE THREAD

**Issue by noregt** [khalwat/seomatic#196]
I learned a lot from setting up SEOmatic, like the JSON-LD data, but I want to keep things as simple as possible for the end user. Right now clients get scared away when they see the SEOmatic field. For instance, when I've assigned the meta description form to another fixed field, it still shows that information. I would also like to get rid of the image transforms and all the extra explanations there (make a fixed choice in the field settings). And optionally hide the main entity of the page. Maybe also combine images for Twitter, Facebook and the general SEO image. (handle transforms in the background). The shorter it gets, the better.

**Comment by khalwat** [comment]
Probably not something I'm going to be doing for SEOmatic 1.x for Craft 2.x. It's something I certainly have in mind for the Craft 3 version, however.
