### ISSUE TITLE
Meta Tab Not Showing

### ISSUE THREAD

**Issue by jayhlee** [khalwat/seomatic#197]
I installed the plugin and the plugin panel shows properly with all the options. However, when I go to my entries, I don't see the Meta Tab next to the Content tab. My understanding was that it'd automatically show up after I install the plugin. Is that not the case? If so, can you let me know what I have to do? Thanks!

**Comment by khalwat** [comment]
There is no "Meta" tab automatically created for you. You'll need to create an SEOmatic Meta Field to add to whatever channels you want:

https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

If you want to put it in a tab called "Meta" or "SEO" or whatever you like, you certainly can.

**Comment by jayhlee** [comment]
Gotcha. Thanks!
