### ISSUE TITLE
Support on 'addTrailingSlashesToUrls' setting

### ISSUE THREAD

**Issue by GewoonRoy** [khalwat/seomatic#198]
When the config 'addTrailingSlashesToUrls' is set to true the seomatic Canonical doesn't add the trailing slash to it's canonical url.

What expected is that the url without a trailing slash will have a canonical with trailing slash.

**Current situation when 'addTrailingSlashesToUrls' is true**
**Called url** : example.com/my-webpage
**Canonical**: example.com/my-webpage

**Called url** : example.com/my-webpage/
**Canonical**: example.com/my-webpage/

**Expected situation when 'addTrailingSlashesToUrls' is true**
**Called url** : example.com/my-webpage
**Canonical**: example.com/my-webpage/

**Called url** : example.com/my-webpage/
**Canonical**: example.com/my-webpage/

**Comment by khalwat** [comment]
I checked a fix into the `develop` branch that should address this for you:

https://github.com/nystudio107/seomatic/tree/develop
