### ISSUE TITLE
More options in Template Meta

### ISSUE THREAD

**Issue by glenwith1n** [khalwat/seomatic#199]
When you edit an entry you can select which image field to use for the facebook/twitter image can this option be placed the the template meta settings so all my product pages uses "productImage" and all my project pages use "projectImage" for instance.
My other issue is I can't get the template path correct, all my pages use a base template and then I have multiple entry type template in a folder called "entrytypes" which all extend the base template. So what should the path be?
entrytypes/product
base/product
Can't get the template meta to work, please help.

**Comment by khalwat** [comment]
It should match exactly whatever you have entered Sections -> Edit Section -> *Entry Template* settings.

For instance, here's my blog:

![google chromescreensnapz378](https://cloud.githubusercontent.com/assets/7570798/23275606/29fd04c2-f9d5-11e6-9bb4-ae12a18b3ed0.png)

On disk, the template is: `craft/templates/blog/index.html`

So in SEOmatic, it should be exactly: `blog/index`

**Comment by khalwat** [comment]
You're right that the Template Meta are currently missing the ability to have separate images for Twitter, Facebook, etc.

For now, you have two choices:

1) Create a single for these "index" pages, and add an SEOmatic FieldType to that single, and use the SEOmatic FieldType to set your separate images

2) Set them yourself in your Twig template ala: https://github.com/nystudio107/seomatic/wiki/10.-Dynamic-Twig-SEO-Meta
