### ISSUE TITLE
SEO Template

### ISSUE THREAD

**Issue by garmeeh** [khalwat/seomatic#2]
Is the SEO template meta feature an upcoming feature? 

I have set up one and set the template path. I have filled in the fields but it still is showing up the Site meta for that page/template.

I am using the default: 

 `{% hook 'seomaticRender' %}`

Am I missing something that needs to go into template?

**Comment by khalwat** [comment]
If you click on the **Preview SEO Meta Tags** button when editing a Template Meta:

![safariscreensnapz003](https://cloud.githubusercontent.com/assets/7570798/11956343/e92183ac-a88f-11e5-8807-653c78226aab.jpg)

You should see that the preview is `Rendered For:` that Template Meta:

![safariscreensnapz002](https://cloud.githubusercontent.com/assets/7570798/11956358/0599613a-a890-11e5-9236-9bbe83b28017.jpg)

Then when that template is loaded in Craft for rendering on the front-end, those SEO Template Meta variables will be used.  I just tested it with the above, and it's working properly.  Are you not seeing this?

I can see the applied `seoTitle` in my browser window for this Template Meta:

![safariscreensnapz004](https://cloud.githubusercontent.com/assets/7570798/11956767/f7af1ea4-a892-11e5-9b9e-980f2ca896cf.jpg)

**Comment by garmeeh** [comment]
Ah thanks. I had the incorrect template reference in. 

Thanks for the speedy reply. Great Plug-In!!
