### ISSUE TITLE
Pingo-o-matic/RPC?

### ISSUE THREAD

**Issue by RitterKnightCreative** [khalwat/seomatic#20]
Wondering if there any merit in incorporating a [ping-like](https://codex.wordpress.org/Update_Services) functionality in seomatic?

I've read mixed things in terms of SEO benefits; some say it has little value, others say it helps a lot with traffic. WordPress does this by default, out of the box when you publish (or edit) a post. For people that use Craft for news/blogging, I could see how it would be valuable.

It'd be trivial to include I'd think with Craft's inclusion of Guzzle, just need the URL of the blog and hook in after a post in that section is created.

BTW: Great plugin. I really need to sink my teeth into this one. Been doing things the "old-fashioned" way (creating fields, etc) but this plugin really streamlines things and it really well thought-out.

**Comment by khalwat** [comment]
@RitterKnightCreative thanks, glad you're enjoying it.  

As for your "ping" comment, what do you mean, exactly?

I assume you don't mean pinging the search engines (which is something that Sitemap plugins do, to notify them of content/structural changes), but rather the block ping-back system as described here:

https://en.support.wordpress.com/comments/pingbacks/

Something like that is really pretty specific to WordPress, it'd only really work if everyone you linked to was using SEOmatic.  Even then, I'm not really sure how beneficial it would actually be.

In effect what it does is create an automatic backlink for you.

**Comment by khalwat** [comment]
I found this to be a pretty good discussion of them:

https://www.elegantthemes.com/blog/resources/wordpress-trackbacks-and-pingbacks

I appreciate the suggestion, but I think it's likely not something I'll be doing for SEOmatic.

> So are pingbacks and trackbacks dead? Well, not yet, but I think they’re limping on their last leg.
> 
> You have a better chance of connecting with a blog owner and their readers by simply taking the time to write helpful and engaging comments on their blog. Most blogs will allow commenting on posts, and though many of them have a no follow attribute to the links connected to a comment, you still have a better chance of gaining meaningful traffic and authority from blogs that relate to your own site.

**Comment by RitterKnightCreative** [comment]
Right, not ping-backs. Those things are spam traps waiting to happen.

What I mean is "pinging" aggregation sites like ping-o-matic when you post new content. You're right, sitemaps do some of that work but pinging can usually get content to show up faster.

For what it's worth, EE has it built into the core as well:
http://agentdir.com/cp/admin/default_ping_servers.html

It's basically just a XML-RPC POST call and platform agnostic. It's one direction, unlike a "pingback" where you get notified whens someone links to you.

**Comment by khalwat** [comment]
Ah, I see.  Interesting, how many sites actually respond to pings these days?  It almost seems antiquated, but perhaps I'm just not familiar enough with it.

**Comment by RitterKnightCreative** [comment]
I wouldn't bother with many but Ping-o-matic. [This site](http://htwp2.com/to-ping-or-not-to-ping/) seems to agree.

FWIW, Moz recommends their use in their venerable [_Beginners' Guide to SEO._](https://moz.com/beginners-guide-to-seo/basics-of-search-engine-friendly-design-and-development) (near the bottom).

> When you publish content in any type of feed format, such as RSS or XML, make sure to ping the major blogging and tracking services (Google, Technorati, Yahoo!, etc.). You can find instructions for pinging services like Google and Technorati directly from their sites, or use a service like Pingomatic to automate the process. If your publishing software is custom-built, it's typically wise for the developer(s) to include auto-pinging upon publishing.
