### ISSUE TITLE
Broken sitemap link in default robots.txt

### ISSUE THREAD

**Issue by davidteal** [khalwat/seomatic#201]
Hi guys.

First of all, thanks for making such a great plugin. It makes Craft an even better sell!

Unless we've got something misconfigured, we've noticed that the default robots.txt file that is generated has a broken sitemap link. Craft renders `{{ siteUrl }}` with a trailing slash so the `Sitemap: {{ siteUrl }}/sitemap.xml` appears as `Sitemap: http://example.com//sitemap.xml` which throws a 404.

**Comment by khalwat** [comment]
No, you don't have anything misconfigured; there's just no great way to tell whether or not the `siteUrl` has a trailing `/` on it or not.

I updated the default `robots.txt` template to handle this more gracefully in the build in `develop`:

https://github.com/nystudio107/seomatic/tree/develop

If you want to just update the template in your existing version, just use this Twig code:

```
# robots.txt for {{ siteUrl }}

Sitemap: {{ siteUrl |trim('/', 'right') }}/sitemap.xml

# Don't allow web crawlers to index Craft

User-agent: *
Disallow: /craft/
```

**Comment by davidteal** [comment]
Hi khalwat.

This doesn't work for me.  It just outputs `Sitemap: /sitemap.xml`. I tried the same code on a template and an exception is thrown complaining about the extra argument. I'm using the latest Craft 2.* build which has Twig 1.24 installed. Looks like the side param was added in 1.32: http://twig.sensiolabs.org/doc/1.x/filters/trim.html

**Comment by khalwat** [comment]
hmmmm. Try just: 

```
# robots.txt for {{ siteUrl }}

Sitemap: {{ siteUrl |trim('/') }}/sitemap.xml

# Don't allow web crawlers to index Craft

User-agent: *
Disallow: /craft/
```

**Comment by davidteal** [comment]
Hi khalwat.

That seems to be do the trick, thanks. I actually think `{{ siteUrl }}sitemap.xml` would work too as Craft serves the siteUrl with a trailing slash at all times.

Thanks for your help.

**Comment by khalwat** [comment]
Well, the user can set whatever they want in the `siteUrl`, and there is a setting `stripTrailingSlashes` that they can be using as well, so we shouldn't assume there will be no `/`
