### ISSUE TITLE
Meta description tags not getting parsed in Japanese

### ISSUE THREAD

**Issue by 43north** [khalwat/seomatic#204]
I'm having an issue where the meta description on Japanese sites is not getting parsed correctly and instead it shows "..." - see screenshot. This is happening randomly, not on every entry. In the screenshot, you can see the OG, Twitter tag for the description gets parsed fine but the Meta and Dublin Core description doesn't...I can't seem to identify why it's happening. I'm seeing this on more than one site. Any ideas?

<img width="865" alt="2017-03-04 at 10 56 12" src="https://cloud.githubusercontent.com/assets/1050192/23574990/3b3d5282-00c9-11e7-94bb-ca57095c1a9e.png">

**Comment by khalwat** [comment]
So I think what this might be is that some of the descriptions might not have spaces in them. And I think the `truncateOnWord()` method might not handle it well if you pass in a string that's longer then the length it's supposed to truncate to, but has no spaces to use as word breaks.

So you can try either adding spaces into the descriptions, or in the `config.php` set the various `truncate` values to `false`.

As an alternative, I'm also open to PRs with a proper "wrap on word" that works better for Japanese/Chinese scripts, too :)

**Comment by 43north** [comment]
Setting `truncateDescriptionTags` to false in config.php solved it - thanks!
