### ISSUE TITLE
FR: Ability to pull in fields from static Super Table rows

### ISSUE THREAD

**Issue by theskyfloor** [khalwat/seomatic#205]
I have several sites where I did a custom SEO implementation but now I want to move to SEOmatic. Rather than redo all of the content I would love it if I could just assign the fields to SEOmatic. All of the current SEO fields are in a single static supertable row. Or would the best way to do this just edit the SEOmatic output in the template?

**Comment by khalwat** [comment]
So while support for the SuperTable field could be added, it might be a little ugly, because you'd need a sub-field chooser for every sub-field in the table.

It's probably easier/better to just set this stuff via Twig:

https://github.com/nystudio107/seomatic/wiki/10.-Dynamic-Twig-SEO-Meta
