### ISSUE TITLE
[Bug] Social image meta gets '/' on the end of the url's

### ISSUE THREAD

**Issue by GewoonRoy** [khalwat/seomatic#206]
#198 There has been a change to respect the 'addTrailingSlashToUrls' setting. First of all, thank you for the change to respect the addTrailingSlashToUrls.

It seems that in version 1.1.43 the social meta tags adds a trailing slash to the image url's. It should respect the image url by not adding the trailing slash. (Maybe other url's which doesn't need the trailing slash as well?).

**Comment by khalwat** [comment]
Ah yes, this should be fixed.

**Comment by khalwat** [comment]
Fixed:

* Add a trailing / if `addTrailingSlashesToUrls` is set, but only if there's on extension

Check out the build checked into `develop`:

https://github.com/nystudio107/seomatic/tree/develop

...and let me know if that works for you.

**Comment by GewoonRoy** [comment]
@khalwat I checked the changes and it looks good, Thanks!
