### ISSUE TITLE
SEO Template Meta is ignored

### ISSUE THREAD

**Issue by samc36** [khalwat/seomatic#208]
Very similar to: https://github.com/nystudio107/seomatic/issues/9

I have the latest version of seomatic, and am on 2.6.2996 on Craft.

Basically, normal site meta works fine, but the specific template meta, is not overwriting that.

Any ideas?

**Comment by khalwat** [comment]
Probably the path you are using for the template meta isn't right. Can you post more info please?

**Comment by samc36** [comment]
Yep, will do now sorry.

So my template group would be called Stories, or Contact Us, and following the wiki where it says:

"Template Path - Enter the path to the template to associate this meta with (just as you would on the Section settings). It will override the SEO Site Meta for this template. Leave any field blank if you want it to fall back on the default global settings for that field."

I've tried:

- /stories/index.html

- stories
and I've tried

- stories/index

 

The last one is working on other sites, I'm not sure why it's not working here, it's possible it's a conflict with another plugin or the version of CRAFT I'm using.

Other plugins I'm using:

- Amforms

- Minimee

- HTML Cache

**Comment by khalwat** [comment]
`stories/index` is correct. 

I don't think it's a conflict with Craft, or any other plugins.

But I see that you're using a static caching plugin; are we sure that it isn't just that something is cached here?

**Comment by samc36** [comment]
Thanks for your help khalwat, still haven't got it working though. 

So all my template paths are correct, and "Preview SEO Meta Display" works correctly.

I don't think it's the static caching plugin as at the time of posting the first message, the cache was busted and disabled. I've completely uninstalled the cache plugin and still no joy.

When it was installed, it was and now still is actively updating the site meta, just won't override with specific template meta.

This is the hook in my template to pull in the seomatic meta:

`{% hook 'seomaticRender' %}`

**Comment by khalwat** [comment]
So the preview uses the same technique that the actual render uses, so that's quite puzzling.

I'm unable to reproduce this locally. Given that this works for you on other sites, are we sure that there isn't something specific to _this_ site that is causing the issue?

**Comment by samc36** [comment]
Found it, thanks loads for your help. 

It's on an Azure server, must be some form of caching active, seomatic is working locally, and it is updating the site meta on the live server, just not the template meta, also not displaying the favicon.

So there's nothing wrong with Seomatic, it's working perfectly.

**Comment by khalwat** [comment]
Thanks for getting back to me on that!
