### ISSUE TITLE
Meta Tab Not Showing

### ISSUE THREAD

**Issue by orchidsite** [khalwat/seomatic#209]
After watching the tutorial video for SEOmatic here: https://www.youtube.com/watch?v=f1149YVEF_0 
I realize I am not seeing all of the same tabs and buttons on SEOmatic. 

I am running Craft 2.6.2967. I installed SEOmatic and am able to access tabs "SEOmetrics, Template Meta, Site Meta, Site Identity, Social Media, Site Creator, and Settings. However, when viewing an entry, I do not see a Meta tab. I only have the Content Tab.

**Comment by khalwat** [comment]
There is only a "Meta" tab (or whatever you decide to name it) if you create it. Then you can add your SEOmatic FieldType to that tab if you want; but that's just an organizational thing.

**Comment by orchidsite** [comment]
Thank you! This really helps. Appreciate you taking the time.
ᐧ

Best,

Ivan Mills - General Manager

<http://thevanillaorchid.com/>
7433 Burnet Road, Austin, TX 78757
o 512 610 2134 <%2B1%20512%20610%202134> | c 512 785 7225
<%2B1%20512%20287%204238>
      www.thevanillaorchid.com

         <https://www.facebook.com/TheVanillaOrchid/?fref=nf>
<https://www.google.com/maps/place/The+Vanilla+Orchid/@30.3499173,-97.7359788,17z/data=!3m1!4b1!4m8!1m5!8m4!1e2!2s100549428209334567837!3m1!1e1!3m1!1s0x8644c9be79a6d1f5:0x93a8ffb3abf1b228>
  <https://www.instagram.com/vanillaorchidtx/>
<https://www.pinterest.com/vanillaorchidtx/>
<https://twitter.com/vanillaorchidTX>
<http://www.yelp.com/biz/the-vanilla-orchid-austin>

Download our new Vanilla Orchid iphone app <https://appsto.re/us/V5vWhb.i>
and order from our Lunch & Delivery menu.
