### ISSUE TITLE
Include site name everywhere except home page?

### ISSUE THREAD

**Issue by joshuatuscan** [khalwat/seomatic#210]
I've been searching around trying to find the answer to if this is possible but can't find anything. I'd simply like to leave off the site name on the home page only. By default it works across my site, but on the homepage I'd like the site name to be the title and that's it, but as it is now it's just duplicating the same phrase.

**Comment by khalwat** [comment]
Yes, you can do this:

```
{% set seomaticSiteMeta = seomaticSiteMeta | merge({'siteSeoTitlePlacement': 'none' }) %}
```

This should be in your template that extends your `layout.twig`, outside of any `{% block %}` content.
