### ISSUE TITLE
Remove canonical URL from 404

### ISSUE THREAD

**Issue by jacquesletesson** [khalwat/seomatic#211]
Hi there,

We are trying to remove the canonical url from the 404 page.

When we omit the canonicalUrl parameter we have a *Twig Error Runtine* : 

> Key "canonicalUrl" for array with keys "seoTitle, seoDescription, seoKeywords, seoImage" does not exist in "_seo_meta" at line 19

If we pass a null value the canonical url is empty but still present.

```
{% set seomaticMeta = {
    seoTitle: "Some Title",
    seoDescription: "Some Description",
    seoKeywords: "Some,Key,Words",
    seoImage: seomaticMeta.seoImage,
    canonicalUrl: null
} %}
```

Is it possible to remove completely the canonical URL from SeoMatic?

**Comment by khalwat** [comment]
hmmm... so you want it to entirely omit the tag? You could do something like:

```
{% set seomaticMeta = seomaticMeta | merge({'canonicalUrl': '/404.html' }) %}
```

So that the canonical URL for any 404 pages points to the 404 page itself. Omitting the URL entirely is an interesting idea though.

**Comment by khalwat** [comment]
Okay, the build in the `develop` branch addresses this: https://github.com/nystudio107/seomatic/tree/develop

* If the current request is a 404, set the `canonicalUrl` to an empty string
* If the `canonicalUrl` is set to an empty string, don't render the `<meta rel='canonical'` tag
