### ISSUE TITLE
SEOMatic field first in list in Element Editor Modal

### ISSUE THREAD

**Issue by jeremyabrahams** [khalwat/seomatic#212]
Apologies if my terminology/taxonomy is off in here/title

My set up looks like this:
CMS Tab 1: Basic content fields
CMS Tab 2: SEOMatic alone

On a structure page that has an entry field (Linked entries) if you click on one of the entry names you can see the fields of that entry. The css has class of .hud and . elementeditor

Within this list SEOmatic appears first even though it is 10 out of 10 fields and appears in the second tab.

- If I move SEOmatic field to the bottom of Tab 1 it appears in order
- If I add a 3rd tab, SEOMatic still appears first

I actually don't know if this is a bug with SEOmatic or not, but it is the only plugin/field I've experienced this issue with.

**Comment by khalwat** [comment]
Can you post a screenshot of this so I can understand what's going on?

**Comment by jeremyabrahams** [comment]
Here is the Element Editor Modal with SEOMatic showing up first.
https://cl.ly/2X001k3o0q2o

Here is the field/tab layout in the section editor screen
https://cl.ly/2p3b0E3d242n

**Comment by khalwat** [comment]
So I tried to replicate this in local dev, but couldn't.

Here is the Element Editor Modal:

![google chromescreensnapz450](https://cloud.githubusercontent.com/assets/7570798/24226127/062fc5cc-0f3b-11e7-97a1-26debd416b97.png)

Here is the field/tab layout in the section editor screen:

![google chromescreensnapz451](https://cloud.githubusercontent.com/assets/7570798/24226136/12c0dcb8-0f3b-11e7-8bde-22d20bc800d0.png)

`Blog SEO` is my SEOmatic FieldType. Maybe it's some weird CSS/layout issue that only happens in certain strange circumstances, like the Entries field is at the top of the page (so there isn't much room for it) or the tab that holds the SEOmatic field is taller than the tab that hold the other content fields?

Either way, you can try inspecting the elements in the browser to see if you can uncover what's going on from a CSS/layout POV?

**Comment by jeremyabrahams** [comment]
https://cl.ly/0V2m1L3m1f3d
Here's a screengrab of the markup. Showing up second after the title field.

**Comment by khalwat** [comment]
Weird. I don't think this is anything specific to SEOmatic, though. I'm really not sure what is wrong, there should be some HTML/CSS around it to show it in a separate tab?

Or when you use that ElementModal maybe it shows ALL of the fields (regardless of tab), and shows them in the order in which the fields are created or something?
