### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by jan-dh** [khalwat/seomatic#215]
After the latest update I get this:

```
Can't use function return value in write context in ../craft/plugins/seomatic/services/SeomaticService.php on line 3079

Fatal error: Interface 'Craft\Iterator' not found in ../craft/app/framework/collections/CListIterator.php on line 21
```

**Comment by khalwat** [comment]
So... I'd suggest redoing the update or such. The errors don't seem to really make sense:

https://github.com/nystudio107/seomatic/blob/master/services/SeomaticService.php#L3079

**Comment by khalwat** [comment]
Try this build from the `develop` branch:

https://github.com/nystudio107/seomatic/tree/develop

**Comment by khalwat** [comment]
Yeah so it should be an issue only if you're running PHP 5.4 or earlier: http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context

Anyway, fixed in the SEOmatic build that is in the `develop` branch.
