### ISSUE TITLE
Yoast-like validation

### ISSUE THREAD

**Issue by hisnameisjimmy** [khalwat/seomatic#216]
One really cool thing that Yoast does for Wordpress is have a very intuitive green/yellow/red system for evaluating the optimization level of a page. You simply input the primary keyword (or keywords) for the page and have it evaluate how well you're doing. This is enormously useful for laymen authors on a website who might not be aware of how to optimize the page, and it gently nudges them to make improvements without the 'SEO expert' getting involved. Everyone wants the green light.

While there are no hard and fast rules for what constitutes a well optimized page, there are some best practices, and I would love a similar type of validator for Craft CMS.

Do you think this is something you might consider for seomatic?

**Comment by khalwat** [comment]
Have you seen the SEOmetrics feature, which is available in Live Preview for any entry (as well as via the Admin CP)?

It does this, and more.
