### ISSUE TITLE
Am I doing something wrong

### ISSUE THREAD

**Issue by mattymulligan** [khalwat/seomatic#217]
Hi Guys, 
have installed the plugin and able to edit site meta etc.

However when posting an Entry like Blog for example, there is no tab for SEO, like the example in the video.
See screenshot..what am I doing wrong?

![capture](https://cloud.githubusercontent.com/assets/15361511/24397943/a6c1754a-139f-11e7-8835-aaa4586f6717.PNG)

Thanks, 
Matthew

**Comment by Ticolyle** [comment]
Hey Matthew, not the dev but you'll need to add a new field using the `SEOmatic Meta` field type.

https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

**Comment by khalwat** [comment]
^ he's correct

**Comment by mattymulligan** [comment]
HI Guys, 
still not working and have added the field..

![2](https://cloud.githubusercontent.com/assets/15361511/24511742/7efd77b8-1564-11e7-9296-a7bf8b32a988.PNG)
![3](https://cloud.githubusercontent.com/assets/15361511/24511741/7efb055a-1564-11e7-8bd2-d826c8b1f7bb.PNG)
![4](https://cloud.githubusercontent.com/assets/15361511/24511740/7efa1438-1564-11e7-9f91-1e55574f4de0.PNG)

**Comment by khalwat** [comment]
You have to add it to the layout for your `Blog` channel, just like any other Craft field.
