### ISSUE TITLE
Canonical url adds trailing slash if addTrailingSlashesToUrls is set to false

### ISSUE THREAD

**Issue by babau67** [khalwat/seomatic#218]
Hi,

I have the opposite situation described here (that now works with the last plugin update)
[https://github.com/nystudio107/seomatic/issues/198](url)

When the config 'addTrailingSlashesToUrls' is set to false the seomatic Canonical adds the trailing slash to it's canonical url.

What expected is that the url with a trailing slash will have a canonical without trailing slash.

Current situation when 'addTrailingSlashesToUrls' is false
Called url : example.com/my-webpage
Canonical: example.com/my-webpage

Called url : example.com/my-webpage/
Canonical: example.com/my-webpage/

Expected situation when 'addTrailingSlashesToUrls' is false
Called url : example.com/my-webpage
Canonical: example.com/my-webpage

Called url : example.com/my-webpage/
Canonical: example.com/my-webpage

Could be an issue or maybe I had to do something else to set a unique canonical?

Thanks

Barbara

**Comment by khalwat** [comment]
I'm not sure I understand fully? You have it saying:

    Expected situation when 'addTrailingSlashesToUrls' is false

...for both of the cases?

**Comment by babau67** [comment]
No, I have two different canonicals (with and without trailing slash) only when I set it to false.
If I set it to true, canonical output is correct, it's the same (both with trailing slash at the end).

1) If in my config.php if I set:
 'addTrailingSlashesToUrls' => false,

if the called url is : example.com/my-webpage
the Canonical is: `<link rel="canonical" href="http://example.com/my-webpage" />`

if the called url is : example.com/my-webpage/
the Canonical is: `<link rel="canonical" href="http://example.com/my-webpage/" />`


2) If in my config.php if I set:
 'addTrailingSlashesToUrls' => true,

if the called url is : example.com/my-webpage
the Canonical is: `<link rel="canonical" href="http://example.com/my-webpage/" />`

if the called url is : example.com/my-webpage/
the Canonical is: `<link rel="canonical" href="http://example.com/my-webpage/" />`

Hope it's clear,

thanks

**Comment by khalwat** [comment]
Yeah so this is "expected behavior"—the option is just `addTrailingSlashesToUrls`, in other words, it will add slashes to URLs. 

If it's set to `false`, it does not remove the slashes. It just doesn't add them. This is consistent with how Craft handles this config setting.

The responsibility of handling things like removing trailing slashes from URLs should be in your server config, for example:

https://github.com/nystudio107/nginx-craft/blob/master/sites-available/somedomain.com.conf#L40
