### ISSUE TITLE
Remove 'Google Analytics Tracking ID' field from 'Site Identity' if 'renderGoogleAnalyticsScript' is false

### ISSUE THREAD

**Issue by danherd** [khalwat/seomatic#219]
I think this would neaten things up slightly.

No point having that field visible if you're got no intention of using it.

**Comment by khalwat** [comment]
Well, often people use `renderGoogleAnalyticsScript` in a multi-environment way, to turn the rendering off for local dev, for instance, but not off in other environments. So we'd probably still want the field to be visible.

**Comment by klick** [comment]
Is this documented somewhere? I assume this is an environment variable, no? Can not find it in the wiki. 

The AMP version of my templates do not validate because SEOmatic renders `<script>` which is prohibited by Google.

**Comment by khalwat** [comment]
Have a look at the `config.php` file in the Seomatic plugin's folder, it has documentation in there on how it works.

As for your AMP templates, you can do this in your AMP template:

```
{% set seomaticHelper = seomaticHelper |merge({'ownerGoogleAnalyticsUID', 0}) %}
```

Which just sets your Google Analytics ID to 0, which will cause it to not render the GA script. Or you can turn GA off in the SEOmatic settings, and include it yourself.

**Comment by klick** [comment]
Cool, thanks. That worked.
Do you accept donations btw?

**Comment by khalwat** [comment]
Nope, enjoy! :D
