### ISSUE TITLE
FR: Transfer and categorize / group all documentation to wiki

### ISSUE THREAD

**Issue by johanneslamers** [khalwat/seomatic#22]
The documentation is getting BIG and bloated. Would it be nice to group / categorize this and add it to the wiki? And maybe leave some TLTR / install / best practice on main README.md.

**Comment by khalwat** [comment]
That's a good idea, I'd been considering that already.  I'll leave this issue open.

**Comment by johanneslamers** [comment]
:-) Would love to see some best practice / examples to show the potential of the plugin.

**Comment by khalwat** [comment]
I know a number of companies that are using it, if that's what you mean by the potential.  In general, I agree with you that a "QuickStart" guide is a good idea too.

**Comment by khalwat** [comment]
Okay, the docs have all been wikified and the README.md has been trimmed down:

https://github.com/nystudio107/seomatic

The complete docs are still in `DOCS.md` as well, if anyone wants them.
