### ISSUE TITLE
Broken README link 

### ISSUE THREAD

**Issue by jayhlee** [khalwat/seomatic#221]
Hi Andrew, just wanted to let you know that the "View Documentation" link in the Plugins control panel is broken. It currently goes to https://github.com/khalwat/nystudio107/blob/master/README.md. 

Seems like the new location is https://github.com/nystudio107/seomatic/blob/master/README.md

Thanks for all your great work!

**Comment by khalwat** [comment]
Fixed it in the `develop` branch, thanks
