### ISSUE TITLE
GTM - dataLayer isn't updating

### ISSUE THREAD

**Issue by owldesign** [khalwat/seomatic#223]
Hey I have placed the dataLayer json as described in the docs above the hook but looking at source code the `dataLayer = []` is empty. Is this a bug or I'm missing something?

<img width="450" alt="screen shot 2017-04-10 at 1 25 48 pm" src="https://cloud.githubusercontent.com/assets/438764/24880982/40a6ff58-1df1-11e7-97d0-889aff15bd10.png">

![screen shot 2017-04-10 at 1 26 24 pm](https://cloud.githubusercontent.com/assets/438764/24881018/5733fbea-1df1-11e7-997c-790b352aa023.png)

**Comment by khalwat** [comment]
So this is what the template looks like:

```
{% if seomaticHelper.ownerGoogleTagManagerID %}
<script>
  {{ gtmDataLayerVariableName }} = [{% if dataLayer is defined and dataLayer %}{{ dataLayer |json_encode() |raw }}{% endif %}];
  (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','{{ gtmDataLayerVariableName }}','{{ seomaticHelper.ownerGoogleTagManagerID }}');
</script>
{% endif %}
```

I don't think it's a bug, but I'm not sure what is doing on in your case. Maybe trying dumping `{{ dump(dataLayer) }}` to look at what it actually looks like?

You're not setting `dataLayer` in another template right?

**Comment by john-henry** [comment]
Craft CMS 2.6.2973 & SEOMatic 1.1.46

I can replicate this also. Either by setting dataLayer in layout template or extended template. Both return nothing.

**Comment by khalwat** [comment]
@john-henry can you do what I mentioned above, and try dumping the dataLayer variable to see what it's set to?

Maybe trying dumping {{ dump(dataLayer) }} to look at what it actually looks like?

**Comment by john-henry** [comment]
@khalwat If I dump the dataLayer in my layout or extended template it renders array.

The issue is that nothing is being rendered in_googleTagManager.twig.

That variable is not available to that template so currently `if dataLayer is defined and dataLayer` is never true

> You're not setting dataLayer in another template right?

What do you mean by this? I'm setting the datalayer in a template that extends my layout.html template

**Comment by khalwat** [comment]
I'm looking into this now, I think I know what's going on.

**Comment by khalwat** [comment]
I pushed a build to the `develop` branch that should fix this issue for you:

https://github.com/nystudio107/seomatic/tree/develop

I tested it with this:

```
    {% set dataLayer = {
        'pageCategory': 'signup',
        'vistorType': 'high-value'
    } %}
    {% hook 'seomaticRender' %}
```

Which then rendered this on the frontend:

```
<!-- Google Tag Manager -->

<script>
  dataLayer = [{"pageCategory":"signup","vistorType":"high-value"}];
  (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','12345');
</script>
```

Let me know how you go?

**Comment by john-henry** [comment]
@khalwat this now works. Thanks for the fast response Andrew

**Comment by khalwat** [comment]
Great, thanks for the follow-up!
