### ISSUE TITLE
PHP warning when i use keywords from source option.

### ISSUE THREAD

**Issue by amos-whitewolf** [khalwat/seomatic#225]
![pasted image at 2017_04_18 09_53 am](https://cloud.githubusercontent.com/assets/9377462/25111368/ee2578c0-242d-11e7-85d2-f6b1e4526a07.png)

Wondering if i have set something up wrong, the vendor files seem to be there when i ssh in.

**Comment by khalwat** [comment]
What version of PHP are you using? SEOmatic uses a third party lib for the keyword generation, and it requires that `iconv` is up to date, and a reasonably complete PHP installation.
