### ISSUE TITLE
Bug: Entity description 

### ISSUE THREAD

**Issue by johanneslamers** [khalwat/seomatic#23]
Adding Entity Description info gives me an Internal Server Error

CDbCommand failed to execute the SQL statement: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'genericOwnerDescription' at row 1

**Comment by khalwat** [comment]
Sounds like the description is very long; it should be gracefully handling this.  I'm assuming you're running MySQL in strict mode?

**Comment by khalwat** [comment]
@johanneslamers What version of MySQL are you running?

**Comment by khalwat** [comment]
This should be fixed in the `develop` branch.  I'll roll out 1.1.1 soon-ish.

**Comment by khalwat** [comment]
This should be fixed in the `develop` branch.  I'll roll out 1.1.1 soon-ish.
