### ISSUE TITLE
Video embeds for social media cards?

### ISSUE THREAD

**Issue by atomworks** [khalwat/seomatic#230]
I've got a channel on my Craft site that always has a featured video. When I share the link to social media it will make a card for the page but I was wondering if there was some kind of way to change this so that it actually embeds the video in to the social media feed rather than just the card for the page.

Is this possible? I couldn't find any information regarding this but everything seems to be so well featured and used here I imagine it's possible somehow and hopefully already has a solution.

**Comment by khalwat** [comment]
To do this, you'd need to add the appropriate OpenGraph tags for video. Currently, SEOmatic doesn't support this, but you can easily add your own in the `<head>` as per:

http://ogp.me/#type_video

**Comment by atomworks** [comment]
Perfect. Thank you. I didn't stop to think the answer would be that obvious! 

Be cool to see this feature built-in in the future though.
