### ISSUE TITLE
SEOmatic cannot analyze sites over https

### ISSUE THREAD

**Issue by jimstrike** [khalwat/seomatic#232]
I get  the following error:

file_get_contents(): SSL: Connection reset by peer.

Maybe thise would resolve the issue?

`$response = file_get_contents($url, false, stream_context_create(array(
 'ssl' => array( 'verify_peer' => false, 'verify_peer_name' => false ) 
)));`

**Comment by khalwat** [comment]
It definitely works over SSL, I use it that way fairly often. Is there a possibility that something isn't set up right with the SSL?
