### ISSUE TITLE
Merging seomaticMeta data, but not rendered

### ISSUE THREAD

**Issue by haabe** [khalwat/seomatic#233]
I've put `{% hook 'seomaticRender' %}` within the head of my _layout file.

Then I have a dynamic template file displaying content from an external source. This template file extends _layout.

As described in the docs, I've tried merging seomaticMeta data to set the metadata to reflect the dynamically loaded content.

`{% set seomaticMeta = seomaticMeta | merge({ seoTitle: title }) %}`

But it seems like it renders the hook before the seomaticMeta is merged. Am I doing something totally wrong?

**Comment by haabe** [comment]
I've been digging around a little, and concluded that `{% set seomaticMeta = seomaticMeta | merge ... %}` only works if there aren't many loops before it is executed.

**Comment by khalwat** [comment]
It shouldn't be a matter of loops, but you might be encountering a Twig scoping issue:

https://nystudio107.com/blog/twig-processing-order-and-scope
