### ISSUE TITLE
Meta field initialisation fails on locale

### ISSUE THREAD

**Issue by ockam** [khalwat/seomatic#235]
I have a meta field set as translatable with 2 locales (en + fr). 

On some entries (entries where the field hasn’t been modified have the correct behavior), there is an error on the `fr` locale: the field options that should be feeded to the plugin via jQuery are undefined (field.js at line 34). Those values should be set in `Seomatic_MetaFieldType`class at line 50 ($jsonVars).

![screen shot 2017-05-08 at 11 17 06 am](https://cloud.githubusercontent.com/assets/229621/25811172/599c437e-33e0-11e7-9dcf-ee8766f129b2.png)

In the screen shot you can see that the select input and text preview field are still there. And the preview buttons don not work.

Sadly, I can’t give you a way to reproduce this because the entries were modified by another person who can’t give me those details.

If there’s a way to reset the field for those entries, that would be enough for me since there’s not a lot of content yet.

**Comment by khalwat** [comment]
It'd be super helpful if you were able to give me steps to reproduce this?

**Comment by ockam** [comment]
Finally found the problem: in `Seomatic_MetaFieldType.php`, at line 198:
```
$jsonVars = json_encode($jsonVars);
```
json_encode return false because of some unicode characters (in my case, an à).

I tried the `JSON_UNESCAPED_UNICODE` flag but that had no effect. I don’t have a solution (not a unicode specialist...) but at least I know the source of the issue.

**Comment by ockam** [comment]
Using `JSON_PARTIAL_OUTPUT_ON_ERROR` appears to solve my issue, but I can’t assert that wouldn’t have unwanted side effect.
```
$jsonVars = json_encode($jsonVars, JSON_PARTIAL_OUTPUT_ON_ERROR);
```

**Comment by ockam** [comment]
For the record, there are other accented characters in my field (a rich text Redactor field) that all work fine when I remove the `à`. I’ve retyped it (because sometimes when copying ans pasting some weird thing happen to Unicode characters) and checked it in the DB and it looks fine. But it keeps giving me an error...

This has nothing to do with Seomatic. But if you have any idea, I’m all ears.
