### ISSUE TITLE
Error on Draft preview

### ISSUE THREAD

**Issue by dgrigg** [khalwat/seomatic#236]
I'm getting this error when viewing a draft preview link

2017/05/09 20:15:11 [error] [php] Undefined property: Craft\EntryDraftModel::$url (/var/www/sorel/craft/plugins/seomatic/services/SeomaticService.php:1221)

The live preview window works fine, just the shareable preview link breaks.

**Comment by khalwat** [comment]
Try the version I just checked into the `develop` branch:

https://github.com/nystudio107/seomatic/tree/develop

It should take care of this issue for you.
