### ISSUE TITLE
Not showing Meta description + GA data

### ISSUE THREAD

**Issue by mattymulligan** [khalwat/seomatic#237]
Have SEOmatic set up..while the SEO preview shows the META description have added..when go to actual site the description is not there.

Plus have the GA tracking code in SEOmatic but showing no results in google analytics

Any ideas

**Comment by khalwat** [comment]
Did you add the

```
    {% hook 'seomaticRender' %}
```

To your template code?

**Comment by mattymulligan** [comment]
HI Khalwat, 
where does that go?..as in what file?

**Comment by khalwat** [comment]
https://github.com/nystudio107/seomatic/wiki/02.-Rendering-your-SEO-Meta-tags
