### ISSUE TITLE
GTM dataLayer not rendering

### ISSUE THREAD

**Issue by aarmitage** [khalwat/seomatic#239]
Hey Andrew,
Having some issues in getting the dataLayer values to render for GTM. We've tried some basic outputs in _googleTagManager.twig, but we're simply getting an empty array.

We've followed your exact example, placing the twig set array immediately before the seomaticRender hook, but it doesn't seem to extend into the template.

Also, this file seems to cache quite aggressively - we're wanting to output dataLayer variables on a checkout complete page (Craft Commerce), so will this work, or should we be using GA ecommerce instead?

Any thoughts?

Thank you,
Andrew

**Comment by khalwat** [comment]
This is fixed in the build in `develop`: https://github.com/nystudio107/seomatic/tree/develop
