### ISSUE TITLE
Template Metas don't work on Windows

### ISSUE THREAD

**Issue by davidteal** [khalwat/seomatic#240]
Hi Andrew.

Having issues using Template Metas on Windows, PHP 5.5. The issue seems to be caused by `$this->_get_current_template_path()` in SeomaticTwigExtension.php returning the full path e.g. `E:/sites/craft-site/craft/templates/contact/index` instead of `contact/index` which when passed to `Seomatic_MetaRecord::model()->find()` returns null.

**Comment by khalwat** [comment]
hmmmm. If you look at that function, it does try to decompose the path. Can you tell me where that is failing? https://github.com/nystudio107/seomatic/blob/master/twigextensions/SeomaticTwigExtension.php#L215

**Comment by davidteal** [comment]
Sure, just looked in to it more and it failed because `$templatesPath` is derived from `realpath()` which uses backslashes on Windows. So `if (substr($result, 0, strlen($templatesPath)) == $templatesPath)` fails (`'E:\web\sites\craft-welford\craft/templates/' == 'E:/web/sites/craft-welford/craft/templates/'`) = false. I'd just do `str_replace('\\', '/', $templatesPath)`

Happy to submit PR if needed

**Comment by khalwat** [comment]
@davidteal Sorry for not getting back to you sooner. I'd like to come up with a fix that works on any platform. I was going to use the PHP `DIRECTORY_SEPERATOR` to handle it, but I have no Windows platform to test on. Can you help?

**Comment by davidteal** [comment]
Hi khalwat.

To be honest I think this should be fixed on Crafts end by using `dirname(CRAFT_APP_PATH)` instead of `realpath(CRAFT_APP_PATH.'..')` as this is where the backslashes get added back in. I've raised an issue on Craft repo so we'll see what P&T say. If they don't think its worth fixing, I guess you could build the templates path yourself instead of using `craft()->templates->getTemplatesPath()` e.g.

`$templatesPath = dirname(CRAFT_APP_PATH) . '/templates/';`

**Comment by khalwat** [comment]
Alright, let me know how this goes.

**Comment by davidteal** [comment]
Brad didn't think it was an issue unfortunately so you'll have to roll your own fix for it: https://github.com/craftcms/cms/issues/1793

**Comment by khalwat** [comment]
I'd be happy to accept a PR for this fix; I just don't have a Windows environment on which I can test it unfortunately.

**Comment by khalwat** [comment]
Alright, I have no way to test this but... I added this code to the build in the develop branch:

    // Try to normalize things for Windows
    $currentTemplate = str_replace('\\', '/', $currentTemplate);
    $templatesPath = str_replace('\\', '/', $templatesPath);

Let me know if this works for you?

**Comment by davidteal** [comment]
Yeah that seems to do the trick

**Comment by khalwat** [comment]
Yay! I rolled it into the 1.1.49 release, too.
