### ISSUE TITLE
[Question] What determines the output 'This is the default global natural language...'?

### ISSUE THREAD

**Issue by aarmitage** [khalwat/seomatic#241]
Some search results are showing the following snippet in the Google.

> This is the default global natural language description of the content on the site pages. (sv)

What are the circumstances that determine this output? I can see the text is set deep down within seoMatic's files, but it's not being referenced anywhere in the page itself.

<img width="575" alt="screen shot 2017-05-29 at 21 35 02" src="https://cloud.githubusercontent.com/assets/1152884/26561472/b55d2e26-44b6-11e7-80e5-1dc89972fcf9.png">

**Comment by khalwat** [comment]
That's just the default setting for the seoDescription. It means that someone didn't fill in an seoDescription at all... or they left the site up with it missing, and Google indexed it.
