### ISSUE TITLE
Feature request: Add more permission settings

### ISSUE THREAD

**Issue by TomDeSmet** [khalwat/seomatic#243]
It would be nice if we could set permissions per settings page of SEOmatic.

I want my users to be able to edit their Site Meta, Site Identity and Social Media.

But I don't want them to be able to edit our Site Creator data, add Template Meta templates or change the name of the plugin as they may be confused of what a plugin actually is... So it's not a page they need to see.

**Comment by khalwat** [comment]
I like it, I think it's a good idea, but it's not likely to be something I do for the Craft 2.x version.
