### ISSUE TITLE
Can't Uninstall

### ISSUE THREAD

**Issue by artmem** [khalwat/seomatic#246]
I'm having issues trying to uninstall SEOMatic. When I disable the plugin, I get this error on every page that had previously had an SEOMatic field:

`Fatal error: Class 'Craft\Seomatic_MetaFieldModel' not found in /craft/app/helpers/ModelHelper.php on line 587`

Is there a specific method to follow to properly uninstall the plugin?

**Comment by khalwat** [comment]
You'll need to remove the SEOmatic FieldTypes that you've created from your site as well.

This really shouldn't be necessary, though.
