### ISSUE TITLE
Error on initial install

### ISSUE THREAD

**Issue by RobErskine** [khalwat/seomatic#25]
I'm getting the following error on installation on a (relatively) fresh Craft instance.

> **Internal Server Error**
> 
> CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'localBusinessOwnerOpeningHours' can't have a default value

I've disabled all other plugins. It looks like it's looking for [Pixel and Tonic's Store Hours](https://github.com/pixelandtonic/StoreHours) plugin?

**Comment by khalwat** [comment]
Download and install version 1.1.1 (just released).  It should fix this for you.
