### ISSUE TITLE
Unable to disable "Facebook OpenGraph Image Source Changeable" in field settings

### ISSUE THREAD

**Issue by benface** [khalwat/seomatic#251]
As the title says. To reproduce:

1. Create a new field of type SEOmatic.
2. Disable "Facebook OpenGraph Image Source Changeable".
3. Save the field.
4. Check the field settings again. "Facebook OpenGraph Image Source Changeable" is still enabled.

EDIT: It actually does effectively disable it, so the bug is that the switch in the form is always enabled regardless of the current value.

**Comment by khalwat** [comment]
This is fixed in the build checked into `develop`
