### ISSUE TITLE
Field for YouTube channel ID

### ISSUE THREAD

**Issue by benface** [khalwat/seomatic#252]
I know there are already two fields for YouTube:
- User handle (`youtube.com/user/`)
- Channel handle (`youtube.com/c/`)

But "Channel ID" is missing (`youtube.com/channel/`). If you don't have a user or channel handle and try to put the channel ID in the "channel handle" field, it won't be a valid URL.

**Comment by khalwat** [comment]
I'm probably not going to be adding this in the Craft 2.x plugin
