### ISSUE TITLE
Feature request: allow Twig in some fields

### ISSUE THREAD

**Issue by benface** [khalwat/seomatic#253]
- In the Site SEO Name, to be able to do `{{ siteName }}` instead of duplicating it
- In the social network fields, in case the same information already exists in a global set: `{{ global.socialNetworks.type('twitter').find().accountHandle }}`
- Maybe in the SEO Title and SEO Description fields?

**Comment by khalwat** [comment]
This is how it will work in SEOmatic for Craft 3, but not for Craft 2.x.

**Comment by benface** [comment]
Good to hear! Thank you. :)
