### ISSUE TITLE
Is "always" a valid value for meta tag "referrer"?

### ISSUE THREAD

**Issue by benface** [khalwat/seomatic#254]
I don't see it referenced here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy. I believe `unsafe-url` would be the standard name for it?

**Comment by khalwat** [comment]
Yes, it is valid.  https://wiki.whatwg.org/wiki/Meta_referrer

**Comment by benface** [comment]
> This document is obsolete.
For the current specification, see: [Referrer Policy](https://w3c.github.io/webappsec-referrer-policy/)

**Comment by khalwat** [comment]
You're right, I think defaulting to `no-referrer-when-downgrade` would be best.

**Comment by khalwat** [comment]
This is fixed in the `develop` branch in 1.1.49
