### ISSUE TITLE
Feature request: ability to customize meta tag "generator"

### ISSUE THREAD

**Issue by benface** [khalwat/seomatic#255]
You know, if we want to change it to "Craft CMS with Twig & SEOmatic". Or just not include it at all.

**Comment by khalwat** [comment]
You can do this if you really want to by supplying a template for SEOmatic to use in the `{% hook 'seomaticRender' %}` as per: https://github.com/nystudio107/seomatic/wiki/02.-Rendering-your-SEO-Meta-tags

**Comment by benface** [comment]
Fair enough. :)
