### ISSUE TITLE
Suggestion: don't render JSON-LD "Place" objects if they don't contain any new information

### ISSUE THREAD

**Issue by benface** [khalwat/seomatic#256]
Here's some JSON-LD that was generated by SEOmatic:
```
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Corporation",
    "sameAs": ["TWITTER_URL","FACEBOOK_URL","INSTAGRAM_URL"],
    "location": {
        "@type": "Place",
        "sameAs": ["TWITTER_URL","FACEBOOK_URL","INSTAGRAM_URL"] 
    } 
}
```
I don't believe the `location` node serves any purpose. I suggest not including it when there's no address (not even a city or a country) whatsoever. There are some other useless `location` nodes in the "WebSite" object.

Finally, I think the whole "Place" object shouldn't be rendered in my case:
```
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Place",
    "sameAs": ["TWITTER_URL","FACEBOOK_URL","INSTAGRAM_URL"] 
}
```

I understand that I can change the values in the meta objects in Twig and customize the template that outputs all this stuff, but I believe this is something that could be improved "out of the box". Feel free to disagree!

**Comment by benface** [comment]
While we're at it, I suggest not including the `author` and `creator` keys of the WebSite object if they're like this:
```
    "author": {
        "@type": "Corporation",
        "sameAs": ["TWITTER_URL","FACEBOOK_URL","INSTAGRAM_URL"],
        "location": {
            "@type": "Place",
            "sameAs": ["TWITTER_URL","FACEBOOK_URL","INSTAGRAM_URL"] 
        } 
    },
    "creator": {
        "@type": "Organization" 
    } 
```

**Comment by khalwat** [comment]
It definitely serves a purpose; if present, iOS will read it and present it as a suggestion to find on the map for directions.

**Comment by benface** [comment]
Sorry, just to be clear, I meant that I don't think it serves any purpose when it doesn't actually HAVE an address or any information other than "sameAs" links.
