### ISSUE TITLE
Feature request: ability to disable robots.txt altogether

### ISSUE THREAD

**Issue by benface** [khalwat/seomatic#257]
... by entering nothing in the "robots.txt Template" field. Right now if you do that and save, that field reverts to its default value.

**Comment by khalwat** [comment]
What would the reason for doing this be? It seems like it'd always be better to have _some_ policy than none?

**Comment by benface** [comment]
Of course you're right, but the reason is user-friendliness. If I clear that field and save, I expect it to be empty when the page reloads, but it's back to being filled with a policy I don't necessarily want. At least it could fill it with the most permissive policy:
```
User-agent: *
Disallow: 
```
so we don't have to Google it. :)

**Comment by khalwat** [comment]
The reason it does this is *to* be user-friendly, so people are left with some kind of default that they can use.
