### ISSUE TITLE
Pass SEO image asset IDs to templates

### ISSUE THREAD

**Issue by benface** [khalwat/seomatic#259]
Sometimes the URLs of Facebook & Twitter images are not enough, and you need to know exactly which assets were selected in the CP. For instance if you want to transform them with Imager -- apparently Imager accepts URLs as well, but not in all cases (for instance when using Imgix with an S3 bucket, it generates a link that gives a 404). So it would be great if SEOmatic could pass the asset IDs to the templates. Thank you very much!

**Comment by khalwat** [comment]
The problem is that there will not always be an ID to pass down, so it's not something I want people to depend on.

Imager should be able to accept a URL, even when using Imgix... if not, I'd file an issue with Imager

**Comment by benface** [comment]
Hmm, but the SEOmatic image fields are always assets fields, no? What do you mean by "there will not always be an ID to pass down"? If no image is selected, of course there won't, but there won't be a URL either. I'm not quite sure what the difference is.

> Imager should be able to accept a URL, even when using Imgix...

Perhaps, but it's a bit strange to do:
Asset -> URL -> URL parsing/detection logic -> S3 path -> Imgix
when you can do:
Asset -> S3 path -> Imgix

See what I mean?
