### ISSUE TITLE
seomaticIdentity & seomatic don't exist

### ISSUE THREAD

**Issue by madebyshape** [khalwat/seomatic#26]
I'm running the latest version of SEOmatic and trying to render my own template, but on fields that you state should start with "seomatic" or "seomaticIdentity" it just outputs an error. Even if I do a conditional to check if something is in that particular field.

e.g. 

`<meta property="og:site_name" content="{{ seomatic.og.site_name }}">`

Just throws the error:

> Variable "seomatic" does not exist

I did change the "seomatic" bit to "seomaticMeta" and it worked for the Open Graph stuff, but then Twitter data messed up.

---

Also - The reason I'm rendering this template is because I don't want all the meta and options outputted in the default template. It would be good if we could turn features we wanted on and off within the plugin so we don't need to create bespoke templates. Just an idea!

**Comment by khalwat** [comment]
What exactly is it that you do not want to be outputted?  Except in very unusual circumstances, there shouldn't be a reason to use a custom template.

Anyway, if you want to do so, just make a copy of the `craft/plugins/seomatic/templates/_seo_meta.twig` template into your `craft/templates/` folder and change it as you see fit.

**Comment by madebyshape** [comment]
Things like Google Analytics and Humans.txt I don't want in there really, and a few other little tags because we manage these separately through other ways or just generally don't need them in there. (I'm a bit OCD with clean looking code!)

Will take a look at that template! Thanks for the amazingly quick response

**Comment by khalwat** [comment]
Only things that you fill in with values are displayed; if you do not want to use Google Analytics, then simply leave the field blank
