### ISSUE TITLE
Multilocale global SEOmatic data?

### ISSUE THREAD

**Issue by marionnewlevant** [khalwat/seomatic#263]
I have a multi-locale site with for instance different twitter handles for the different locales. Is there a way to enter this global SEOmatic data on a per-locale basis?

Is my best fall-back to put everything in a config file and pull it all in via twig?

Never mind. I am blind, and there the locale choice is in the right sidebar for Site Meta, Site Identity, Social Media, and Site Creator.

**Comment by khalwat** [comment]
Yep, you got it @marionnewlevant
