### ISSUE TITLE
Can set Google Analytics/GTM using Multi-Env Config?

### ISSUE THREAD

**Issue by luislavena** [khalwat/seomatic#264]
Hello

Thank you for making this plugin public!

Been trying to setup different GA and GTM codes between staging and production environments.

While implementing this in a project, noticed that is not possible to setup neither `GoogleAnalyticsUID` or `googleTagManagerID` inside `craft/config/seomatic.php` without success.

I've also tried prepend `owner` to the settings, all with same results.

Noticed that the value for these variables are stored in the database, so that value is not read from the configuration file.

But most likely I'm missing something, so any hint or pointer will be much appreciated.

Thank you in advance for your time and once again, thank you for releasing this plugin to the public.

❤️ ❤️ ❤️

**Comment by khalwat** [comment]
Unfortunately, no, SEOmatic doesn't currently support this. You can disable either in staging, with the following multi-environment `config.php` settings:

    "renderGoogleAnalyticsScript" => true,
    "renderGoogleTagManagerScript" => true,

Using a method very similar to here: https://nystudio107.com/blog/prevent-google-from-indexing-staging-sites

...but it doesn't support different values for environments, unfortunately.
