### ISSUE TITLE
Wrong alternative tags on custom localised route

### ISSUE THREAD

**Issue by kymar** [khalwat/seomatic#265]
On one of our consumer sites, lets call it `acme.com` we have three locales:
- en-gb
- en-au
- en-nz

And a pages thats lists out blog tags with the route:

````
'blog/tags/(?P<tag>[a-zA-Z\-\/]+)' => '_blogTags.twig'
````

Everything works fine with this route except the meta location tags are incorrect, so for example the homepage returns:

````html
<link rel="alternate" hreflang="x-default" href="https://acme.com/" />
<link rel="alternate" hreflang="en-gb" href="https://acme.com/" />
<link rel="alternate" hreflang="en-au" href="https://acme.com/au/" />
<link rel="alternate" hreflang="en-nz" href="https://acme.com/nz/" />
````
This is correct, however on the blog tags route the returned tags are:

````html
<link rel="alternate" hreflang="x-default" href="https://acme.com/au/blog/tags/easter" />
<link rel="alternate" hreflang="en-gb" href="https://acme.com/au/blog/tags/easter" />
<link rel="alternate" hreflang="en-au" href="https://acme.com/au/au/blog/tags/easter" />
<link rel="alternate" hreflang="en-nz" href="https://acme.com/nz/au/blog/tags/easter" />
````

So as you can see it prefixes the locale to the alternative urls twice which is incorrect.

**Comment by khalwat** [comment]
So I think this is likely happening because you've using a custom route that overrides the default behavior of what should be happening.

I'm not sure this is actually a bug in SEOmatic (though it might be), because it does render these tags properly when the default Craft behavior is used.

**Comment by khalwat** [comment]
Closing due to lack of additional information. I will re-open it if more information is added.

**Comment by scottwakefield** [comment]
Hey @khalwat,

I've just run into this issue, and your suspicion that it was happening because of custom routes appears to be correct!

I have two locales configured: `en` and `fr`. I'm running SEOmatic version `1.1.56`.

I'm seeing the same duplication of locale id in the urls on pages accessed via custom routes:

```
<link rel="canonical" href="http://website.test/fr/villas/seminyak" />
<link rel="alternate" href="http://website.test/fr/villas/seminyak" hreflang="x-default" />
<link rel="alternate" hreflang="en" href="http://website.test/fr/villas/seminyak" />
<link rel="alternate" hreflang="fr" href="http://website.test/fr/fr/villas/seminyak" />
```

My routes file includes:

```
return [
    'villas/(?P<locationSlug>[a-z0-9\-]{2,80})' => '_locations/entry',
];
```

Everything works as expected on urls that aren't via a custom route. 

Do you think anything can be updated within SEOmatic to mitigate this?

**Comment by scottwakefield** [comment]
It looks like this is the same as what's reported in https://github.com/nystudio107/seomatic/issues/302.
