### ISSUE TITLE
Meta tag causing W3 html validation error

### ISSUE THREAD

**Issue by matt-adigital** [khalwat/seomatic#266]
It seems that the W3 html validator reports an error because it wants the charset and the http-equiv to be set in separate meta tags. As this is an error and not a warning, generated by the {% hook 'seomatic' %} tag, could this be implemented please? Thanks!

<img width="1103" alt="screen shot 2017-08-02 at 11 26 06" src="https://user-images.githubusercontent.com/15085874/28869731-933ab862-7775-11e7-860b-e8fbc61f4fe8.png">

**Comment by khalwat** [comment]
So this is because you have an additional `<meta>` tag in your HTML that defines the charset; remove it, and all will be well.
