### ISSUE TITLE
Breadcrumbs on localized site not correct

### ISSUE THREAD

**Issue by xo-dev** [khalwat/seomatic#267]
The breadcrumbs from position 2 on have no language prefix (see example below), all other seomatic-rendered links seem to be OK.

"position": "1",
"item": {
"@id": "https://dev.mysite.com/de-de/",

"position": "2",
"item": {
"@id": "https://dev.mysite.com/produkte/produktwelt",

"position": "3",
"item": {
"@id": "https://dev.mysite.com/produkte/produktwelt/some-product",

**Comment by khalwat** [comment]
hmmmm, I will have a look at this. What _should_ it be in your case?

**Comment by xo-dev** [comment]
Position 1 is correct:
https://dev.mysite.com/de-de/

Position 2 has to be:
https://dev.mysite.com/de-de/produkte/produktwelt

Position 3 has to be:
https://dev.mysite.com/de-de/produkte/produktwelt/some-product

**Comment by khalwat** [comment]
I checked a fix into the `develop` branch; let me know how it works for you?

https://github.com/nystudio107/seomatic/tree/develop

**Comment by xo-dev** [comment]
Sorry, still the same behavior, language suffix after the domain is present for the homepage but on any other page (level) it’s missing.

**Comment by khalwat** [comment]
hmmmmm... that doesn't make sense. Can you clear your caches, and confirm the version number that SEOmatic is showing?

**Comment by xo-dev** [comment]
Caches cleared twice, browser cache cleared twice, Version Number 1.1.51.

Still the same problem.

**Comment by khalwat** [comment]
That's very strange. I'm asking for the elements in the language of the current request:

https://github.com/nystudio107/seomatic/blob/develop/services/SeomaticService.php#L1215

**Comment by xo-dev** [comment]
Yep, it is. Can’t see why the output ist missing the locale. Have checked it with other locales then the default one, but it’s missing there too.

And there is an other strange behavior. The "breadcrumbsHomeName" => 'Somename‘ is set in seomatic.php in the config dir, but the output is: Home, or whatever the name of the section for the homepage is set to. The config setting seems to be ignored.

Is there a way to disable the output of the breadcrumbs via a config setting? We can live without them, but not with wrong ones.

**Comment by khalwat** [comment]
I'm going to set up a test locally to see if I can reproduce what's going on here.

**Comment by xo-dev** [comment]
Hi,

have you found something in the meantime?

Thomas



Am 29.08.2017 um 16:55 schrieb khalwat <notifications@github.com>:

I'm going to set up a test locally to see if I can reproduce what's going on here.

**Comment by khalwat** [comment]
Not yet, but it's on the menu for tonight!

**Comment by khalwat** [comment]
So I tested his on a site that has English and Mexican Spanish, and it does appear to work properly:

```
    "breadcrumb": {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": "1",
                "item": {
                    "@id": "http://jesseyjoy.dev/",
                    "name": "Homepage" 
                } 
            },
            {
                "@type": "ListItem",
                "position": "2",
                "item": {
                    "@id": "http://jesseyjoy.dev/mx/contact",
                    "name": "Contactpage" 
                } 
            }
        ] 
    } 

```

In this case, the Contact page is localized (the home page is not). So you're going to have to tell me more about how you've set up the localized site.

Screenshots of how the URLs are set up for the sections, for example would be helpful. As would any of your other multi-locale setup config.

**Comment by xo-dev** [comment]
Hi Andrew,

thanks for testing. The sectionUrl’s are set up this way:


de_de   produkte/produktwelt/{slug}

de_at   produkte/produktwelt/{slug}

en_gb   products/product-world/{slug}

en_ie   products/product-world/{slug}

en_us   products/product-world/{slug}

es_es   productos/mundo-de-productos/{slug}

nl_be   producten/productaanbod/{slug}

nl_nl   producten/productaanbod/{slug}


In /craft/config/general.php we have the following block for the siteUrl’s:

'siteUrl' => array(
	        'de'    => 'https://dev.example.com/de-de/',
	        'de_at' => 'https://dev.example.com/at-de/',
	        'de_de' => 'https://dev.example.com/de-de/',
	        'en'    => 'https://dev.example.com/gb-en/',
	        'en_gb' => 'https://dev.example.com/gb-en/',
	        'en_ie' => 'https://dev.example.com/ie-en/',
	        'en_us' => 'https://dev.example.com/us-en/',
	        'es'    => 'https://dev.example.com/es-es/',
	        'es_es' => 'https://dev.example.com/es-es/',
	        'nl'    => 'https://dev.example.com/nl-nl/',
	        'nl_be' => 'https://dev.example.com/be-nl/',
		'nl_nl' => 'https://dev.example.com/nl-nl/'


Perhaps we can spin up a test server with a copy of the site and provide you the details for Craft login and ssh connect, if you would like to take a closer look at it.

**Comment by khalwat** [comment]
I think I understand the problem a bit better now @XOC-Th  . Can you try the build in the `develop` branch to see if it fixes it?

https://github.com/nystudio107/seomatic/tree/develop

If not, then yeah, having access to the site in some way would make it much easier to figure out.

**Comment by xo-dev** [comment]
Sorry, still the same. The locale appears for the 1st level breadcrumb (home) but not on any other page.

I’ll setup a copy the next days and send you the details.

**Comment by khalwat** [comment]
Yeah all I would need is some way to ssh in so I can debug and make changes. So some kind of a staging server.

**Comment by khalwat** [comment]
Thanks for your help with the dev setup for debugging. This version in the `develop` branch should fix your issues:

https://github.com/nystudio107/seomatic/tree/develop

**Comment by xo-dev** [comment]
I have to thank you for your great support.

Will try the new develop-build as soon as I can and report back.

**Comment by xo-dev** [comment]
Works like a charm.
