### ISSUE TITLE
Description not showing

### ISSUE THREAD

**Issue by optimized-zz** [khalwat/seomatic#268]
Hi,

I am really new to Craft and would really like some help. I read the closed ´'Not showing Meta description' thread but each time I try to add the code the website returns a 500 error.

I am attempting to change the _meta.html file in the template (not sure if this is correct). The code is 

<meta name="description" content="{% if descripcion is defined %}{{ descripcion }}{% else %}{{ seo.descripcion }}{% endif %}">

but wherever I put the code {% hook 'seomaticRender' %} I get the 500 error.

Could you tell me the correct code to use.

Many thanks,

Mike

**Comment by khalwat** [comment]
500 errors are server errors; my guess is something is misconfigured with your webserver.
