### ISSUE TITLE
1.1 Killed Google Analytics

### ISSUE THREAD

**Issue by theskyfloor** [khalwat/seomatic#27]
On sites where we already had GA tracking code the 1.1 update overrode the working tracking code with a blank one taking a clients analytics down for days before we realized it. Now we added the GA code into SEOmatic and tracking is back online - but the plug-in shouldn't output that snippet if its not filled in.

**Comment by khalwat** [comment]
It doesn't as of 1.1.1 (I fixed it in that version) -- sorry for the bug.
