### ISSUE TITLE
<title> isn't being localized

### ISSUE THREAD

**Issue by eheiser** [khalwat/seomatic#272]
I have a simple bi-lingual site with (I believe) everything configured right, except that the entry's title isn't being localized, it seems to be using whatever gets saved last.
Any idea? This is on a brandnew craft install, seomatic latest version.
Check http://dev.d-2.be/index.php/showroom-beurzen to see what I mean. Instead of "Showroom & beurzen" (NL) it's showing the french "Showroom & salons" (note: this is a temp url)

**Comment by khalwat** [comment]
Probably the SEOmatic FieldType wasn't set to be localizable?

**Comment by eheiser** [comment]
D'oh! Thanks!
