### ISSUE TITLE
How to merge new fields into json-ld

### ISSUE THREAD

**Issue by john-henry** [khalwat/seomatic#274]
We are using parse.ly analytics service and have been asked to add a few new fields to the @type: NewsArticle

```
"thumbnailUrl": "https://blog.parse.ly/inline_mra670hTvL1qz4rgp.png",
"articleSection": "Programming",
"creator": ["A. A. Milne", "John Kendall"],
```

Is there a way to merge these new fields back into the json or would they have to be added at a plugin level?

**Comment by khalwat** [comment]
Just so I can make sure I'm understanding the question, this is MainEntityOfPage information coming from an Entry that has an SEOmatic FieldType attached to it yes?

**Comment by john-henry** [comment]
@khalwat correct

**Comment by john-henry** [comment]
Using

```
{% set seomaticMainEntityOfPage = seomaticMainEntityOfPage | merge({
    headline: entry.seoHeadline ?: entry.title,
...
```
