### ISSUE TITLE
Add support for x-default hreflang

### ISSUE THREAD

**Issue by sjelfull** [khalwat/seomatic#277]
>The new x-default hreflang attribute value signals to our algorithms that this page doesn’t target any specific language or locale and is the default page when no other page is better suited. For example, it would be the page our algorithms try to show French-speaking searchers worldwide or English-speaking searchers on google.ca.

>The same annotation applies for homepages that dynamically alter their contents based on a user’s perceived geolocation or the Accept-Language headers. The x-default hreflang value signals to our algorithms that such a page doesn’t target a specific language or locale.

[Read more on Google's blog](https://webmasters.googleblog.com/2013/04/x-default-hreflang-for-international-pages.html)

**Comment by khalwat** [comment]
Added it in the build in `develop`:

https://github.com/nystudio107/seomatic/tree/develop
