### ISSUE TITLE
Template Meta not working even with correct template path

### ISSUE THREAD

**Issue by jchai002** [khalwat/seomatic#278]
The seomatic template meta feature does not work at all on my site

I made a template meta and set the correct template path to it
<img width="1023" alt="screen shot 2017-08-31 at 11 02 30 am" src="https://user-images.githubusercontent.com/11948171/29938022-35ed5fba-8e3c-11e7-885a-f9e634f01927.png">

Here is the corresponding section setting, as you can see, the template path is careers/_entry, just like the seomatic template meta template path
<img width="996" alt="screen shot 2017-08-31 at 10 58 40 am" src="https://user-images.githubusercontent.com/11948171/29938060-5a0816ce-8e3c-11e7-9fca-177b9111b1e9.png">

When I try to make a new entry inside the careerListing section, before I save it for the first time, the seo render shows this
<img width="982" alt="screen shot 2017-08-31 at 11 02 46 am" src="https://user-images.githubusercontent.com/11948171/29938093-75d7af0e-8e3c-11e7-836d-bd0abfb42c36.png">

After I hit save, it shows this
<img width="754" alt="screen shot 2017-08-31 at 11 01 25 am" src="https://user-images.githubusercontent.com/11948171/29938111-814c8a6c-8e3c-11e7-81d6-daaa0f74dce9.png">

Even though I added absolutely nothing to the seomatic tab in the entry settings.

Either way, the tempalte meta is not being used...am I missing something here?

**Comment by jchai002** [comment]
Also, I don't have any {% cache %} tags in the project, so nothing should be cached on the server

**Comment by khalwat** [comment]
So I'm a little confused... are you saying that you're using an SEOmatic FieldType in addition to a Template Meta?

**Comment by khalwat** [comment]
Will re-open if more info is added

**Comment by jchai002** [comment]
Oh I see.

Removing the seo meta field from the layout settings makes template overrides work properly.

Thanks for pointing that out!
