### ISSUE TITLE
Hebrew Locale Bug

### ISSUE THREAD

**Issue by matanlevkowich** [khalwat/seomatic#279]
I am using the Plugin and I have found one bug when using it with Hebrew language. 
I am using the SEOmatic field to target individual pages info. The SEO title filed content isn't being exported properly, instead of the Hebrew title the following is being  outputted: "..."

That being said, the site SEO title is being outputted properly but there is a limitation of only 6 characters for the title text.

I have attached several screen shots that demonstrate the issue.
Thank you,
Matan

![1](https://user-images.githubusercontent.com/12957213/29986817-5cfd0e14-8f65-11e7-809e-6496bd9add55.jpg)
![2](https://user-images.githubusercontent.com/12957213/29986816-5cfbcf54-8f65-11e7-9d4d-4dc4722ec781.jpg)
![3](https://user-images.githubusercontent.com/12957213/29986818-5cffff66-8f65-11e7-92ea-079ae67a7bfb.jpg)

**Comment by khalwat** [comment]
I think there's a similar issue with Chinese characters; the truncation algorithm gets confused. You can set the `truncateTitleTags` to `false` to prevent it from doing this truncation:

https://github.com/nystudio107/seomatic/blob/master/config.php
