### ISSUE TITLE
Dashboard SEO Site Meta tab creates error

### ISSUE THREAD

**Issue by E2design** [khalwat/seomatic#28]
Hi,

Installed SEOMatic 1.1.3 on Craft 2.5.2763 and getting the attached error while opening the SEO Site Meta tab from the Craft dashboard.
![schermafdruk 2016-02-19 08 23 10](https://cloud.githubusercontent.com/assets/5907530/13169017/86747e86-d6e2-11e5-8938-53bb43e46ccb.png)

**Comment by khalwat** [comment]
Right you are, that's an error.  I will fix it, apologies.

**Comment by khalwat** [comment]
This is fixed in SEOmatic 1.1.4:

https://github.com/nystudio107/seomatic

**Comment by E2design** [comment]
No it isn't getting e new error with the 1.1.4 fix.
See attached
![schermafdruk 2016-02-19 16 54 50](https://cloud.githubusercontent.com/assets/5907530/13180738/fb873852-d729-11e5-9750-863e75d52761.png)

**Comment by khalwat** [comment]
oops nevermind, fixing.

**Comment by khalwat** [comment]
Sorry about that, it was missing a period (!) :)

**Comment by khalwat** [comment]
Grab the latest build from here:

https://github.com/nystudio107/seomatic
