### ISSUE TITLE
[FR] Include 'availability' in 'Offer' in Product JSON-LD microdata 

### ISSUE THREAD

**Issue by hongc-cc** [khalwat/seomatic#281]
'availability' is an important data for Google rich image viewer, related items feature, rich snippet for google search result, google merchant center item verification and more.

missing this attribute will block Google Shopping Ad as well. I know we can custom-made our own JSON-LD microdata, but 'availability' should be auto included in the default Product JSON-LD

// from google // 
ItemAvailability, required for Related Items feature in Image Search, recommended for Search

// from google merchant center //
Price or availability mismatches were found throughout your product data and landing pages.  You received an email asking you to update that prices or availability in your product data so that they’re consistent with your landing page by a certain date. After that date, we still found mismatching prices or availability.
Your landing pages haven’t been crawled recently. Your products will be approved once your landing pages are crawled and our systems confirmed that price or availability matches your product data. Until then, we have preemptively disapproved these items to ensure users see consistent price and availability information.

**Comment by khalwat** [comment]
What do you think I should default the value of the `availability` key to?

**Comment by khalwat** [comment]
I added this to the build in `develop` @idolab 

https://github.com/nystudio107/seomatic/tree/develop

It defaults to "InStock" -- not sure if there is a Commerce-ish way to determine the availability?

**Comment by khalwat** [comment]
Never mind, we figure it out by asking Commerce now:

```
                                            if ($variant->getIsAvailable()) {
                                                $availability = "http://schema.org/InStock";
                                            } else {
                                                $availability = "http://schema.org/OutOfStock";
                                            }
```
