### ISSUE TITLE
Template Meta not working (specifically robots meta)

### ISSUE THREAD

**Issue by SherriAlexander** [khalwat/seomatic#282]
Using the latest version of SEOMatic, I've got a site where I need to block off an entire section from being indexed via `<meta name="robots" content="none" />` (an index page single, and a channel with many many pages).  Rather than having to configure each page individually, I'm trying to do it with an SEOMatic Template Meta.

Starting with the index page single, I pointed it at the correct Craft template location (checked and double-checked), and set the robots pulldown to none.  However, if I preview the meta info on that screen, it shows `<meta name="robots" content="all" />`.  After saving and viewing the source of the page, it also uses `<meta name="robots" content="all" />`.

No caching is in place, so that's not the culprit.  

Not sure if it's relevant, but this is a situation where the actual URL on the front-end is different from the template folder naming (rough example, URL in browser is `/foo`, but the Craft template is `/bar/_index.html`).  In SEOMatic, I'm putting in the path to the template, not the route.

Thoughts?  Unfortunately this is something the client wants to have fixed today, and the thought of adding the field to maybe a hundred existing pages (instead of just 2 templates!) is pretty daunting... :-/  Thanks in advance for your time!

**Comment by SherriAlexander** [comment]
Actually, I think the time pressure is off -- as a temporary patch fix, I just hardcoded an extra robots meta tag directly in the templates (from what I'm reading, if you have two robots tags, the more restrictive one should be honored).  Still curious why it's misbehaving though.  :)

**Comment by khalwat** [comment]
Is there an SEOmatic Meta field in the section? If so, it will override the template meta settings.

Another way you could also do this is via Twig, by adding something like this to the templates:

```
{% set seomaticMeta = seomaticMeta | merge({'robots': 'none' }) %}
```

**Comment by SherriAlexander** [comment]
I'd actually put an SEOmatic meta field in there originally, then removed it to go the template meta route instead.  Is there any chance that inserting the field and then removing it would still register with SEOmatic somehow?

I'll probably do the merge solution anyway, but figured I'd throw it out there in case anyone else was having similar problems.  :)  Thanks!
