### ISSUE TITLE
Unclear definition ”Automatically send Google Analytics PageView”

### ISSUE THREAD

**Issue by tsawitzki** [khalwat/seomatic#283]
Hello and a massive **thank you** for this plugin, first of all!

I have a problem understanding the definition of the _Automatically send Google Analytics PageView_ function, as the wiki here just repeats what the explanation in the backend already says.

Is the page view actually created anytime there is a server request to a specific site and Craft renders the page, independently of any analytics code in the frontend?

I am especially asking since all navigation links in my project fire Ajax requests to fetch the associated content – thus I will have to send a "link clicked" information to my GA script to count pageviews beyond the user’s entry page. In case your plugin does this anyway since there is a CMS request to each page involved and Seomatic catches/listens to that, I would not have to implement any extra code to communicate with the GA script …

Looking forward to a more detailed explanation of what happens with this function.

**Comment by khalwat** [comment]
So this is what the code looks like, hopefully this helps:

```
{% if seomaticHelper.ownerGoogleAnalyticsUID %}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '{{ seomaticHelper.ownerGoogleAnalyticsUID |raw }}', 'auto'{% if seomaticHelper.googleAnalyticsLinker %}, {allowLinker: true}{% endif %});
{% if seomaticHelper.googleAnalyticsAnonymizeIp %}
  ga('set', 'anonymizeIp', true);
{% endif %}
{% if seomaticHelper.googleAnalyticsAdvertising %}
  ga('require', 'displayfeatures');
{% endif %}
{% if seomaticHelper.googleAnalyticsEcommerce %}
  ga('require', 'ecommerce');
{% endif %}
{% if seomaticHelper.googleAnalyticsEEcommerce %}
  ga('require', 'ec');
{% endif %}
{% if seomaticHelper.googleAnalyticsLinkAttribution %}
  ga('require', 'linkid');
{% endif %}
{% if seomaticHelper.googleAnalyticsLinker %}
  ga('require', 'linker');
{% endif %}
{% if seomaticHelper.googleAnalyticsSendPageview %}
  ga('send', 'pageview');
{% endif %}
</script>
{% endif %}
```
