### ISSUE TITLE
Render hook does not display meta tags using facebook share debugger

### ISSUE THREAD

**Issue by dotcollective-brendon** [khalwat/seomatic#284]
{% hook 'seomaticRender' %} seems to only output JSON data when request by Facebook share debugger.

Source:
https://developers.facebook.com/tools/debug/echo/?q=http%3A%2F%2Fstage.sneakerfreaker.com%2Fsneakers%2Fnike-air-max-zero-collection%2F

Tool:
https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fstage.sneakerfreaker.com%2Fsneakers%2Fnike-air-max-zero-collection%2F

**Comment by khalwat** [comment]
Looks like there may be a Facebook Open Graph scraper parsing issue with minified HTML; likely a regression https://developers.facebook.com/bugs/2025528171065799/

I don't think there is anything wrong with the tags output from SEOmatic; I don't think there is anything wrong with the way that Minify minifies the HTML.

I think this is likely a regression on Facebook's end; the same output that used to work, no longer does, and other services like Slack, Pinterest, etc. that scrape `og:` tags continue to work.

Recommendation: give them a few days to look into it; if you _must_ have this fixed immediately, uninstalling the Minify plugin should do the trick.

**Comment by khalwat** [comment]
I do notice that you have duplicate meta charset tags though:

```
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Home - Sneaker Freaker</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```

You should have only one; SEOmatic outputs it for you, so you can eliminate the charset & http-equiv tags you're putting above `{% hook 'seomaticRender' %}`

**Comment by mauriciodulce** [comment]
same problem

**Comment by khalwat** [comment]
Same solution @mauriciodulce

**Comment by khalwat** [comment]
I can verify that Facebook has fixed this bug. You can now re-install the `Minify` plugin happily:

![safariscreensnapz534](https://user-images.githubusercontent.com/7570798/30670737-81ce5948-9e31-11e7-9c23-861ff39ccb7d.png)

**Comment by dotcollective-brendon** [comment]
Thanks @khalwat - confirming that everything is working as expected now.
