### ISSUE TITLE
Allow separate SEO description and OG:description

### ISSUE THREAD

**Issue by jasonlav** [khalwat/seomatic#285]
It appears that the SEOMatic does not allow separate values to be defined in the control panel for the SEO Description and OG:Description. In some cases it would be very useful to be able to define these fields seperately.

**Comment by khalwat** [comment]
You can do this via Twig: https://github.com/nystudio107/seomatic/wiki/10.-Dynamic-Twig-SEO-Meta

It probably won't be done via the backend GUI for Craft 2.x
