### ISSUE TITLE
Every time I update seomatic plugin, I always get a fatal error

### ISSUE THREAD

**Issue by epcliff** [khalwat/seomatic#287]
Hi, 

Whenever I update the seomatic plugin, I get the following fatal error:

Fatal error: Cannot declare class ComposerAutoloaderInit5b938720cfef7b7256946290ccab109b, because the name is already in use in /path/to/mysite/craft/plugins/seomatic/vendor/composer/autoload_real.php on line 5

When I update, I remove the entire seomatic folder from plugins folder and add the updated seomatic folder. I don't have any problems with other Craft plugins.

Any ideas on why this error comes up? Do you have any suggestions on what to do?

**Comment by khalwat** [comment]
I'm not sure what could be causing this, but it isn't a general error with SEOmatic; somewhere on your setup there's a duplicate copy of SEOmatic or some other plugin that's causing a namespace collision with that class.

It's also potentially possible that there's some kind of caching issue involved here; are you using OPCache? I just searched the entire SEOmatic source tree, and there's only one instance of that class being declared:

![phpstormscreensnapz017](https://user-images.githubusercontent.com/7570798/30878005-8ddeb7b8-a2c9-11e7-84f3-2994f026f83c.png)

**Comment by michaelrog** [comment]
@epcliff Try searching your whole project for instances of that class name. (It's possible — although astoundingly unlikely — that some other composer autoloader ended up with that same class name. More likely, you have a duplicate/old copy of SEOmatic hanging around somewhere.)

**Comment by khalwat** [comment]
That's my conclusion as well @michaelrog -- thx.
