### ISSUE TITLE
meta tag 

### ISSUE THREAD

**Issue by pixeldeluxe** [khalwat/seomatic#289]
A document must not include both a meta element with an http-equiv attribute whose value is content-type, and a meta element with a charset attribute.

`<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`

It should be:

`<meta http-equiv="Content-Type" content="text/html" />`
`<meta charset="utf-8">`

**Comment by khalwat** [comment]
No... this is valid:

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```

The problem is you probably have an additional `<meta charset="utf-8">` somewhere else. Remove it, and all will be well.

**Comment by pixeldeluxe** [comment]
Hi, 

Sorry. There was a doubling indeed. 
Keep up the good work.

grtz, Martijn


	 	
Martijn La Feber UI/UX designer
PixelDeluxe Interaction Design
T 010 - 413 10 53
E martijn@pixeldeluxe.nl <mailto: martijn@pixeldeluxe.nl>
Boomgaardsstraat 166
3012 XE Rotterdam

website <http://www.pixeldeluxe.nl/> | linkedin <https://www.linkedin.com/company/pixeldeluxe-interaction-design> | facebook <https://www.facebook.com/PixelDeluxe> | twitter <https://www.twitter.com/pixeldeluxe>
