### ISSUE TITLE
Modified seomaticMeta in templates not available in custom template

### ISSUE THREAD

**Issue by apolakipso** [khalwat/seomatic#29]
When using a custom template, it only ever gets the initial `seomaticMeta` values, changes made in templates are not applied.

I have this in my layout:

```
{% set seomaticTemplatePath = '_seo/index' %}
{% hook 'seomaticRender' %}
```

`_seo/index.twig` is based on `plugins/seomatic/templates/_seo_meta.twig`.

I can modify `seomaticMeta` in templates extending my layout, and even though the value of `seomaticMeta` within the layout template changes accordingly (as is expected), the value of `seomaticMeta` in the template `_seo/index.twig` is always set to the initial state (as prefilled by the plugin).

[`services/SeoMaticService.php@62`](https://github.com/nystudio107/seomatic/blob/master/services/SeomaticService.php#L62)

```
     public function render($templatePath="", $metaVars=null, $isPreview=false)
     {

         if ($templatePath)
             {
-            $htmlText = craft()->templates->render($templatePath);
+            $htmlText = craft()->templates->render($templatePath, $metaVars);
             }
         else
             {

```

To fix this, I passed in `$metaVars` to the render method as well - it works, but I'm unsure whether this is the right move.

NB: It's completely possible that I have misunderstood how templates are supposed to be used.

**Comment by khalwat** [comment]
You're correct; I rolled this fix into 1.1.4:

https://github.com/nystudio107/seomatic
