### ISSUE TITLE
Regression in version 1.1.53 with breadcrumbs when the first letter in the slug matches the last letter in the tld

### ISSUE THREAD

**Issue by eriweb** [khalwat/seomatic#291]
I've not narrowed it down to exactly what piece of the code does this (might be replaceOverlap), but when the first letter of the slug matches the last letter of the tld, a slash and one instance of the letter is removed.

Example:

siteUrl: http://foobar.dev
slug/entry: /very-nice-plugin
url to entry: http://foobar.dev/very-nice-plugin

In this instance, the url for the entry instance in seomaticMeta.breadcrumbs becomes: http://foobar.devery-nice-plugin

we've reproduced this with several tlds, ie. http://foobar.no/oh-crap becomes http://foobar.noh-crap

**Comment by khalwat** [comment]
Well, that's not good. And yes, it's very likely to be the `replaceOverlap()` method.

**Comment by khalwat** [comment]
Alright, give the build in the `develop` branch a whirl:

https://github.com/nystudio107/seomatic/tree/develop

**Comment by eriweb** [comment]
Seems to work, I can no longer reproduce the bug when using `develop`
