### ISSUE TITLE
Seomatic_MetaFieldType error

### ISSUE THREAD

**Issue by ncc-jwood** [khalwat/seomatic#292]
Yesturday I updated Craft and this plugin in a project (latest versions), and I'm getting the following error: `Call to a member function first() on null ` in `craft/plugins/seomatic/fieldtypes/Seomatic_MetaFieldType.php(184)`

```
181                 case "FocusPoint_FocusPoint":
182                 case "Assets":
183                     $imageFieldList[$field->handle] = $field->name;
184                     $img = $this->element[$field->handle]->first(); // << here
185                     if ($img)
186                         {
187                             $fieldImage[$field->handle] = $img->url;
188                         }
189                     break;
```

This is in the entries editing page, which was working before the update.  Do you have any suggestions on fixes?

**Comment by khalwat** [comment]
So it looks like you have it set to pull from a field that no longer exists. Is it possible that a field was deleted?

**Comment by khalwat** [comment]
I added some paranoid checking into the FieldType; try out this build from the `develop` branch:

https://github.com/nystudio107/seomatic/tree/develop

**Comment by ncc-jwood** [comment]
@khalwat That's very possible, this is a project that I've only just inherited and I'm still figuring out what the last dev was doing.  

Your dev branch update fixes the problem for me, thank you.
