### ISSUE TITLE
SEO Description not pulling the field source

### ISSUE THREAD

**Issue by emir-plicanic-14243** [khalwat/seomatic#294]
After the most recent update the SEO Description "Source" drop-down is not showing custom post fields when you select "From Field" option.

It only shows "Title" field as an option.

**Comment by zackspear** [comment]
In addition to SEO Description, it seems that most items are no longer working when choosing _From Field_. As mentioned above, only _Title_ is showing up for any of them. 

For the SEO image fields there are no available asset fields to choose from.

Downgrading to the previous release for now.

**Comment by steveooo9** [comment]
We also have a bug where a change on meta description per page (via SEO field) result in changing every other pages' descriptions...

**Comment by khalwat** [comment]
This is a regression that happened when fixing another issue. This is fixed in version 1.1.56:

https://github.com/nystudio107/seomatic/releases/tag/1.1.56
