### ISSUE TITLE
In entries No Image set from SEOmatic field

### ISSUE THREAD

**Issue by pixeldeluxe** [khalwat/seomatic#295]
Hi,
First of all, great plugin. Thanks very much.
If I set an image field as default in the seomatic field it cannot be selected in an new or existing entry.

<img width="544" alt="screen shot 2017-11-08 at 09 13 13" src="https://user-images.githubusercontent.com/524849/32538973-427172a0-c468-11e7-9c3c-37b609b5dfe5.png">

**Comment by khalwat** [comment]
This is a regression that happened when fixing another issue. This is fixed in version 1.1.56:

https://github.com/nystudio107/seomatic/releases/tag/1.1.56
