### ISSUE TITLE
Question about migrating entries with SEOMatic field

### ISSUE THREAD

**Issue by bryantAXS** [khalwat/seomatic#296]
I'm attempting to move various entries, each which are Singles and share the same fields, into new a Structure. I'm using a slightly modified version of this script [here](https://craftcms.stackexchange.com/questions/4433/move-entry-from-one-structure-to-another-with-parenting/4467#4467).

Everything is working except I lose associated SEOMatic entry data. Any thoughts on how to complete the migration and preserve that entry data?

**Comment by khalwat** [comment]
I've never used that script, but looking at it, you'd have to write a custom handler for the SEOmatic Field.
