### ISSUE TITLE
SEO Title is not dynamic

### ISSUE THREAD

**Issue by SOLiNARY** [khalwat/seomatic#297]
I have 3 locales active on site.
Whichever locale is saved last, page title is from that specific language for ALL locales.
So if I edit english version & save it, all versions of site will have english page title.

In DB in table **craft_content** there is jsonified column called "**field_seo**" which is overriden whenever u save entry in ANY language. last language's title overrides property "**seoTitle**" in this jsonified column for ALL locales.

**Comment by khalwat** [comment]
This is likely because you have not set the SEOmatic Field to be localizable.
