### ISSUE TITLE
Make SEO field collapsable

### ISSUE THREAD

**Issue by steveooo9** [khalwat/seomatic#298]
A feature request:  
Make the SEO field collapsable, maybe per default or having an option to set the default behavior.

<img width="653" alt="collapse" src="https://user-images.githubusercontent.com/27959355/33074402-5a90ee66-cec6-11e7-93e9-a15cfe77adf6.png">

This would be good, because it takes a lot of vertical space and on live preview, it gives a better overview when this huge field is collapsed.

@khalwat What do you think?

**Comment by khalwat** [comment]
So what I usually do is just put it on a separate "Meta" tab, which essentially accomplishes the same thing.

I am redesigning this somewhat for the Craft 3 version, though.

**Comment by steveooo9** [comment]
@khalwat Well, I also have this on a separate Meta tab, but on live preview, the tabs still break underneath each other because of the limited horizontal space...
