### ISSUE TITLE
truncateStringOnWord() stumbling on a colon

### ISSUE THREAD

**Issue by tomkiss** [khalwat/seomatic#299]
Hoping this isn't just me, but when I run truncateStringOnWord(1000) on the following string (which has been extracted from a matrix field):

> In addition to reduced fuel costs, as low as 2p per mile, there are a number of ways to receive financial support in the switch to electric and low-emission vehicles: Support from the Government: Plug-in car, van and motorcycle grants, offering:35% of the cost of a car, up to a maximum of either £2,500 or £4,500 depending on the model.20% of the cost of a van, up to a maximum of £8,000.20% of the cost of a motorcycle, up to a maximum of £1,500.

I get:

> In addition to reduced fuel costs, as low as 2p per mile, there are a number of ways to receive financial support in the switch to electric and low-emission vehicles:…

**Comment by khalwat** [comment]
If you remove the colon, does it then truncate on the next colon?
