### ISSUE TITLE
og:url are missing base url

### ISSUE THREAD

**Issue by tomfrew** [khalwat/seomatic#30]
On two of my sites the output of og:url is "/page" rather than "http://domain.com/page"

The meta tag previews on both a site and entry level both show the correct og:url with base url but somehow are getting over ridden by the time they are output.

My current fix is to update the _seo_meta.twig template so that line 62 reads:
`{% if key == 'url' %}
<meta property="og:{{ key }}" content="{{craft.request.url}}" />
{% else %}
<meta property="og:{{ key }}" content="{{ value }}" />
{% endif %}`

Do you know what might be causes this override?

**Comment by khalwat** [comment]
My guess would be that something isn't set up right; SEOmatic actually uses `craft.request.url` by default.

Are you using any SEOmatic Fieldtypes?

**Comment by tomfrew** [comment]
`{{craft.request.url}}` outputs the full domain url for me.

I do have the field types setup on all entries. There doesn't seem to be any url overrides on the field types though are there?

**Comment by khalwat** [comment]
I need more information to diagnose this for you. What pages does the full URL not appear?  On your home page with not FieldTypes involved, you should be seeing the full URL

**Comment by khalwat** [comment]
Try grabbing the build from the `develop` branch here:

https://github.com/nystudio107/seomatic/tree/develop

It should fix it for you.

**Comment by khalwat** [comment]
This is fixed in 1.1.5:

https://github.com/nystudio107/seomatic

**Comment by tomfrew** [comment]
Thanks @khalwat!
