### ISSUE TITLE
Canonical url incorrect

### ISSUE THREAD

**Issue by DanielleDeman** [khalwat/seomatic#300]
For pages with a locale the canonical url is incorrect. The locale part of the url is duplicated. Instead of blabla.com/de/blabla you get blabla.com/de/de/blabla. 
It seems in $meta['canonicalUrl'] =  $this->getFullyQualifiedUrl($entryMetaUrl); $entryMetaUrl is incorrect

**Comment by khalwat** [comment]
What version of SEOmatic are you using? This should have been fixed in a recent update.
