### ISSUE TITLE
Canonical Next and Prev links

### ISSUE THREAD

**Issue by terryupton** [khalwat/seomatic#303]
Not sure if this should or could be part of SEOmatic or if this is best reserved to be handled separately? However, it would be nice to add Canoncial links for the next and previous pages if the current page is part of a pagination (say a portfolio, news or blog).

Typically the URLS would look like this (on page 2);
<link rel="prev" href="http://www.domain.co.uk/news/1/">
<link rel="next" href="http://www.domain.co.uk/news/3/">

There would need to be some checking if first or last page to omit the next and previous respectively.

Heres some further information
https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html

**Comment by khalwat** [comment]
This probably should be handled outside of SEOmatic, because it's tough for it to know the context.

**Comment by terryupton** [comment]
Would there be a way to merge this in with the other SEOmatic meta data or just to append it to after the SEOmatic hooks have been applied in the template?
