### ISSUE TITLE
Authorship is dead

### ISSUE THREAD

**Issue by RitterKnightCreative** [khalwat/seomatic#305]
SEOMatic points to [this](https://www.woorank.com/en/blog/how-to-implement-rel-publisher-tag) 3+ year old article about authorship which is basically [dead](https://support.google.com/webmasters/answer/6083347?hl=en) as Google suggests using structured data instead. 

Suggest removing the check; SEOMatic already spits out JSON-LD so nothing to add. ;)

**Comment by khalwat** [comment]
Good idea, thanks!
