### ISSUE TITLE
Enhancement: CraftQL Integration for Craft 3

### ISSUE THREAD

**Issue by edolyne** [khalwat/seomatic#306]
I'd love to propose an integration for the Craft 3 version of Seomatic, to include support for [CraftQL](https://github.com/markhuot/craftql).

This would make the SEO fields available through a GraphQL endpoint for those of us working on single page JS projects whose content is powered by Craft and use GrahpQL to consume the content.

Here's an example from another field type that added support [Simple Map](https://github.com/ethercreative/simplemap/issues/60)

**Comment by khalwat** [comment]
SEOmatic for Craft 3 supports returning all of the meta data to you via AJAX as an array of tags, or an array of arrays:

https://twitter.com/nystudio107/status/856751885939879936

(or rather it will, once it is released)
