### ISSUE TITLE
Image not merging with SEO data

### ISSUE THREAD

**Issue by nathanielperales** [khalwat/seomatic#307]
I have a pretty specific set up: posts get created via rss feeds and images are not attached to the specific posts, so instead in the entry template I use an image from a related entry. When I try to use the related entry's image as the SEO image and merge it with SEOmatic, it does not merge.

Is this something that SEOmatic supports? This is the code I'm using:

```
{% if craft.entries.section('episode') %}
   {% set relatedPodcastImage = craft.entries.section('podcastChannel').relatedTo(entry).albumCoverPicture.first().getUrl('large') %}
      {% set seomaticMeta = seomaticMeta | merge(
            { og:
                  {
                  title: entry.title,
		  description: entry.podcastDescription,
                  image: relatedPodcastImage
                  }
            },
	    { twitter:
                  {
                  title: entry.title,
                  description: entry.podcastDescription,
                  image: relatedPodcastImage
                  }
            }
      ) %}
{% endif %}
```

**Comment by khalwat** [comment]
I'd suggest having `devMode` on and outputting `{{ dump(seomaticMeta) }}` to make sure that things are actually being changes the way they should be.

This type of functionality definitely works in SEOmatic, I've done it on a number of sites.
