### ISSUE TITLE
gtag.js support

### ISSUE THREAD

**Issue by jonXmack** [khalwat/seomatic#308]
I was wondering if you had plans to add support for [gtag.js](https://developers.google.com/analytics/devguides/collection/gtagjs/) in the future. We have a client who is using it rather than analytics.js, and it would be great to be able to keep the GA ID in SEOmatic rather than having to set it in the global config.

**Comment by khalwat** [comment]
SEOmatic does support Google Tag Manager, which I believe does what you want?

**Comment by jonXmack** [comment]
We're using gtag.js with a UA-XXXXXX-XX ID, whereas the description of the Google Tag Manager ID field asks for a GTM-XXXXXX ID. Using the Google Tag Manager ID field adds the gtm.js code, but the gtag.js code is different, and allows us to set up events on the page itself using onclick events in a similar way to how you'd do it using analytics.js which can then be tracked in GA as you normally would, as opposed to setting up events in Tag Manager and using Tag Manager to track it. 

https://developers.google.com/gtagjs/
https://support.google.com/tagmanager/answer/7582054

**Comment by khalwat** [comment]
Ah, I see. I have not used `gtag.js` yet. It does look nifty

**Comment by khalwat** [comment]
I've added it to SEOmatic for Craft 3:

<img width="1368" alt="google chromescreensnapz078" src="https://user-images.githubusercontent.com/7570798/37238386-3bb4fc8a-23f3-11e8-8fe1-abad6960b2db.png">

https://www.lunametrics.com/blog/2017/12/12/what-is-gtag-google-analytics/
