### ISSUE TITLE
Pinterest Author Meta

### ISSUE THREAD

**Issue by jonlongnecker** [khalwat/seomatic#309]
Pinterest is showing my company's name (since I entered it in as the "creator" of the website in SEOmatic) as the author of individual articles that are being pinned. I'm not sure the best way to fix this? It needs a tag like this: 

`<meta property="article:author" content="Jon Longnecker" />`

I know I can put this in manually, but it would make sense if it were included by default.

**Comment by jonlongnecker** [comment]
Ah, I also see that the Facebook OpenGraph tags are putting a link to the FB page as the article author. Is this causing a conflict?

`<meta property="article:author" content="https://www.facebook.com/whatever" />`

**Comment by khalwat** [comment]
No, I think it's likely grabbing the information from the `mainEntityOfPage` JSON-LD.

That's the only place that the Creator information is used.
