### ISSUE TITLE
Receiving 500 response error when attempting to upload images

### ISSUE THREAD

**Issue by zackspear** [khalwat/seomatic#31]
So far I'm absolutely loving this plugin. I didn't even know about a lot the things it includes which is awesome.

Unfortunately I'm unable to upload images to the SEO Image field anywhere, including the default SEO Site Meta and in entries that require a custom image. This occurs on both my local vagrant environment and on my dev server.

**In the console I'm receiving this**
![screenshot 2016-02-25 08 36 52](https://cloud.githubusercontent.com/assets/2531682/13327096/5a64c1ec-db9d-11e5-8543-30e0d71b132a.png)

**And in the network tab of the dev tools I checked out the XHR response**

```
PHP Error [500]

Argument 1 passed to Craft\FieldsService::populateFieldType() must be an instance of Craft\FieldModel, null given, called in /var/www/cosmic.dev/core/app/controllers/AssetsController.php on line 93 and defined (/var/www/cosmic.dev/core/app/services/FieldsService.php:1045)

#0 /var/www/cosmic.dev/core/app/etc/errors/ErrorHandler.php(184): Craft\ErrorHandler->handleError()
#1 /var/www/cosmic.dev/core/app/framework/base/CErrorHandler.php(133): Craft\ErrorHandler->handleError()
#2 /var/www/cosmic.dev/core/app/framework/base/CApplication.php(824): Craft\ErrorHandler->handle()
#3 /var/www/cosmic.dev/core/app/etc/web/WebApp.php(685): Craft\WebApp->handleError()
#4 /var/www/cosmic.dev/core/app/services/FieldsService.php(1045): Craft\WebApp->handleError()
#5 /var/www/cosmic.dev/core/app/controllers/AssetsController.php(93): Craft\FieldsService->populateFieldType()
#6 /var/www/cosmic.dev/core/app/framework/web/actions/CInlineAction.php(49): Craft\AssetsController->actionExpressUpload()
#7 /var/www/cosmic.dev/core/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#8 /var/www/cosmic.dev/core/app/framework/web/CController.php(286): Craft\AssetsController->runAction()
#9 /var/www/cosmic.dev/core/app/framework/web/CController.php(265): Craft\AssetsController->runActionWithFilters()
#10 /var/www/cosmic.dev/core/app/framework/web/CWebApplication.php(282): Craft\AssetsController->run()
#11 /var/www/cosmic.dev/core/app/etc/web/WebApp.php(815): Craft\WebApp->runController()
#12 /var/www/cosmic.dev/core/app/etc/web/WebApp.php(285): Craft\WebApp->_processActionRequest()
#13 /var/www/cosmic.dev/core/app/framework/base/CApplication.php(184): Craft\WebApp->processRequest()
#14 /var/www/cosmic.dev/core/app/index.php(62): Craft\WebApp->run()
#15 /var/www/cosmic.dev/www/index.php(23): require_once()
```

A few things about my Craft setup that might be helpful.
- Instead of a `craft` directory we have a `core` directory that has the `app` and `storage` directories while `templates`, `plugins`, and `config` are one level up in the root directory of the project. This helps with not having to track the Craft app in Git.
- I'm using an S3 bucket for all my asset uploads
- You may see in the screenshot `mission-control`. This is the `cpTrigger` to access the CMS instead of `admin`

Another dev on the team I work with is using the exact same setup without any issues. So any help would be awesome.

 Thanks in advance.

**Comment by khalwat** [comment]
That's pretty strange.  What if you use a local asset source?

**Comment by zackspear** [comment]
Okay, so in the process of adding and testing with a local asset source I've narrowed down as to when the 500 error actually occurs.

So I'm able to click the `+ Select SEO Image` field button that opens the asset picker/upload modal and choose & upload new images to both S3 and local asset sources.

The error occurs when I try to drag and drop upload to that `+ Select SEO Image` asset field.

**Comment by khalwat** [comment]
...and this doesn't happen for any other asset fields you have?

From what you're describing, it almost sounds like it may be some kind of Craft issue.

**Comment by zackspear** [comment]
Initially thought the same thing about it potentially being a Craft issue. But it does not happen when I drag and drop to other asset fields.

**Comment by khalwat** [comment]
Very odd, because I don't see anything related to my plugin in the stack crawl.  I will try testing locally in a bit.

**Comment by khalwat** [comment]
Got this from Brad @ P&T:

```
bradbell [2:56 PM] 
@khalwat: weird. that error indicates that either `$fieldId` doesn’t exist in POST `$fieldId = craft()->request->getPost('fieldId');` or id does, but the field doesn’t exist `craft()->fields->getFieldById($fieldId)`
```

**Comment by khalwat** [comment]
I'm unable to replicate this.  Closing it; feel free to re-open it if you have additional information.
