### ISSUE TITLE
Not populating fields with existing info after plugin update 

### ISSUE THREAD

**Issue by drball** [khalwat/seomatic#310]
Just had an issue after updating this on a site with existing pages of content. 
The fields aren't pre-populated with the existing title and description, so saving the page loses the data. 
On the frontend, the pages do show the correct title and description, but not after saving.
This has caused us big problems because the only solution I've found is to copy the title and description from the public version of the page into the editor, for every page!

**Comment by devkokov** [comment]
I have traced this down to these being blank or non-existent in the database:

"seoTitleUnparsed":"","seoDescriptionUnparsed":"","seoKeywordsUnparsed":""

Potential fix for this would be to pre-populate them from the parsed values as part of the update script.

**Comment by devkokov** [comment]
Here's a little PHP script that fixed the issue for me.

AS USUAL, take a backup of your database before trusting random people on the internet.

```
<?php

// CONFIG START

$db_host    = "localhost";
$db_user    = "db_user";
$db_pass    = "db_pass";
$db_name    = "db_name";
$table_name = "craft_content"; // Name of Craft's content table
$field      = "field_seo"; // Name of column where SEOMatic stores its data in the craft_content table

// CONFIG END


$conn = new mysqli($db_host, $db_user, $db_pass, $db_name);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$sql = "SELECT id, $field FROM $table_name WHERE $field IS NOT NULL AND $field <> ''";
$result = $conn->query($sql);

if ($result->num_rows == 0) {
    echo "Nothing to update";
    exit;
}

$i = 0;

while($row = $result->fetch_assoc()) {
    $data_new = $data_old = json_decode($row[$field], true);
    foreach (["seoTitle", "seoDescription", "seoKeywords"] as $key) {
        if (empty($data_new[$key . "Unparsed"])) {
            $data_new[$key . "Unparsed"] = $data_new[$key];
        }
    }

    if ($data_new != $data_old) {
        $stmt = $conn->prepare("UPDATE $table_name SET $field = ? WHERE id = ?");
        $stmt->bind_param("si", $json, $id);
        $json = json_encode($data_new);
        $id = $row["id"];
        $stmt->execute();
        $stmt->close();
        $i++;
    }
}

echo "Updated $i entries";

$conn->close();
```

**Comment by khalwat** [comment]
You just need to re-save the Section as per: 

https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

```
If you add an SEOmatic FieldType to an existing Section that already has entries in it, you'll need to re-save the Section to populate the newly added SEOmatic FieldType with data. You can do this via Settings → Edit My Section → hit Save.
```
