### ISSUE TITLE
How to update seoMatic fields from custom plugin?

### ISSUE THREAD

**Issue by tvansteelandt** [khalwat/seomatic#312]
Is it possible to update specific seomatic fields from inside a custom plugin?
I tried this:

$entry->getContent()->setAttributes(array(
	'seo'				=> array(
		'seoTitle' => "TEST"
	)
));
			
craft()->elements->saveElement($entry);

But doesn't work.

**Comment by khalwat** [comment]
You should be able to change any of the settings just as you would for any field; check out the way it works under the hood here:

https://github.com/nystudio107/seomatic/blob/master/controllers/SeomaticController.php#L840
