### ISSUE TITLE
Implement a way to include tracking-related scripts only if variable is set to true

### ISSUE THREAD

**Issue by Saboteur777** [khalwat/seomatic#313]
As GDPR is coming, websites should receive explicit consent before installing tracking cookies and initiating tracking scripts. I was wondering if it is possible to extend the `{% hook 'seomaticRender' %}` to include the tracking scripts only if a specific variable is set to true/cookie is present? 

The idea: 
1. User visits the page for the first time, only SEOMatic metadata is loaded (so no harm for SEO). 
2. If the user accepts the cookies (this can be indicated to SEOMatic with a variable set to true), then the tracking scripts can be loaded, too.

**Comment by khalwat** [comment]
Does the ability that SEOmatic has built-in to anonymize the data passed to GA mitigate this?

**Comment by Saboteur777** [comment]
I am not sure, but I don't think so: users have to have a way to opt out from the usage of cookies/tracking. Anonymization doesn't let the user to disable the tracking.

**Comment by frontedbe** [comment]
Upvoting this :)

**Comment by khalwat** [comment]
You can disable the Google Analytics rendering by doing this:

```twig
{% set seomaticHelper = seomaticHelper | merge({'ownerGoogleAnalyticsUID': ''}) %}
```

Similarly, you can disable the Google Tag Manager from rendering by doing this:

```twig
{% set seomaticHelper = seomaticHelper | merge({'ownerGoogleTagManagerID': ''}) %}
```
This need to be done _before_ the `{% hook 'seomaticRender' %}`

**Comment by Saboteur777** [comment]
Thank you! :)
