### ISSUE TITLE
Omit humans.txt if blank

### ISSUE THREAD

**Issue by ryanmasuga** [khalwat/seomatic#315]
This is for SEOmatic for Craft 2, so I realize you may be beyond doing anything for it, but this would apply to Craft 3, too: in the event we do not want a humans.txt file on our site, it would be nice if by leaving the field blank it would not output a link to it in the markup. Right now, wiping out the humans.txt content just reinserts all the default content.

**Comment by khalwat** [comment]
Is there a strong argument _against_ having a `humans.txt`?

**Comment by ryanmasuga** [comment]
No idea the for/against argument, but I would just expect that even if I wanted an empty humans.txt file, that's not even really possible, because all the defaults stuff pops back in when I wipe out what's in there. I think this is more of a "this isn't doing what I expect a normal field to do" situation. 

Or, what if I wanted to keep a separate humans.txt file, as a file, versioned, sitting on the server. Does SEOmatic always output the link to its own humans.txt file?

**Comment by khalwat** [comment]
If the file is sitting there on disk, the webserver will always use it.

There will be a way to do what you want in SEOmatic for Craft 3, but not for the 2.x version.
