### ISSUE TITLE
Can't get the "seoImage" override to work

### ISSUE THREAD

**Issue by ohlincik** [khalwat/seomatic#316]
I've poured over the documentation and tried everything I could think of but for whatever reason, I simply am not able to get the **seoImage** override to work.

I have the following code in a template to override the default SEOMatic values:

```twig
{% set seomaticMeta = seomaticMeta | merge({
  'seoTitle': 'Product# ' ~ entry.productNumber,
  'seoDescription': entry.title,
  'seoImage': entry.productPicture.first
}) %}
```

When inspecting the generated HTML, the **seoTitle** and **seoDescription** override the SEOMatic defaults but the **seoImage** does not override the default value.

I'm sorry if I missed something mentioned in the documentation. Any help would be appreciated.

**Comment by john-henry** [comment]
Does using `entry.productPicture.first().url` do anything for you?

**Comment by ohlincik** [comment]
Actually, that's what I did originally and that did not work. So I reviewed the SEOMatic docs and the default settings. There I saw that the default seoImage is being selected from an asset source and can have a transform applied to it. That led me to believe that an asset model should be set for seoImage rather than a string.

**Comment by khalwat** [comment]
It's required that it is a string.

**Comment by ohlincik** [comment]
The **seoImage** in a form of a string (url) also does not override the default.
