### ISSUE TITLE
Youtube channel URL format

### ISSUE THREAD

**Issue by dowadidi** [khalwat/seomatic#317]
Seomatic renders the Youtube channel url as follows:

```
{% set seomaticHelper = { 
    ...
    "youtubeChannelUrl": "https://www.youtube.com/c/UConcxZ0jK8OabQhckn26hGQ",
    ...
} %}
```

But if I go to the url, I get an "Channel does not exist" error.
But https://www.youtube.com/channel/UConcxZ0jK8OabQhckn26hGQ does.

**Comment by khalwat** [comment]
huh. It looks like `/c/` is still in use, though. Is it perhaps because you didn't register for a custom channel URL?

https://support.google.com/youtube/answer/2657968?hl=en
