### ISSUE TITLE
Add "itemCondition" property as sibling of "@type": "Offer"

### ISSUE THREAD

**Issue by sjcallender** [khalwat/seomatic#318]
Google notifies stores using Google Shopping when their data doesn't include a product condition. Would you be able to add this so our clients can manage the values themselves?

```
"@type": "Offer",
"priceCurrency": "AUD",
"price": "14.95",
"itemCondition": "https://schema.org/NewCondition",
"availability": "http://schema.org/InStock",
"url": "https:\/\/www.example.com\/products\/all-you-need-is-love-and-a-dog-cotton-cushion",
"sku": null,
"seller": {
	"@type": "Organization",
	"name": "example"
}
```

- Schema: [http://schema.org/itemCondition](http://schema.org/itemCondition)
- Example: [https://jsonld.com/product/](https://jsonld.com/product/)
- Context: [https://feedarmy.com/kb/google-shopping-missing-microdata-for-condition/](https://feedarmy.com/kb/google-shopping-missing-microdata-for-condition/)

**Comment by khalwat** [comment]
This is something you'll need to add in via Twig, because there's no real way for SEOmatic to know where the value should be pulled from.

https://github.com/nystudio107/seomatic/wiki/10.-Dynamic-Twig-SEO-Meta

**Comment by sjcallender** [comment]
Merging the value in via Twig is not working. Here's what I've tried.

```
	{% set seomaticMainEntityOfPage = seomaticMainEntityOfPage | merge({
    		offers: { 
        		itemCondition: 'http://schema.org/NewCondition'
    		}
	}) %}

	{% hook 'seomaticRender' %}
```
^^ This adds a whole new property unrelated to the product property, which doesn't help.

```
	{% set seomaticMeta = seomaticMeta | merge({
		offers: { 
    			itemCondition: 'http://schema.org/NewCondition'
		}
	}) %}

	{% hook 'seomaticRender' %}
```
^^ This does nothing.

What am I doing wrong, if anything?
