### ISSUE TITLE
Dynamic Twig SEO meta - Image Transforms not being used

### ISSUE THREAD

**Issue by john-henry** [khalwat/seomatic#321]
If I use the standard Dynamic SEO Twig like your Wiki example then `seomaticMeta.seoImage` just returns the image path of the source and not the actual transformed url to image.

Can I override this anywhere? I have tried doing the following to no avail

```
seoImageTransform: seomaticMeta.seoImageTransform,
seoFacebookImageTransform: seomaticMeta.seoFacebookImageTransform,
seoTwitterImageTransform: seomaticMeta.seoTwitterImageTransform,
```

Example used

```
{% set seomaticMeta = { 
    seoTitle: "Some Title",
    seoDescription: entry.summary,
    seoKeywords: "Some,Key,Words",
    seoImage: seomaticMeta.seoImage,
    canonicalUrl: entry.url,
    twitter: { 
        card: seomaticMeta.twitter.card,
        site: seomaticMeta.twitter.site,
        creator: seomaticMeta.twitter.creator,
        title: "Some Title",
        description: entry.summary,
        image: seomaticMeta.twitter.image
    },
    og: { 
        type: seomaticMeta.og.type,
        locale: seomaticMeta.og.locale,
        url: entry.url,
        title: "Some Title",
        description: entry.summary,
        image: seomaticMeta.og.image,
        site_name: seomaticMeta.og.site_name,
        see_also: seomaticMeta.og.see_also
    }
} %}
```

Notes

Entry variable is set in template pulling segment as a slug

I also tried `globalMetaOverride`, although not as flexible I would have thought, it still didn't work.

I also use `{% set seomaticMainEntityOfPage = seomaticMeta.getJsonLD(entry) %}` in same template and its pulls correct transformed image

**Comment by khalwat** [comment]
So I'm not really sure what you're trying to do; but the `seomaticMeta.seoImage` should already be set to the transformed image URL by the time it hits your templates:

https://github.com/nystudio107/seomatic/blob/master/services/SeomaticService.php#L859
