### ISSUE TITLE
Updating the 'Site SEO Name' incorrectly updates all pages until they are re-saved

### ISSUE THREAD

**Issue by SimonEast** [khalwat/seomatic#323]
*Super amazing plugin! Really appreciate such a useful and in-depth tool.*

Not sure if I'm hitting a bug though. Here are the steps I'm taking:

1. Set *SeoMatic > Site Meta > Site SEO Name* to `ABC`
2. Create a bunch of pages
3. Pages all correctly display `<title>[PageName] — ABC</title>`
4. Set *SeoMatic > Site Meta > Site SEO Name* to `XYZ`
5. All pages now (incorrectly) display `<title>XYZ</title>`
6. After going into individual pages and hitting the *Save* button, that page's title then correctly gets set to `<title>[PageName] — XYZ</title>`

But I really don't want my client to have to go in and re-save all their pages. I've tried clearing the cache but this doesn't fix it, so I don't think it's a cache issue.

Has anyone had this before?

SeoMatic 1.1.56 on Craft CMS 2.6.2998.

**Comment by khalwat** [comment]
Something doesn't quite sound right here... the site name is stored entirely separately from the SEO title. I've attempted to reproduce the locally, but am unable to?
