### ISSUE TITLE
Template Meta not working when using "own URL" option for section entries

### ISSUE THREAD

**Issue by OisteinH** [khalwat/seomatic#324]
I have added a Template Meta for a page. Everything looks fine in Preview, but it does not override the Site Meta when opened in a browser. I have tried deleting Craft and browser caches and different variants of Template paths but without success.

I suspect it may be related to the Template Path. My twig template, products.twig, is located in my templates/contentstructure folder. I have set Template path to contentstructure/products. In Preview the url to the page is https://www.mysite.com/contentstructure/products and the Template Meta is correct, but in a browser the url is https://www.mysite.com/products because I am using the "own URL" option for all entries in the contentstructure section. Could this be the reason it fails and is there a workaround?

**Comment by khalwat** [comment]
I think this is related to https://github.com/nystudio107/seomatic/issues/322
