### ISSUE TITLE
error caused by seo matic when using console commands

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [khalwat/seomatic#328]
While developing a console command, seo matic plugin probably somehow tries to intercept a request which is not there. Without SEO matic the console command run normal.

```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getPathInfo()'

```

**Comment by khalwat** [comment]
Sounds like you meant to file this for the SEOmatic for Craft 3 plugin? https://github.com/nystudio107/craft-seomatic

In any event, it's been fixed. It'll be rolled out in the next beta release.
