### ISSUE TITLE
Option to remove the HREFLANG tag

### ISSUE THREAD

**Issue by marc524** [khalwat/seomatic#329]
Hello,
We put our site through an SEO audit and it was recommended to use to either set the HREFLANG tag to **en** or remove it altogether. I do not see any option to do either of these. It appears the Alternate tag is hard-coded with HREFLANG to be 'x-default'.

This was the note from the audit:

> You currently use the “x-default”, which tells Google that page is to be used as the
> default if the user’s language is not specifically targeted. In this case, you are using the
> hreflang to tell Google this page is the default, but you also have a canonical tag telling
> Google a different page is the default.
> Recommendations:​
>  Since your website is not targeting multiple locations, we recommend
> that you remove the hreflang tag. If you would still like to use this tag, it should be changed
> to en for English.

The audit isn't quite right. The Canonical tag and the Alternate tag are exactly the same URL.

`<link rel="canonical" href="https://kidscorner.reframemedia.com/about/contact" />`
`<link rel="alternate" href="https://kidscorner.reframemedia.com/about/contact" hreflang="x-default" />`

I'm curious of your opinion if this is really an issue or not?

**Comment by hatzipanis** [comment]
We'd also love the ability to disable the `hreflang` tag/attribute. My client's website is a single language website and this is showing errors in Google Search Console. [This Stack thread](https://webmasters.stackexchange.com/a/65617) recommends removing it.

**Comment by marc524** [comment]
While I'm waiting for a response, I just commented out lines 22-32 of the seomatic/templates/_seo_meta.twig file. That removes it altogether.

**Comment by khalwat** [comment]
Yeah the way to do this would be to edit that file in the Craft 2.x version.

Note that I'm not sure I agree with the recommendations. The SEO audit likely just ran some automated tool, and spat that out (for whatever reason). It's perfectly valid to use `hreflang="x-default"` in the manner described:

> The new x-default hreflang attribute value signals to our algorithms that this page doesn’t target any specific language or locale and is the default page when no other page is better suited. For example, it would be the page our algorithms try to show French-speaking searchers worldwide or English-speaking searchers on google.ca.

https://webmasters.googleblog.com/2013/04/x-default-hreflang-for-international-pages.html

**Comment by cherrykoda** [comment]
I'm also dealing with a very SEO focused client that is receiving errors/dings through scanners such as SEMRush for having "conflicting" hreflang tags. I cant set or edit these for their single-language site and that's pretty frustrating. 

I'd really like to see SEOMatic have the ability to turn on/off options for what gets injected into the header. Providing less is often more, as in this case. Consider this a feature request in addition to 'me too'.

**Comment by khalwat** [comment]
@cherrykoda are you using Craft 3.x or 2.x?

This issue is for Craft 2.x... and if you really want, you can pass in your own template to use on Craft 2.x

If you're on Craft 3.x, it has the ability to disable the rendering of anything you don't want rendered via the Twig API.
