### ISSUE TITLE
502 error on enabling plugin. Disabling removes this issue

### ISSUE THREAD

**Issue by admench** [khalwat/seomatic#33]
Hi,

I recently took the time to add SEOmatic fields to areas of my site so that I could specify more specific meta data per entry. Doing this has caused those pages to throw a 502 bad gateway (running nginx). I have pages that do not have this field in and they run fine. Disabling the SEOmatic plugin results in the pages loading fine again. Have you had any reports on this problem before? If you need log files I can provide them, but when searching craft.log (in my local dev mode enabled environment) I don't see anything that makes sense relating to this issue. Thanks in advance, Adam

**Comment by khalwat** [comment]
I've never heard this before, no.  I have a hard time understanding how it could actually happen as well.  I'd need more info/data to look into it.

**Comment by khalwat** [comment]
So I'm still having a hard time understanding how the FieldType could result in a 502 error.  I'm using SEOmatic FieldTypes on a similar dev setup running Nginx without incident.

Have you tried pushing to staging or another environment to see if the issue exists there?

**Comment by admench** [comment]
Hi

I can confirm the same problem happened on the staging server - I am going
to investigate further this morning.

**Comment by admench** [comment]
OK I completely uninstalled the plugin, thus removing any reference to it in the DB, then re downloaded it and installed a fresh copy. After initialising the plugin again in Craft, and clicking on the Get Started button on the welcome screen, I save the default data then I load my page that has the hook in the head and it breaks with a 502 bad gateway again. Again, disabling fixes this.
Craft.log shows no signs of any errors and nothing new in seomatic.log - perhaps its something with my nginx setup, but the remote site does the same

**Comment by khalwat** [comment]
If you're able, perhaps I can look into this on the staging server?  If you don't mind giving me access, I'd like to see what's going on here.  It's all very strange.

**Comment by khalwat** [comment]
Given the nature of the error, it makes it all the stranger:

http://pcsupport.about.com/od/findbyerrormessage/a/502error.htm

I realize that you've narrowed this down to happening only when SEOmatic is installed, which certainly points to it being the culprit.  But I haven't the foggiest how SEOmatic could cause a bad gateway error.

**Comment by khalwat** [comment]
Can you check your nginx/php-fpm logs?  This really seems like a server configuration issue.  Maybe see if you have mod_security or Suhosin installed?

_something_ is acting as a proxy here, I think.  I highly suspect some kind of server configuration issue.

**Comment by admench** [comment]
Hi 

Here is the contents of the nginx log file for the site, on the remote server.

2016/03/03 17:40:26 [error] 19126#0: *6 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 151.228.145.38, server: youi.design, request: "POST /index.php?p=admin/actions/tasks/getRunningTaskInfo HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "youi.design", referrer: "https://youi.design/admin/settings"

**Comment by admench** [comment]
I agree, this seems like it is a server issue, even though disabling the plugin stops the error.

**Comment by admench** [comment]
Shall I create a user and ssh key so that you can have a look?

**Comment by admench** [comment]
It seems like it isn't your problem!

**Comment by khalwat** [comment]
That error message probably isn't relevant.  But I think you should have your server guys take a look at the setup.  I'm not abdicating all responsibility, but my instinct tells me this is a server misconfiguration issue.  It's strange to me that it would happen both on dev and stating, though.

**Comment by admench** [comment]
It is my server setup, I'm running a forge setup on DO. It is strange that it is happening on both, yes.

**Comment by admench** [comment]
Locally it is a laravel homestead vagrant box

**Comment by khalwat** [comment]
If you set `always_populate_raw_post_data` to `-1` in php.ini does the error go away?

**Comment by admench** [comment]
Unfortunately not.

**Comment by khalwat** [comment]
Did you restart Nginx and fpm?

```
 sudo nginx -s reload
 sudo service php-fpm restart
```

**Comment by admench** [comment]
Yes I did that. Thanks - I am continuing to try to debug this

**Comment by khalwat** [comment]
Let's talk on Slack a bit.

**Comment by khalwat** [comment]
This ended up being due to `{title}` and similar parsed fields used in the various fields in SEOmatic... which used to work, but now apparently result in an infinite loop that ultimately crashes the php thread.

This is fixed in `develop` and I'll roll it into a release soon.

https://github.com/nystudio107/seomatic/tree/develop

**Comment by admench** [comment]
Thanks Andrew.

**Comment by clarknelson** [comment]
I've been getting a similar problem with the plugin. On my deployed server it shows 502 on the front-end but the back-end still works. When I disable our friend SEOmatic the error goes away. 

Heres the error in the nginx logs:
```
2021/02/15 15:24:42 [error] 799#799: *105 upstream sent too big header while reading response header from upstream, client: 99.46.148.171, server: my.domain.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "my.domain.com"
```

**Comment by khalwat** [comment]
@clarknelson this is the old Craft 2 version of the plugin, which is deprecated now

**Comment by clarknelson** [comment]
oh I didn't notice, I hope you don't mind if I open a new issue in the Craft 3 plugin
