### ISSUE TITLE
Hide sections and category groups without urls

### ISSUE THREAD

**Issue by keithmancuso** [khalwat/seomatic#332]
Loving the content sep settings, a huge huge step forward.  But we have a lot of sections without their own urls that are showing a lot of red circles that make us and our clients feel like we are doing something wrong.

Is it possible to hide entries that don’t have urls since the would never have seo settings?

**Comment by khalwat** [comment]
I think you meant to post this on the Craft 3 repo? https://github.com/nystudio107/craft-seomatic

In any event, this should be taken care of now.
