### ISSUE TITLE
Meta Tab Not Displaying for Entries

### ISSUE THREAD

**Issue by make-ready** [khalwat/seomatic#334]
My dev team recently installed the SEOmatic plugin. Seems like a great plugin. Everything is working well, except the meta tab is not displaying on entries. I need to update titles, meta descriptions, etc. for individual pages. What is the best way to do this?

**Comment by motorzen** [comment]
@make-ready I think the documentation makes some assumptions about the Craft admin's setup and knowledge that might leave one wondering how to get to what you might see in their demo video. 

1. Go into Settings > Fields > + New Field and create a new field called "SEOMatic". Select the SEOMatic field type.
2. Go into Settings > Sections > Edit entry types to add a new Tab (rename it "Meta" if you like). Add the "SEOMatic" field from step one to this tab.
3. Edit your entries > Click the new Meta tab to find the "SEOMatic" field. Click Save to add the new SEO tags automatically into your entry.
4. Profit!

**Comment by make-ready** [comment]
That's great! Thank you for taking the time to respond.
