### ISSUE TITLE
How to set custom Title, for example in a section?

### ISSUE THREAD

**Issue by zzseba78** [khalwat/seomatic#335]
Hi there, first of all, terrific plugin, i use it on each Craft project, awesome.

I have a question, for most of all entries it´s great that SEOmatic creates the title ( page title and open graph, etc ). But sometimes i have a section, that have a list of entries, and i want to set myself the Section title ( not generic fallback default of SEOmatic ). It´s there a way to override this values?

Thanks

**Comment by khalwat** [comment]
Yes, you can do it via Twig as described here:

https://github.com/nystudio107/seomatic/wiki/10.-Dynamic-Twig-SEO-Meta
