### ISSUE TITLE
Duplicated entries in tab Content SEO

### ISSUE THREAD

**Issue by ghost** [khalwat/seomatic#337]
Hi,

Awesome plugin! But I've discovered a bug: On a multilingual website (NL and EN) the tabs Content SEO shows duplicated entries. Any clue how to fix this? Thanks

![schermafbeelding 2018-05-03 om 14 21 46](https://user-images.githubusercontent.com/24385708/39576165-8b2d8f7e-4edd-11e8-8966-4c3e25ec92e3.png)
![schermafbeelding 2018-05-03 om 14 21 31](https://user-images.githubusercontent.com/24385708/39576166-8b4a6626-4edd-11e8-934f-38ed3e44057b.png)

**Comment by khalwat** [comment]
So I think you meant to post this on the SEOmatic for Craft 3 repo: https://github.com/nystudio107/craft-seomatic

...but in any event, this has been fixed.
