### ISSUE TITLE
Canonical URL's and Case Sensitivity

### ISSUE THREAD

**Issue by jonlongnecker** [khalwat/seomatic#338]
I just noticed that a client's server doesn't have case sensitivity enabled after they ran a promotion at site.com/MoneyBall. I would have assumed that the canonical URL meta tag created by SEOmatic would have used the lowercase slug from Craft, but it looks like it's grabbing it straight out of the URL so it shows site.com/MoneyBall as well.

Is that on purpose? Would it make sense to change that functionality to use the Craft url?

Thanks!

**Comment by khalwat** [comment]
I think by default it just uses the `craft.request.url` which is the incoming URL to set the canonical URL for pages that don't have entries. This is probably actually something that should be addressed (if it needs to be) server-side, I'd think.

**Comment by jonlongnecker** [comment]
That makes sense, thanks.

**Comment by jonlongnecker** [comment]
So I'm going to push back on this a bit. The host (webfaction) is all locked down in regards to supporting case insensitivity. But regardless, I don't think the canonical URL shouldn't use `craft.request.url` - it should use the slug set in the entry for this very reason. Canonical should be the definitive URL, not just the one that's visible in the URL bar.

**Comment by khalwat** [comment]
You can easily change it to be whatever you want it to be, via:

```
{% set seomaticMeta = seomaticMeta | merge({'canonicalUrl': craft.request.url|lower }) %}
```
