### ISSUE TITLE
Rendering Entity Name and other Address parts individually

### ISSUE THREAD

**Issue by donnyburnside** [khalwat/seomatic#342]
Hello,

I need to apply some styles to different parts of the address. Typically we would use `seomaticHelper.ownerAddressHtml` which renders the full address. However, because of my use-case, this is not sufficient.

What I would like to do is render the `entity name` field by itself, followed by each line of the address. This will let me wrap the specific parts of the address in the HTML tags that are necessary for me to complete my design.

I've read the documentation, had a look on Google and also searched here but can't find any mention of how to render parts of the address individually.

Any help would be great, and thanks in advance!

**Comment by khalwat** [comment]
You should be able to get this information individually by looking at the `seomaticIdentity` variable. To see what's in it, you can do `{{ dump(seomaticIdentity) }}`
