### ISSUE TITLE
Renaming Asset Transform causing error 

### ISSUE THREAD

**Issue by terryupton** [khalwat/seomatic#343]
I have changed my Asset Transform handle for my Twitter feed and when even though I have updated the SEOmatic field type and the General settings I get the error that the transform cannot be found. This occurs both on the front-end and back-end. I have saved the section entries again to re-save the page(s), I have cleared all caches, I have tried with singles and channels and all the same outcome.

It appears like once the SEOmatic fields params have been set these are not updated again when you change them in the field section in Craft.

If this is of help here is my stack trace for back-end:
https://gist.github.com/terryupton/17e5ebf9a49e6bf2c31d24fcd078b86e

If this is of help here is my stack trace for front-end:
https://gist.github.com/terryupton/a22419c6951f1155170b49cf849bc084

I have tried all sorts but cannot figure a way to revert this. Seems like a possible bug.
Thoughts?

Thanks.

**Comment by khalwat** [comment]
So the issue is that each field in SEOmatic has that old stale information saved in it. You'd need to re-save each entry with the new transform to populate it.

The path of least resistance here is just to re-create the transform with the old handle.
