### ISSUE TITLE
Possible to have diff "Site SEO Name Placement" for <title> and <meta og:title>?

### ISSUE THREAD

**Issue by frontedbe** [khalwat/seomatic#346]
Hi!

I'd like to have my <title> tags have the following format: "title-of-page | siteName" so when you have different pages of your site open in browser's tabs, you can clearly see which tab contains which page, which works nice without a problem.

Downside is that by doing this, my og:title also gets filled in this way, which is not what I want when the page is posted on facebook, for this matter I'd like it to have the following format: "siteName | title-of-page". So the order of the page title and sitename should be reversed. 

Maybe I'm missing something here but thought, why not ask :)

(Craft 2 question)

Thanks!

**Comment by khalwat** [comment]
Not in the version for Craft 2.x unfortunately.

**Comment by mylesthedev** [comment]
Hey @khalwat is this possible in Craft 3.X?

**Comment by khalwat** [comment]
@mediabeastnz yes -- they are separate fields
