### ISSUE TITLE
SEO image from matrix field

### ISSUE THREAD

**Issue by janhendrickx** [khalwat/seomatic#349]
I'm using a (required) matrix field for the hero of the singles and some structures in which it's possible to choose between a video or an image. If they choose a video it's also required to choose an image (as placeholder).  
So there's always an image available that can be used as image for SEO, but it's not possible (yet) to select it from a matrix field. 
Shouldn't it be handy if this is possible - or am I missing something and is it possible?

**Comment by khalwat** [comment]
You'd need to do the via Twig; SEOmatic would need to have a UX that let you pick not just which Matrix field, but then which matrix block, and then which field inside the matrix block. Which would get a bit unwieldily.
