### ISSUE TITLE
ld+json is not fully parsed for env strings

### ISSUE THREAD

**Issue by timkelty** [khalwat/seomatic#35]
![screen shot 2016-03-02 at 4 33 08 pm](https://cloud.githubusercontent.com/assets/18329/13476233/dd2ed1ca-e094-11e5-9ab6-fb1ade78cec8.png)

Namely:
- Identity → location.url
- WebSite → copyrightHolder.location.url, author.location.url
- Place → url

**Comment by khalwat** [comment]
hmmmm.  It actually parses the entire array, or rather it's supposed to.  Is `{baseUrl}` actually an `environmentalVariable`?  Show me your settings in `general.php`

**Comment by timkelty** [comment]
It is set. In fact, it's working in _some_ places (where you see the acutal url in the example).

Condensed/relevant `general.php`:

``` php
$scheme = isset($_SERVER['HTTPS']) ? 'https' : 'http';
$host = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : $_SERVER['SERVER_NAME'];
$url = $scheme . '://' . $host . '/';

$config['environmentVariables'] = array(
    'basePath'   => BASE_PATH,
    'baseUrl'    => $url,
);

// etc...

return $config;
```

**Comment by khalwat** [comment]
That's just plain weird.  This is the routine that recursively goes through the array to do the sanitizing/parsing:

```
private function _sanitizeArray(&$theArray)
{
    foreach ($theArray as $key => $value)
    {
        if (is_string($value))
        {
            $value = craft()->config->parseEnvironmentString($value);
            $value = strip_tags($value);
            if ($key == 'email')
                $value = $this->encodeEmailAddress($value);
            else
                $value = htmlspecialchars($value, ENT_COMPAT | ENT_HTML401, 'UTF-8', false);
            $theArray[$key] = $value;
        }
        else
        {
            if (is_array($value))
                $this->_sanitizeArray($value);
        }
    }
} /* -- _sanitizeArray */
```

I take it that `{baseUrl}` is what you entered into the field in SEOmatic yes?  It's not something you're setting/changing via Twig?

**Comment by timkelty** [comment]
Strange indeed.
Yes, `{baseUrl}` is what is entered in the "Entity URL" field.

If I replace it with a static value, it works everywhere.

**Comment by timkelty** [comment]
Ah - I think you want to do this:

``` php
                if (is_array($value))
                    $theArray[$key] = $this->_sanitizeArray($value);
```

Seems to fix it on my end.

**Comment by khalwat** [comment]
oooh, that was a fun one!  I've fixed it, and will roll it into 1.1.6.  If you want to try out the fix, grab the build from the `develop` branch:

https://github.com/nystudio107/seomatic/tree/develop

**Comment by timkelty** [comment]
Recursion is always fun!

**Comment by khalwat** [comment]
I love recursive algorithms.  This was me not understanding that `foreach` passes in a new copy of the array, which means changes made would be discarded.  Oops.

So it's not really a recursive issue, I suppose, but it only surfaces if you recurse into the array more than 1 level.
