### ISSUE TITLE
Tracking scripts can't be enabled

### ISSUE THREAD

**Issue by thaoms** [khalwat/seomatic#351]
All fields get saved, except the enable switch.

![tracking](https://user-images.githubusercontent.com/2323270/41588661-ab735f8a-73b2-11e8-818c-02bdad11336a.gif)

**Comment by skramstad** [comment]
Same problem here!

**Comment by HelgeSverre** [comment]
Got the same problem here, using version 3.1.6

**Comment by maccadesign** [comment]
Is live Production environment selected in settings?

**Comment by HelgeSverre** [comment]
@maccadesign  in my case the environment is set to "production" and DevMode is false

**Comment by thaoms** [comment]
I realized we are in the wrong repo - https://github.com/nystudio107/craft-seomatic
