### ISSUE TITLE
Sharing on Google Plus gets incorrect meta info

### ISSUE THREAD

**Issue by jonXmack** [khalwat/seomatic#356]
I'm having an issue where when sharing a page on Google Plus it uses the WebSite ld+json data rather than the OG meta information, or the WebPage ld+json data. I've run the page through the [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool) and there are no errors or issues, and using [Social Debug](https://socialdebug.com/) shows the correct data for Google Plus, but when actually sharing a page, or blog post, it doesn't work correctly.

**Comment by hashtagerrors** [comment]
Same Issue.  [Social Debug](https://socialdebug.com/results?url=http%3A%2F%2Fwww.hashtagerrors.com%2Fblog%2Freducing-wordpress-database-size) shows everthing perfect but sharing on google plus shows entity name instead of Title.
Craft 2.7
SEOmatic 1.1.56

**Comment by khalwat** [comment]
Google Plus is being discontinued https://www.engadget.com/2018/10/08/google-shutting-down-google-plus/
