### ISSUE TITLE
Meta tags issue in SEOMatic Craft CMS

### ISSUE THREAD

**Issue by setjo1980** [khalwat/seomatic#360]
My site is using SEOmatic plugin.. but all pages are using home page meta tags.. Please let me know how to have different meta tags for internal pages.

![plugin](https://user-images.githubusercontent.com/12120829/46031730-576d7580-c117-11e8-93aa-75c420a19b0f.PNG)
![layout](https://user-images.githubusercontent.com/12120829/46031737-5dfbed00-c117-11e8-80de-9210d2e927a7.PNG)

**Comment by flarpflinger** [comment]
I am also experiencing this. Any ideas what is causing this?

**Comment by khalwat** [comment]
I'd suggest using a SEOmatic Meta field instead.
