### ISSUE TITLE
Enhance Response Times when hitting API Endpoints

### ISSUE THREAD

**Issue by camposcristian** [khalwat/seomatic#361]
We're about to receive a considerable load of traffic and we've performed a load test using load impact.

What we've found out is that SEO Matic is becoming our bottleneck at the moment:

![image](https://user-images.githubusercontent.com/1928706/46246454-396a8280-c441-11e8-80d9-95b550c8b533.png)

Any tips or considerations in order to increase the response ratio?

Thanks!

**Comment by khalwat** [comment]
I believe this should be posted in the SEOmatic for Craft 3 repo: https://github.com/nystudio107/craft-seomatic
