### ISSUE TITLE
Craft Commerce Single Product Support

### ISSUE THREAD

**Issue by glenwheeler-ps** [khalwat/seomatic#362]
Hey Guys,

We use this plugin for Craft CMS and Craft Commerce however, like you can add SEO data for Pages and Blogs theres no option to Add SEO for Singular Products. Is this just because SEOMatic only Supports Craft CMS and not Craft Commerce?.

I noticed in the settings theres an option to Edit "Products" but this is just SEO data for the Products as a whole and not singular products. It also allows us to add SEO data and Product Category Level but just not Singular Product level like you can with blogs. 

Am I missing something at all?

**Comment by khalwat** [comment]
You should add an SEOmatic field to your Product layout, and it'll work
