### ISSUE TITLE
Link to humans.txt is wrong

### ISSUE THREAD

**Issue by piotrpog** [khalwat/seomatic#363]
When domain doesnt direct to craft `web` folder, but craft install is in subfolder itself, for example: `domain.com/craft/web`
humans .txt file path doesnt takes this subfolder into account, and is like this:
`domain.com/humans.txt`

I think its something related to this:
https://github.com/nystudio107/craft-retour/issues/20

**edit: 
This is supposed to be in 3.x repo, please close this issue.**

**Comment by khalwat** [comment]
I'm assuming you're looking for the Craft 3 version of SEOmatic -> https://github.com/nystudio107/craft-seomatic
