### ISSUE TITLE
Feature Request: LinkedIn and Hubspot Support

### ISSUE THREAD

**Issue by stevehurst** [khalwat/seomatic#367]
The current social and tracking settings are great. However, we also use LinkedIn and Hubspot, and would like to offer our content editors and site admins access to IDs and script settings alongside Google Analytics and our other social settings within SEOmatic.

LinkedIn Features:
- Insights Tracking Code
- Social previews / meta tags

Hubspot Features:
- Tracking Code

**Comment by khalwat** [comment]
This is something that could be added to the Craft 3 version, if you want to post a FR there: https://github.com/nystudio107/craft-seomatic
