### ISSUE TITLE
Template Meta Issue

### ISSUE THREAD

**Issue by RichardAlbary** [khalwat/seomatic#37]
Hi,

First of all, thank you for the awesome plugin.

I'm having a little bit of trouble getting Template meta's working. I'm trying to set them up for sub-menu entries. While I can get the SEOmatic template meta working for the base template for the section, even though I use {% include %} for a sub-menu template within the base section template, it doesn't load when I try pointing it to the sub-menu entry template. I could be missing something here, as I'm a bit of a Craft novice, but any help would be greatly appreciated!

**Comment by khalwat** [comment]
So it's very likely you're running into a Twig _scoping_ issue.  When you `{% include %}` a template, it's given a _copy_ of the current Twig context (variables, etc.), which means that any changes made there are not propagated back to the parent template.

So for instance if you `{% include %}` a template that changes some SEOmatic variables, they will _not_ be changed in the parent context's scope.

It's just how Twig works.

So you'll either need to use `extends` or `embed`

http://twig.sensiolabs.org/doc/tags/extends.html

http://twig.sensiolabs.org/doc/tags/embed.html

**Comment by khalwat** [comment]
I added this to the README.md:

**Important:** Due to the way Twig scoping works, if you `{% include %}` a template, it's given a copy of the current Twig context (variables, etc.), which means that any changes made there are not propagated back to the parent template.

So for instance if you `{% include %}` a template that changes some SEOmatic variables, they will **not** be changed in the parent context's scope, so they will not be rendered by SEOmatic.

You'll need to modify the SEOmatic variables in a template that `{% extends %}` the main `layout.twig` template or via Twig `embeds`.

**Comment by RichardAlbary** [comment]
Many thanks for your help on this. Hopefully I should be on the right track now!

Kind regards,

Richard Chalkley
MA BA(Hons) PROJECT MANAGER

6 JOLLIFFE'S COURT • 51-57 HIGH STREET • WIVENHOE • COLCHESTER • ESSEX • CO7 9AZ
TEL:  +44 (0)1206 585200  •  EMAIL:  ENQUIRIES@SPIFFINGCOVERS.COM mailto:ENQUIRIES@SPIFFINGCOVERS.COM  •  WEB:  SPIFFINGCOVERS.COM http://spiffingcovers.com/ 

The information provided in the email is to be treated as confidential and may not be used or disclosed except for the purpose for which it has been sent. If you are not the named recipient or have reason to believe that you are not the intended recipient, please notify the sender immediately and do not disclose the contents to another person, use it for any purpose or store or copy the information in any medium.   Although this email and any attachments are believed to be free from any virus or other defect which might affect any system into which they are opened or received, it is the responsibility of the recipient to check that they are virus free and that they will in no way affect systems and data.  No responsibility is accepted by SpiffingCovers.com http://spiffingcovers.com/ Ltd. for any loss or damage arising in any way from their receipt, opening or use.   Any views or opinions expressed are those of the individual sender and do not necessarily represent the view of SpiffingCovers.com http://spiffingcovers.com/ Ltd, its subsidiaries or associates.   VAT Registration No. 158 6202 06
