### ISSUE TITLE
Content SEO table and SEO field in Single

### ISSUE THREAD

**Issue by umkasanki** [khalwat/seomatic#371]
I use the SEO Settings field in Singles.
When entering data in the field, the information in the general table is not updated.
![field](https://user-images.githubusercontent.com/496132/48602816-75bc5880-e985-11e8-8800-9d58c82b4f76.png)
![table](https://user-images.githubusercontent.com/496132/48602821-781eb280-e985-11e8-894b-27ec0b1d131c.png)

**Comment by khalwat** [comment]
This is being posted in the wrong repo; you want the Craft 3 plugin: https://github.com/nystudio107/craft-seomatic
