### ISSUE TITLE
hreflang not outputting pagination segment

### ISSUE THREAD

**Issue by steve-holland** [khalwat/seomatic#372]
We have a site in English and French and on category listing pages the pagination segment doesn't seem to be output. So for example, for this Url:

`https://www.example.com/category/category-child/p3`

The following link tags are output:

```
<link rel="canonical" href="https://www.example.com/category/category-child/p3">
<link rel="alternate" href="https://www.example.com/category/category-child" hreflang="x-default">
<link rel="alternate" hreflang="en" href="https://www.example.com/category/category-child">
<link rel="alternate" hreflang="fr" href="https://www.example.com/fr/category-in-french/category-child-in-french">
```

The canonical tag seems to be correct, but the other three tags are missing the `/p3` segment. 

I guess main question is, should the `/p3` part of the url be output too? Only we're getting `'en' - no return tags` errors in Google Search console relating to the hreflang tags.

Edit: Craft v2.6.3016, SEOMatic v1.1.56

**Comment by khalwat** [comment]
Yeah I think you'd need to provide your own custom template to handle this, passing that in to the `{% hook 'seomatic' %}`
