### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by m8brgarc** [khalwat/seomatic#376]
Not sure what is causing this error but I'm getting this:

`2018-12-11 14:27:40 [-][1][05ab82eef66db7ecb5751e7dea5c3ba0][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: nystudio107\seomatic\models\MetaSiteVars::additionalSitemaps in /Users/brandon/Iddigital/thebayouchurch/vendor/yiisoft/yii2/base/Component.php:209
`

**Comment by khalwat** [comment]
This is because the database has been updated, but the version of SEOmatic that is running has not.

Do `composer update` and everything should be fixed for you.
