### ISSUE TITLE
Duplicate 'country codes' in canonical url localized site

### ISSUE THREAD

**Issue by almeric** [khalwat/seomatic#38]
Hi,

I've added this plugin to a localized site and I'm having some issues with the canonical url.  

Given the following `siteUrl` config in general.php [as per the docs](https://craftcms.com/docs/localization-guide):  

``` php
'siteUrl' => array(
  "en" => 'http://testsite.lan/en/',
  "nl" => 'http://testsite.lan/nl/',
  "de" => 'http://testsite.lan/de/',
  "fr" => 'http://testsite.lan/fr/',
  "be" => 'http://testsite.lan/be/',
  "da" => 'http://testsite.lan/da/',
)
```

Gives the following canonical url on http://testsite.lan/en/: `<link rel="canonical" href="//localhost:3000/en/en/" />`.   

It appears `craft()->getSiteUrl()` returns `http://testsite.lan/en` while `craft()->request->url`returns `/en/` and these are concatenated together.  

Is this an config issue on my end?

**Comment by khalwat** [comment]
okay I pushed a change to `develop` that should fix it: https://github.com/nystudio107/seomatic/tree/develop

**Comment by almeric** [comment]
That seems to have fixed the issue! 

Thanks!
