### ISSUE TITLE
Trying to get property 'sourceName' of non-object when clicking breadcrumb in seo content

### ISSUE THREAD

**Issue by bkmorse** [khalwat/seomatic#392]
Seomatic plugin version 3.3.5
Craft cms version 3.4.15

Issue:

I have a multi site setup. I click Seomatic in the CP's left sidebar, bringing me to: admin/seomatic

Then I click "Content SEO", bringing me to: admin/seomatic/content

I select "United States" from the dropdown that appears to the right of heading: Content SEO, bringing me to: admin/seomatic/content/en_us
![Screen Shot 2020-05-29 at 11 21 20 AM](https://user-images.githubusercontent.com/84529/83276554-c594f600-a19e-11ea-9c2c-afb45cdc2ed9.png)

It displays a table listing, I click on an item Products, bringing me to: **admin/seomatic/edit-content/general/section/products/en_us**
![Screen Shot 2020-05-29 at 11 22 35 AM](https://user-images.githubusercontent.com/84529/83276557-c9287d00-a19e-11ea-9d67-9df007681ce2.png)

Then I click the "Products - General" breadcrumb at the top of the page, it is the third link to the right of the hamburger link in the top right
![Screen Shot 2020-05-29 at 11 23 27 AM](https://user-images.githubusercontent.com/84529/83276629-e3faf180-a19e-11ea-85c5-a6c6452a4386.png)

Which now brings me to: **admin/seomatic/edit-content/general/section/products**

with an error of: Trying to get property 'sourceName' of non-object
![Screen Shot 2020-05-29 at 11 25 53 AM](https://user-images.githubusercontent.com/84529/83276827-30dec800-a19f-11ea-85eb-62fccd16d3f4.png)

I checked what site id ($siteIdToLoad) it was using on line 474 of SettingsController.php and it was using site id 1, when I set it to 2, it worked as expected.

Here is a screenshot from the craft_sites table:
![Screen Shot 2020-05-29 at 11 28 57 AM](https://user-images.githubusercontent.com/84529/83277434-0b05f300-a1a0-11ea-8cff-d9e04bce6122.png)

If I modify the url to: **admin/seomatic/edit-content/general/section/products/en_us**

then it works.

**Comment by sjcallender** [comment]
@bkmorse You posted in the Craft 2 version of this plugin. I found this because I'm having a similar issue with a multisite build. Did you resolve this?

**Comment by bkmorse** [comment]
@sjcallender I did not, I did not realize I added it to craft cms version 2 of this. I'll post this to the craft cms 3 version, thanks!

**Comment by bkmorse** [comment]
Added the issue, follow here https://github.com/nystudio107/craft-seomatic/issues/689
