### ISSUE TITLE
“Internal server error” when piggybacking (in PHP)

### ISSUE THREAD

**Issue by joshuabaker** [khalwat/seomatic#396]
### Describe the bug

I’m getting an internal “Internal server error” error for `seomatic` when using GraphQL via the PHP Craft service. 

* The query works fine via the GraphiQL interface
* I can’t see anything in the logs
* I’ve cleared all caches
* I’ve tried resaving all entries

I’m really struggling to debug. Do you have any idea why this might happen?

### To reproduce

I’ve simplified the use case down to just getting the `metaTitleContainer`.

##### PHP

```php
$schema = Gql::createFullAccessSchema();

$query = "
  {
    entry(id: 555) {
      seomatic {
        metaTitleContainer
      }
    }
  }
";

$response = Craft::$app->getGql()->executeQuery($schema, $query);
```

##### Response

```json
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 4,
          "column": 17
        }
      ],
      "path": [
        "entry",
        "seomatic"
      ]
    }
  ],
  "data": {
    "entry": {
      "seomatic": null
    }
  }
}
```

### Versions
- Plugin version: 3.3.26
- Craft version: 3.5.15.1

**Comment by khalwat** [comment]
This issue is posted on the old deprecated Craft 2 repository. It never supported GraphQL, so I'm wondering if perhaps you posted this in the wrong place?

**Comment by joshuabaker** [comment]
Possibly. I don’t actually recall. Either way, it’s not been an issue for a few years. 🙏🏻
