### ISSUE TITLE
Google Tag Manager code ends up in body instead of head

### ISSUE THREAD

**Issue by royslampaq** [khalwat/seomatic#397]
When I set 'Head' as the Script Render Location in the Google Tag Manager settings, the resulting code ends up in the <body> tag, the same as when I choose 'Body Begin'. Changing it to 'Body End' does change the position as expected.

I'm using the latest version (3.3.30); on another site I have access to, which runs on 3.3.8, the code ends up in the right place. but I can't find anything which might cause this issue.

**Comment by jamesmacwhite** [comment]
You might want to flag this here: https://github.com/nystudio107/craft-seomatic

This is for the Craft 2 version.
