### ISSUE TITLE
Provide data in a structured way on GraphQL endpoint

### ISSUE THREAD

**Issue by tremby** [khalwat/seomatic#399]
### Is your feature request related to a problem? Please describe.

My site front end is built in React. I might be able to take the HTML output from Seomatic's GQL API and dump that in with `dangerouslySetInnerHTML`, though React fragments don't support that and I think these tags need to be direct children of `<head>` so that may not work. Besides, I would rather and parse a structured form of the data and build the nodes programmatically.

### Describe the solution you would like

I'd like there to be a way to get data about the various meta tags and links etc from the GQL API in a structured form, rather than only as an HTML dump. It could be objects for each tag with fields for attributes etc, or it could be just a JSON string or similar.

### Describe alternatives you have considered

I could parse the HTML to React nodes with html-react-parser or Interweave or similar, but these are both heavy handed solutions and would add a lot to my bundle size.

### Additional context

I'm on Craft 4, headless, multisite.

**Comment by khalwat** [comment]
This is the old Craft CMS 2 repository for a deprecated version of the SEOmatic plugin; you want: https://github.com/nystudio107/craft-seomatic

In any event, what you want is already implemented, you just need to pass in `asArray: true`:

https://nystudio107.com/docs/seomatic/advanced.html#graphql-query-support

**Comment by tremby** [comment]
So it is. Lovely, thanks, and sorry for the noise.
