### ISSUE TITLE
Can't retrieve (GQL) or save (control panel) humans template

### ISSUE THREAD

**Issue by tremby** [khalwat/seomatic#400]
### Describe the bug

I get an error when trying to retrieve or save the humans template.

### To reproduce
Steps to reproduce the behaviour:
1. Query via GQL for `seomatic { frontendTemplates { contents filename } }` or `seomatic { frontendTemplateContainer }`
2. See response, which has `Error rendering template string -> The "defined" test only works with simple variables in "__string_template__9d8842c587f4804bb2efb8391bf2419a" at line 4. ` where I expect the humans.txt content to be
3. Go to control panel -> SEOmatic -> global SEO -> humans
4. See default humans.txt template (which does not contain the string `defined` at all)
5. Without editing click to save
6. See error. It is partially obscured under the bottom of the text field. `Error rendering template string -> The "defined" test only works with simple variables in "__string_template__9d8842c587f4804bb2efb8391bf2419a" at line 4. `

### Expected behaviour
When retrieving and an error takes place, I expect not to get a response at all, or for graphql errors to be produced, or to get an empty result. In fact, the string I expect to contain the humans.txt content has a string error message in it. This is bad since I might inadvertently serve this error message as the file.

When saving the humans.txt template I expect it to save properly with no error.

# Screenshots
![graphql query and response showing error message](https://user-images.githubusercontent.com/199635/163072275-ebbebe80-d928-467e-9644-361458d9216a.png)
![seomatic control panel showing error message hiding at bottom of text field](https://user-images.githubusercontent.com/199635/163072300-cf2ecd52-ec7b-4e5d-9ea3-a74080fa064d.png)

### Versions
- Plugin version: 4.0.0-beta.7
- Craft version: 4.0.x at 38a1659

**Comment by khalwat** [comment]
I think you've posted this on the wrong repository; this repository is for an old version of SEOmatic for Craft CMS version 2

You likely want: https://github.com/nystudio107/craft-seomatic
