### ISSUE TITLE
Section Entries Not Populating to Content SEO and Sitemap.xml

### ISSUE THREAD

**Issue by ja5ee** [khalwat/seomatic#401]
We have lost entry types in the Content SEO Section of the SEOMatic Plugin. In the content configuration - settings are populated with 8 unique sections all defined by entry types - most are channels with pages being structure.

The result of this is that "content SEO" is not populating and our sitemap is no longer generating.

Here's a screenshot of the SEOMatic Dashboard
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/66383726/166507632-53c75dfe-52c6-43ba-bd32-fc9c73381bdc.png">

Here's a screenshot of the SEOMatic Content SEO Entries
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/66383726/166507764-f8f787de-e6e5-4c4d-b26b-6352f9ac2cb7.png">

And when checking /sitemap.xml
<img width="933" alt="image" src="https://user-images.githubusercontent.com/66383726/166507869-e2719b07-1f55-45b8-bd89-a75adc56732d.png">

### Expected behaviour
This used to be populated. Don't know exactly when it started failing, but doesn't appear that the data is populating.

We have tried uninstalling and re-installing - but get the same results. 

Other plugins include:
Blitz
Navigation
NEO
GDPR Cookie Consent

### Versions
- Plugin version: 3.4.28
- Craft version: 3.7.37

@simb

**Comment by ja5ee** [comment]
Good morning ... any thoughts on what may be at issue here? Thank you.

**Comment by khalwat** [comment]
This is posted on the wrong repository. This is the repository for the deprecated SEOmatic plugin for Craft CMS 2
