### ISSUE TITLE
Pagination for Sitemaps / Sitemap Indexes

### ISSUE THREAD

**Issue by aloco** [khalwat/seomatic#402]
### Is your feature request related to a problem? Please describe.
Hi, we have a large Webshop with around 40K Products. We can´t access the sitemap generated bei SEOMatic for those products, the request ends in a 504. It seems like it was generated successful but the output is too large. It would be very helpful if SEOMatic supports paginated sitemaps. Unfortunately we can´t make all products accessible for crawlers, therefore we need a complete sitemap(s).

Thank you

**Comment by khalwat** [comment]
You are posting on a repository for an old deprecated Craft 2 version of the plugin, which does not generate sitemaps.

**Comment by aloco** [comment]
Sorry!
