### ISSUE TITLE
Sitemap Page loads slowly

### ISSUE THREAD

**Issue by mortscode** [khalwat/seomatic#403]
### Describe the bug
Experiencing an issue where the site map for my "postEntries" (846 entries) is taking a long time to open when I click on the link, and is reaching a full request timeout at times. We add or update 3-4 posts a week to this entry type, so this specific sitemap is rebuilt quite often.

I ran `./craft seomatic/sitemap/generate` recently on the server in hopes to get a fresh start.

Once it loads, the cached version seems to work relatively quickly (i think).

### To reproduce
1. Go to ["my main sitemap"](https://themodernproper.com/sitemaps-1-sitemap.xml)
2. Click on ["sitemaps-1-section-postEntries-1-sitemap.xml"](https://themodernproper.com/sitemaps-1-section-postEntries-1-sitemap.xml)
3. See error message "request timeout (cloudflare)"

### Expected behavior
For the sitemap to load quickly so as to keep google search console happy

### Versions
- Plugin version: 3.4.38
- Craft version: 3.7.55.2

**Comment by khalwat** [comment]
This is posted on the old Craft CMS 2 version of SEOmatic's repository, which is deprecated. Did you mean to post it here?

https://github.com/nystudio107/craft-seomatic/issues
