### ISSUE TITLE
SEO Image Source > render output with overlay image, logo or watermark

### ISSUE THREAD

**Issue by srosenbrand** [khalwat/seomatic#405]
It would be great to have the option to render the global and/or on section level generated SEO image source with a logo or overlay image. I have done some tests with the 'Share Previews Plugin' (https://github.com/alpshq/craft-share-previews/blob/master/README.md), but this plugin behaves unstable and has giving me errors and is unfortunately unreliable. 

In SEOMatic settings ad dropdownfields, I can see something like this:

<img width="1415" alt="image" src="https://github.com/nystudio107/seomatic/assets/5593262/8ca313b7-81a3-4b89-9ebf-cf9c849de85e">

I can't imagine I am the only one who would love this feature...

**Comment by khalwat** [comment]
Are you intentionally posting this issue on this old deprecated Craft 2.x plugin repository?

**Comment by srosenbrand** [comment]
My mistake! Will post in correct repo!

**Comment by khalwat** [comment]
I think you will find an existing Feature Request is there for this

**Comment by srosenbrand** [comment]
Ah check! Then I'll just hope for good things to happen ;-)

**Comment by srosenbrand** [comment]
Couldn't find a similar recent feature request so proposed in correct repo. Thanks for replying!
