### ISSUE TITLE
Algolia search on docs website is returning 404s

### ISSUE THREAD

**Issue by langlers** [khalwat/seomatic#406]
### Describe the bug
Algolia search returning 404s on SEOmatic plugin docs website.

### To reproduce
Steps to reproduce the behaviour:
1. Go to [https://nystudio107.com/docs/seomatic/v4/](https://nystudio107.com/docs/seomatic/v4/)
2. Click on the search box and enter, e.g., "sitemap".
3. See 404 error message [https://nystudio107.com/docs/seomatic/configuring.html#sitemap](https://nystudio107.com/docs/seomatic/configuring.html#sitemap)

### Expected behaviour
Search results.

**Comment by khalwat** [comment]
I think this is a result of the recent Docs restructuring. I think Agolia just needs to re-index it, I'll see if there's a way to kickstart it.

**Comment by khalwat** [comment]
Looks like we just need to wait until it fixes itself:

> It's not possible to manually trigger reindexing for DocSearch.

> DocSearch crawls your site and [reindexes once a day](https://docsearch.algolia.com/docs/crawler/#how-often-will-you-crawl-my-website).

> The DocSearch scraper follows [the recommended atomic-reindexing strategy](https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/in-depth/asynchronicity-and-when-to-wait-for-tasks/#atomic-reindexing). It creates a brand new temporary index to populate the data scraped from your website. When successful, the crawl overwrites the old index defined in your configuration with the key index_name and deletes the temporary index.


https://support.algolia.com/hc/en-us/articles/13314090986513-How-do-I-trigger-a-reindex-with-DocSearch

**Comment by khalwat** [comment]
Apparently, if I login via https://crawler.algolia.com/admin I can force it to re-index

**Comment by khalwat** [comment]
So apparently because the SEOmatic documentation was completely redone, the index had enough changed in it that Algolia would not automatically replace it like it normally does. The old login.algolia.com that I was using does not show any indication of this, nor does it allow me to re-index it. But if I login via crawler.algolia.com I'm able to see the alert that allows me to manually replace the index, as well as manually re-index.
