### ISSUE TITLE
Control spacing before separator

### ISSUE THREAD

**Issue by simonleadbetter** [khalwat/seomatic#409]
For improved a11y, we prefer to use a comma as a separator than the default | pipe character as screen readers will read **vertical line**, but they will ignore punctuation like a comma.

We change the default separator using the separatorChar config override; however, this leaves a space between the title and the comma. It would be great if the value of the separator honoured spacing, i.e: `', ' ` rather than it be programatically added.

**Comment by khalwat** [comment]
I think you're posting this in the wrong place, this is the old, defunct free SEOmatic plugin for Craft 2.x

**Comment by simonleadbetter** [comment]
You are right. Sorry about that.
