### ISSUE TITLE
Google Analytics not working

### ISSUE THREAD

**Issue by ajaffarali** [khalwat/seomatic#41]
I've enabled Google Analytics by adding my ID and enabled page tracking but its not loading the tracking code

**Comment by khalwat** [comment]
Are you using a custom template?

**Comment by ajaffarali** [comment]
I'm not using a custom template defined in SEOMatic Template Meta if that's what you're asking.

**Comment by khalwat** [comment]
So this is what is in the `_seo_meta.twig` template:

```
{% if not craft.config.devMode and not craft.request.isLivePreview %}{{ craft.seomatic.renderGoogleAnalytics() |raw }}{% endif %}
```

So it doesn't render Google Analytics if `devMode` is on, and it doesn't render Google Analytics in a Live Preview.

Then the template that ends up getting rendered is the `_googleAnalytics.twig` template, which does this:

```
{% if seomaticHelper.ownerGoogleAnalyticsUID %}
<script>
```

So assuming you are not overriding the default template (which if I recall correctly, you were), it will render Google Analytics as long as `devMode` isn't on, it isn't a Live Preview, and you entered something for your Google AnalyticsUID.
