### ISSUE TITLE
Facebook Tracking Pixel

### ISSUE THREAD

**Issue by lindseydiloreto** [khalwat/seomatic#42]
Would be cool if we could also add our Facebook Tracking Pixel code (just like you did with Google Analytics).

The GA thing is pretty awesome btw, thanks!

**Comment by khalwat** [comment]
I fear the kitchensink-ization of SEOmatic.  It's a slippery slope for sure. :)

There are a few things that I want to make sure I get done first, but I'll keep this open for consideration.  If anyone else has opinions on it, feel free to chime in.

**Comment by jeremiahcalvino** [comment]
I think using something Google Tag Manager is usually a better option for things like Tracking Pixels. Maybe having one field for a Tag Manager Pixel could make sense and then everything else could be managed through that.

**Comment by khalwat** [comment]
The problem is that Tag Manager isn't something that's rendered in `<head>` -- Google wants you to put it inside your `<body>` tag somewhere, and SEOmatic doesn't occupy that space at all.
