### ISSUE TITLE
Query Strings added to canonical (and dcterms.Identifier, og:url) if present

### ISSUE THREAD

**Issue by masugadesign** [khalwat/seomatic#43]
I'm using SEOMatic 1.0.11 (older, yes) but I tested this on Craft's own site (see pic) and it did the same thing. If I add a query string to any page, it shows in the canonical meta tag. I think that should be stripped.

![pasted_image_at_2016_03_11_10_20_pm](https://cloud.githubusercontent.com/assets/45638/13720505/ac843d08-e7d8-11e5-82e6-d15d7334b7ef.png)

**Comment by khalwat** [comment]
Pushed a fix to `develop`:

https://github.com/nystudio107/seomatic/tree/develop
