### ISSUE TITLE
FR: Make meta content max lengths configurable

### ISSUE THREAD

**Issue by michaelrog** [khalwat/seomatic#45]
The developer should be able to specify a custom truncation threshold for meta title, description, and keyword content. Notwithstanding conventional wisdom regarding the optimum length limits for this content, there are cases where it would be legitimate for the developer to tweak how/if various recommendations are enforced.) (In general, a plugin should not mutate content in ways that are out-of-reach of the developer to control.)

**Comment by khalwat** [comment]
I'm probably not going to let you set custom lengths, but I probably will let you set whether or not it should truncate the description & keywords (there's already a setting for turning off the truncation of the title tags.

Keep in mind that other than for the title tag, we're not talking about information that is generally visible to the user.  There is also a very good reason why SEOmatic by default truncates as it does; search engines will truncate for you anyway.

At least this way, you get to see the truncated version, and have the ability to edit it down to the recommended lengths.  I'm not making the rules, but SEOmatic enforcing them I think is a positive thing.

**Comment by michaelrog** [comment]
**A config to disable truncation of title/description/keywords is exactly what I'm looking for in this case.** However, currently, the config that "disables" truncation of the title doesn't _actually_ disable truncation of the title; It just sets a higher truncation threshold. If the config actually allowed me to _disable_ truncation altogether, that'd be super.

I don't mind sensible (even opinionated) defaults. However, I don't think that SEOmatic should necessarily _"enforce"_ your understanding of the "rules" — especially since the "rules" are subjective and constantly shifting.

For example, while search engines do frequently truncate the amount of the description that's visible on a SERP, it isn't always so (c.f. https://moz.com/blog/i-cant-drive-155-meta-descriptions-in-2015). I've seen 300+ character length SERP snippets, depending on the context. And moreover, search engines may use the content of the description to decide whether it would be relevant to display a snippet in the first place. Even if the SERP doesn't ultimately _display_ the entire description, the fact that the search engine _read_ the entire description may be useful.

Trustable tools serve at the pleasure of the developer. It's great that SEOmatic helps me hit as many best practices as possible, with as little effort as possible, and tries to keep me from shooting myself in the foot. Ultimately, I don't think it's disruptive to request that content-mutating features should be optional. If I conscientiously decide that a 175-character-long meta description is okay, it seems rather bullheaded for SEOmatic to claim moral high-ground and fight me on it.

**Comment by khalwat** [comment]
This is done in 1.1.10:

https://github.com/nystudio107/seomatic
