### ISSUE TITLE
FR: Make meta `generator` tag content editable

### ISSUE THREAD

**Issue by michaelrog** [khalwat/seomatic#47]
If SEOmatic is to render a `generator` meta tag, its value should be editable/overridable in the template just like other meta tag values.

**Comment by khalwat** [comment]
You can use your own template if you don't like the `generator` meta tag (which is completely benign).

**Comment by michaelrog** [comment]
Using a custom template aggravates the upgrade path. What's the advantage of a hardcoded value over making it editable as part of the `seomaticMeta` array?
