### ISSUE TITLE
Override 'locale'?

### ISSUE THREAD

**Issue by eheiser** [khalwat/seomatic#48]
More a question than an issue: right now the locale for the Facebook OpenGraph seems to be set by Craft's locale. Issue is that I often have my CP set in English (locale = en_us) but the site itself is in another language (mosly dutch or french).
Is there any place in the code where we can override this?

BTW, this is a kick-ass plugin, cannot believe this is non-commercial... is there a donate button somewhere?

**Comment by khalwat** [comment]
No donate button (yet!).  Let me see if I'm setting it incorrectly; perhaps it should not be setting it to the locale, but rather to the language.

**Comment by khalwat** [comment]
So the language for Facebook is set by craft.language... which should be set to whatever the current locale is for the website.  Are you not seeing this happen?  Is your website a multi-locale website?

In any event, you can change the og:locale via Twig, see the "Dynamic Twig Meta" section of the documentation.

**Comment by eheiser** [comment]
Cheers mate!
