### ISSUE TITLE
Google Analytics UA Code On Pixel & Tonic

### ISSUE THREAD

**Issue by ghost** [khalwat/seomatic#49]
We are trying to add our UA code into a Seomatic plugin on Pixel & Tonic (see attached image). Currently the code is not communicating with our GA account or appearing on the source code of the website. Thanks for your help!

<img width="1266" alt="screen shot 2016-03-22 at 2 09 00 pm" src="https://cloud.githubusercontent.com/assets/6945378/13964886/f9041de2-f039-11e5-8300-6e89f7f0d683.png">

**Comment by khalwat** [comment]
The code will only appear if `devMode` is not on (Analytics are not meant for dev).

**Comment by khalwat** [comment]
I checked your live website, and it is running with `devMode` on, that's why the Analytics are not appearing.  It's probably not the best idea to have `devMode` on for a live site:

https://craftcms.com/support/dev-mode

**Comment by ghost** [comment]
Thanks! I'll let my client know.
