### ISSUE TITLE
Inquiry about '...' treatment

### ISSUE THREAD

**Issue by sg-modlab** [khalwat/seomatic#5]
I have two related but likely different questions/issues with treatment of `...`

1) I have a blog title `Is if Possible to ... ?`. Here's how it is rendered in the title which is not so great. Any way around this outside of changing title?

```
<title>Is it Possible to &acirc;�&brvbar; ? | MOD-Lab</title>

```

2) I am noticing also the descriptions seem to be getting truncated. Is this expected and if so how does this behave with Twitter Cards and Facebook posts?

```
<meta name="description" content="As a web developer and technologist the question of &quot;Is it possible?&quot; is an incredibly common one. Posed by clients, partners, and/or team members, it is shared&acirc;�&brvbar;" />
```

**Comment by sg-modlab** [comment]
Regarding truncation of description, it seems to truncate around 160 characters is that correct?

**Comment by khalwat** [comment]
Regarding the truncation, from the README.md:

> Some of the `seomaticMeta` variables have character limitations on them, because search engines want to see only the most relevant, succinct information, and will truncate them during processing:
> - **seomaticMeta.seoTitle** - 70 characters
> - **seomaticMeta.seoDescription** - 160 characters
> - **seomaticMeta.seoKeywords** - 200 characters
> 
> SEOmatic will automatically truncate these variables for you when you set them, so you don't have to worry about the length.  It intelligently truncates them on whole-word boundaries, so nothing will get cut off.

**Comment by sg-modlab** [comment]
@khalwat right on ... missed that during first couple reads.

What about what I am seeing in my title when I have `...` in them. Edge case I'm sure by itself, but wondering what other characters may be impacted as well . Seeing the following in browser is not good.

![ab](https://cloud.githubusercontent.com/assets/529067/12045016/8c102238-ae69-11e5-8e64-ca973584fdac.png)

**Comment by khalwat** [comment]
Regarding the character encoding you mentioned, I just pushed a change that might take care of it for you.  I think it was overzealously converting characters to entities:

https://github.com/khalwat/seomatic

**Comment by sg-modlab** [comment]
Just tested, no change.

**Comment by khalwat** [comment]
hmmmm.  I'm not seeing it:

![safariscreensnapz003](https://cloud.githubusercontent.com/assets/7570798/12045131/59124fd0-ae6b-11e5-89a1-309009ffb95c.png)

Can you tell me what your `default_charset` is set to in `php.ini`?  Are you sure there are no extraneous characters in that blog title?

**Comment by sg-modlab** [comment]
Looks like it did fix it. Did not see it right away .. cache I presume.
Thanks.

On Tue, Dec 29, 2015 at 8:33 PM, khalwat notifications@github.com wrote:

> hmmmm. I'm not seeing:
> 
> [image: safariscreensnapz003]
> https://cloud.githubusercontent.com/assets/7570798/12045131/59124fd0-ae6b-11e5-89a1-309009ffb95c.png
> 
> Can you tell me what your default_charset is set to in php.ini?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/khalwat/seomatic/issues/5#issuecomment-167914865.

## 

seth giammanco
seth@mod-lab.com
ph 718.858.1066

minds on design lab
www.mod-lab.com
Subscribe to our Mailing List
https://confirmsubscription.com/h/y/12431274F3870FEA

**Comment by khalwat** [comment]
Great, thanks for using SEOmatic!  I appreciate the feedback!
