### ISSUE TITLE
Focus Keywords and Score Preview

### ISSUE THREAD

**Issue by ajaffarali** [khalwat/seomatic#50]
I'm coming from Wordpress using the Yoast SEO plugin which had a great feature of taking the keywords for your post, analysing them and giving a score/suggestions on what could be improved to get better SEO results. 

Would be awesome if something like this is planned for SEOMatic.

**Comment by khalwat** [comment]
How would you envision it working?

I sort of view this as the domain of the various SEO analysis tools (WooRank, MozRank, etc.)

**Comment by ajaffarali** [comment]
Here's a screenshot of what I'm used to and like. On top, you get a preview on how Google is showing the post, followed by metrics on what could be used to make it more SEO friendly.

<img width="899" alt="screen shot 2016-03-26 at 11 00 28 pm" src="https://cloud.githubusercontent.com/assets/11093375/14061917/d0ce366c-f3a6-11e5-9188-5ca5656af48c.png">

**Comment by khalwat** [comment]
So if you click on _Preview Meta Display_ SEOmatic will show you what it will look like in Google, Facebook, and Twitter.

As for the content analysis, again, I feel like that more the domain of the various SEO evaluation sites and services.

**Comment by hisnameisjimmy** [comment]
I'm gonna open this back up, as I feel like you guys are great developers, and I would love to see this as part of your plugin.

The value of Yoast's keyword focus and content analysis is that it steers behavior of authors. When you have to click a button to see a 'what this will look like in X', nobody does it. However, if you can see a red, yellow or green light, as you type, those simple indicators have you pause, see what changed, and direct behavior accordingly. This is what I was looking for in my previous plea: https://github.com/nystudio107/seomatic/issues/216

We may want human behavior to be different, but the reality is this: simple affordances have a powerful ability to steer people in the right direction. SEO is insanely important, and a lot of people who are writing oriented struggle with the thinking. We can help that.

Some of this is done in this plugin: https://github.com/ethercreative/seo

But development seems to be a bit more sporadic. Again, I love what you guys do at nystudio107, and have utilized a lot of your thinking. I'd love your brains to break this one down a bit more.
