### ISSUE TITLE
Simple title for entry not appearing

### ISSUE THREAD

**Issue by alanski66** [khalwat/seomatic#51]
So have put " {% hook 'seomaticRender' %}" in my header template.
But a simple entry in a new section just gets the global site title set in main config. Is this intended default behaviour?

Unfortunately I am using lots of includes and extends and cant target some of my included files....either

**Comment by khalwat** [comment]
`{% hook 'seomaticRender' %}` needs to go in your main `layout.twig` that other templates `extends` 

Beyond that, I'm not sure I understand your question?
