### ISSUE TITLE
Retain locale once selected

### ISSUE THREAD

**Issue by sjelfull** [khalwat/seomatic#52]
If you select a locale, and go to another section, it currently defaults back to US English (it's not even default in Craft).

**Comment by khalwat** [comment]
Select a locale where, exactly?

**Comment by sjelfull** [comment]
Here, in the sidebar of SEOMatic.

![image](https://cloud.githubusercontent.com/assets/10508/14178062/5f0e8df4-f759-11e5-98de-713eb73d4b5d.png)

If I select another section here:

![image](https://cloud.githubusercontent.com/assets/10508/14178052/54f2eb4e-f759-11e5-9486-013870157c86.png)

.. it defaults back to US English:

![image](https://cloud.githubusercontent.com/assets/10508/14178102/7569dc66-f759-11e5-9e86-55bda86b634a.png)

**Comment by khalwat** [comment]
So it actually does this based on URL.  So it doesn't "switch back" to the other language, clicking on it in the AdminCP actually inherently selects that language.

```
        'seomatic/site'                                         => array('action' => 'seomatic/editSiteMeta'),
        'seomatic/site/(?P<locale>[-\w\.*]+)'                   => array('action' => 'seomatic/editSiteMeta'),
        'seomatic/identity'                                     => array('action' => 'seomatic/editIdentity'),
        'seomatic/identity/(?P<locale>[-\w\.*]+)'               => array('action' => 'seomatic/editIdentity'),
        'seomatic/social'                                       => array('action' => 'seomatic/editSocial'),
        'seomatic/social/(?P<locale>[-\w\.*]+)'                 => array('action' => 'seomatic/editSocial'),
        'seomatic/creator'                                      => array('action' => 'seomatic/editCreator'),
        'seomatic/creator/(?P<locale>[-\w\.*]+)'                => array('action' => 'seomatic/editCreator'),
```

I'm open to the idea of a better way to handle it?

**Comment by sjelfull** [comment]
After I switch locale to Norwegian Bokmål, I think these:

![image](https://cloud.githubusercontent.com/assets/10508/14459800/66a15f46-00ba-11e6-81cb-919fe32353d1.png)

which has url's like http://craft.dev/manage/seomatic/identity should be http://craft.dev/manage/seomatic/identity/nb

**Comment by khalwat** [comment]
(finally) did this... `[Improved] SEOmatic now remembers the selected locale in its tabbed settings`

It's checked into `develop`:

https://github.com/nystudio107/seomatic/tree/develop
