### ISSUE TITLE
PHP warning when saving robots.txt with certain Twig tags

### ISSUE THREAD

**Issue by johndwells** [khalwat/seomatic#53]
I'm trying to set up robots.txt file to send rules contingent upon the environment, so I've tried adding this:

```
{% if craft.config.environment == 'production' %}
User-agent: *
Disallow:
{% else %}
User-agent: *
Disallow: /
{% endif %}
```

Where `environment` is a custom configuration variable we have set within `craft/config/general.php`.

When I paste this in and hit save, I'm greeted with this PHP warning:

`md5() expects parameter 1 to be string, array given`

I then continue to receive this whenever I attempt to access the SEO Site Meta tag in the CMS, or when I try to hit `/robots.txt` on the front end (of course the response comes across as plain text because of the extension).

For what it's worth, it's not just a conditional twig block that causes this error - I can also get it thrown by simply placing a single variable tag, e.g. `{{ siteUrl }}` or even an environment variable, e.g. `{basePath}`.

**Comment by khalwat** [comment]
That's pretty strange.  Do you have a backtrace you can paste in here?

**Comment by johndwells** [comment]
Sure thing - I'll send one to you privately since it reveals client info.

**Comment by khalwat** [comment]
So something clearly isn't right; are you saying the default robots.txt file (which includes `{{ siteUrl }}` in the code does't render?

```
# robots.txt for {{ siteUrl }}

Sitemap: {{ siteUrl }}sitemap.xml

# Don't allow web crawlers to index Craft

User-agent: *
Disallow: /craft/
```

The above is the default robots.txt, and it is rendering fine here.

**Comment by ademers** [comment]
I also had issues with custom env vars. However, I was successful with the code below as documented at: https://craftcms.com/docs/templating/craft.config

```
{% if craft.config.devMode %}
# Don't allow web crawlers to index site
User-agent: *
Disallow: /
{% else %}
# Don't allow web crawlers to index Craft
User-agent: *
Disallow: /craft/
{% endif %}
```

**Comment by khalwat** [comment]
This is fixed in `develop` -- I'll roll it into an official release soonish, I have a few other things to do first.

https://github.com/nystudio107/seomatic/tree/develop
