### ISSUE TITLE
Environment Variables not being parsed

### ISSUE THREAD

**Issue by johndwells** [khalwat/seomatic#54]
I've tried placing an environment variable same as the example is given in the CP:

`This is my {baseUrl}`

And to the best of my ability I'm confident that `baseUrl` has been properly set as an environmentVariables within my `craft/config/general.php` file.  But on the front end this is rendered as-is, without being parsed.

**Comment by johndwells** [comment]
Just a note that the content also appears un-parsed when I "Preview robots.txt" from within the CP.

**Comment by khalwat** [comment]
Where are you putting this variable, exactly?  You say you are placing `{baseUrl}` but you don't say where you are putting it?

**Comment by johndwells** [comment]
Good grief, sorry about the vagueness of this issue - in my mind I was just continuing our conversation from Slack.

This has to do with the robots.txt file - so when I place `{baseUrl}` inside the textarea of the Robots.txt setting, it comes out the other end unparsed.

**Comment by khalwat** [comment]
yes, `{baseUrl}` is an environmental variable, and so it won't be parsed in the robots.txt template.  Treat everything in the robots.txt template as an actual front-end Twig template.  So you'd need to do something like `{{ craft.config.environmentVariables.baseUrl }}`
