### ISSUE TITLE
Google Analytics code not being output

### ISSUE THREAD

**Issue by MattWilcox** [khalwat/seomatic#57]
Hi,

I have a Google Analytics code entered into the SEOmatic back-end, but the front end is only spitting out an HTML comment:

`

`

**Comment by MattWilcox** [comment]
Just found out from an old closed issue that this is by design when in dev mode - maybe change the HTML Comment to explain as much when it is in dev mode?

**Comment by khalwat** [comment]
That's a good idea, I'll do that!

**Comment by khalwat** [comment]
Added it to the `develop` branch:

```
 <!-- Google Analytics -->

<!-- Google Analytics script is NOT included in LivePreview or if devMode is on -->
<!-- END SEOmatic rendered SEO Meta -->
```
