### ISSUE TITLE
Templates Meta

### ISSUE THREAD

**Issue by pascallammers** [khalwat/seomatic#59]
Hey,

I created an Template Meta for my subsite and put in different content for like SEO Title or SEO Description but it only shows the data specified in the SEO Site Meta Tab.

I put {% hook 'seomaticRender' %} in my "_layout.html" which is the base file of all subsites.

Could anybody help me out?

Thanks in advance!

**Comment by khalwat** [comment]
Make sure the paths you put into the template metas match the actual template paths.

**Comment by pascallammers** [comment]
Hey khalwat!
Thanks for your feedback! I checked the settings but nothing changed :(

I attached 3 images where my problem shows up 
![bildschirmfoto 2016-04-12 um 09 40 01](https://cloud.githubusercontent.com/assets/4232679/14453103/0e87275e-0093-11e6-95a7-de8679dfddcb.png)
![bildschirmfoto 2016-04-12 um 09 42 25](https://cloud.githubusercontent.com/assets/4232679/14453102/0e7f02ea-0093-11e6-973c-4736a6c6ec45.png)
![bildschirmfoto 2016-04-12 um 09 42 34](https://cloud.githubusercontent.com/assets/4232679/14453104/0eb9a88c-0093-11e6-9fc8-285f34447b13.png)

I hope anybody can help me with this issue :+1:

**Comment by khalwat** [comment]
Template path should be to the actual template, so it should be:

`agentur/index`

**Comment by pascallammers** [comment]
Thanks for your support! It´s working now! :+1:
