### ISSUE TITLE
Dynamic Meta Data

### ISSUE THREAD

**Issue by Macxim** [khalwat/seomatic#61]
Hi, first of all, thank you for this great plugin which looks very powerful and thorough.

I have read the documentation carefully but am not sure I fully understand the purpose of Template Meta. What is the point of filling in the fields with static data? You don't want a static page title but a unique one for each entry.

Example of what I have in mind:

![screen shot 2016-04-14 at 00 26 25](https://cloud.githubusercontent.com/assets/1909957/14511525/49973f78-01d8-11e6-9ffc-97aba5638b2e.png)

I'm sure I'm just missing something here.

**Comment by khalwat** [comment]
Not all pages have entries on them.  You might use Template Meta for Singles, for instance.

What you want is to use the SEOmatic FieldType

**Comment by Macxim** [comment]
I see.
Thanks, it makes sense.
