### ISSUE TITLE
Upgrading from 1.1.11 to 1.1.12 notification doesn't go away

### ISSUE THREAD

**Issue by seb-thomas** [khalwat/seomatic#62]
Hey, I've copied the contents of the newly downloaded SEOmatic zip to my SEOmatic directory in plugins, and refreshed the plugins page but I still get a notification to download 1.1.12.

![image](https://cloud.githubusercontent.com/assets/629571/14561527/c9f9e65c-030e-11e6-864f-255688feb2e7.png)

![image](https://cloud.githubusercontent.com/assets/629571/14561562/038f4b3c-030f-11e6-9ac4-b56d3c11ad7b.png)

![image](https://cloud.githubusercontent.com/assets/629571/14561566/08e2ddf6-030f-11e6-9598-22ae9bcfb914.png)

**Comment by seb-thomas** [comment]
PEBKAC :-1:

**Comment by khalwat** [comment]
Glad I could help! :)
