### ISSUE TITLE
OG and Twitter descriptions not stripped of HTML or truncated

### ISSUE THREAD

**Issue by jamiepittock** [khalwat/seomatic#63]
Hi,

I'm noticing that the general meta description tag is stripped of HTML and truncated but my OG and Twitter description tags aren't. See:

https://gist.github.com/jamiepittock/af458ab8e1b38ecffe9fc36d49d614c4

Is this a bug or intended?

Cheers

**Comment by khalwat** [comment]
I'm unable to replicate this.  I tried by putting `<p>` tags in my SEO Site Description, and it rendered it without `<p>` tags in my `og:` and `twitter:` meta tags.

Can you give me some more information on how to replicate this?  In the code, it looks at every key/value pair, and does `strip_tags` on each value, so I'm not sure how this could be slipping through...?

**Comment by khalwat** [comment]
How is the information in the SEO Description getting there?  Via FieldType?  Template Meta?  Twig code?

**Comment by hollandzone** [comment]
sd

**Comment by justkeen** [comment]
Hi,

I have an issue that the og and twitter description are not truncated, but the html is stripped. 

In my particular case, Im using it via FieldType and it does not truncate it either for og or twitter.  Than Ive tried using Twig code and added seomaticMeta.seoDescription to the og:description and twitter:description, but still it does not truncate it.

**Comment by khalwat** [comment]
Right, SEOmatic does not truncate those fields.  The only fields it truncates are for the seoTitle, seoDescription, and seoKeywords.

If you want to manually truncate other fields, you can.  SEOmatic has a `truncateStringOnWord()` Twig filter you can use:

https://github.com/nystudio107/seomatic/wiki/12.-Utility-Filters-&-Functions

**Comment by justkeen** [comment]
I was under the impression that it should truncate those fields as well, my bad. The Twig filter works like a charm. Thx for the plugin, a real time saver.

**Comment by khalwat** [comment]
It doesn't truncate them because there's no guidelines from Facebook/Twitter on what the length max is, or at least that I'm aware of.

**Comment by jamiepittock** [comment]
Thanks for clarifying about the truncating.

Here's how to replicate the `twitter:description` and `og:description` tags not being stripped of HTML. 

This is code taken directly from the SEOmatic wiki:

```
{% set seomaticMeta = { 
    seoTitle: "Some Title",
    seoDescription: entry.summary,
    seoKeywords: "Some,Key,Words",
    seoImage: seomaticMeta.seoImage,
    canonicalUrl: entry.url,
    twitter: { 
        card: seomaticMeta.twitter.card,
        site: seomaticMeta.twitter.site,
        creator: seomaticMeta.twitter.creator,
        title: "Some Title",
        description: entry.summary,
        image: seomaticMeta.twitter.image
    },
    og: { 
        type: seomaticMeta.og.type,
        locale: seomaticMeta.og.locale,
        url: entry.url,
        title: "Some Title",
        description: entry.summary,
        image: seomaticMeta.og.image,
        site_name: seomaticMeta.og.site_name,
        see_also: seomaticMeta.og.see_also
    }
} %}
```

`entry.summary` is a Rich Text field.

Like I said originally, the meta description tag content is stripped of HTML but the twitter and og descriptions aren't. All are using the same field as content.

Let me know if you need anything else.

**Comment by jamiepittock** [comment]
Hi Andrew, you closed this but was the issue with HTML not being stripped resolved? Maybe I've misunderstood.

**Comment by khalwat** [comment]
I re-opened it.  I need more information from you (see above).

**Comment by jamiepittock** [comment]
What extra information do you need? I've tried to show you how to reproduce and showed the Twig code. Let me know what else you need.

**Comment by khalwat** [comment]
Okay so what you really want is something like this:

	{% set seomaticMeta = {
	    seoTitle: "Some Title",
	    seoDescription: entry.someRichText.getParsedContent(),
	    seoKeywords: "Some,Key,Words",
	    seoImage: seomaticMeta.seoImage,
	    canonicalUrl: entry.url,
	    twitter: {
	        card: seomaticMeta.twitter.card,
	        site: seomaticMeta.twitter.site,
	        creator: seomaticMeta.twitter.creator,
	        title: "Some Title",
	        description: entry.someRichText.getParsedContent(),
	        image: seomaticMeta.twitter.image
	    },
	    og: {
	        type: seomaticMeta.og.type,
	        locale: seomaticMeta.og.locale,
	        url: entry.url,
	        title: "Some Title",
	        description: entry.someRichText.getParsedContent(),
	        image: seomaticMeta.og.image,
	        site_name: seomaticMeta.og.site_name,
	        see_also: seomaticMeta.og.see_also
	    }
	} %}

If you just set it to `entry.someRichText` you're actually setting it to be a `\RichTextData` object.  I'm not sure if this will solve it in your case, but I did a test with the above code, and I dumped the raw array on the front-end (the top half of the screenshot), and you can see the tags in it.  Then in the meta, the tags are stripped out.  This is using SEOmatic 1.1.16 (a release you don't have yet), but it should work for you as well:

<img width="1018" alt="safariscreensnapz160" src="https://cloud.githubusercontent.com/assets/7570798/14871967/86d94f24-0cb5-11e6-9c6b-f45e77874e80.png">

**Comment by khalwat** [comment]
Okay so what you really want is something like this:

```
{% set seomaticMeta = {
    seoTitle: "Some Title",
    seoDescription: entry.someRichText.getParsedContent(),
    seoKeywords: "Some,Key,Words",
    seoImage: seomaticMeta.seoImage,
    canonicalUrl: entry.url,
    twitter: {
        card: seomaticMeta.twitter.card,
        site: seomaticMeta.twitter.site,
        creator: seomaticMeta.twitter.creator,
        title: "Some Title",
        description: entry.someRichText.getParsedContent(),
        image: seomaticMeta.twitter.image
    },
    og: {
        type: seomaticMeta.og.type,
        locale: seomaticMeta.og.locale,
        url: entry.url,
        title: "Some Title",
        description: entry.someRichText.getParsedContent(),
        image: seomaticMeta.og.image,
        site_name: seomaticMeta.og.site_name,
        see_also: seomaticMeta.og.see_also
    }
} %}
```

If you just set it to `entry.someRichText` you're actually setting it to be a `\RichTextData` object.  I'm not sure if this will solve it in your case, but I did a test with the above code, and I dumped the raw array on the front-end (the top half of the screenshot), and you can see the tags in it.  Then in the meta, the tags are stripped out.  This is using SEOmatic 1.1.16 (a release you don't have yet), but it should work for you as well:

<img width="1018" alt="safariscreensnapz161" src="https://cloud.githubusercontent.com/assets/7570798/14872374/a976e970-0cb9-11e6-8f09-fbecd04d2031.png">

**Comment by khalwat** [comment]
So it's working as expected in my case here.  What version of SEOmatic are you using?  Where in your Twig template are you putting that `{% set seomaticMeta = {` statement?

**Comment by jamiepittock** [comment]
Ok thanks for your help. I think I'll just strip the tags myself and leave it at that.

**Comment by khalwat** [comment]
Okay.  I'm really not sure what's going on, because it passes the entire array that it's using into a function that sanitizes it, and strips the tags:

/\* --------------------------------------------------------------------------------
    Sanitize the passed in array recursively
-------------------------------------------------------------------------------- */

```
public function sanitizeArray(&$theArray)
{
    foreach ($theArray as $key => &$value)
    {
        if (is_string($value))
        {
            $value = craft()->config->parseEnvironmentString($value);
            $value = strip_tags($value);
            if ($key === 'email')
                $value = $this->encodeEmailAddress($value);
            elseif ($key === 'url')
                $value = $this->getFullyQualifiedUrl($value);
            else
                $value = htmlspecialchars($value, ENT_COMPAT | ENT_HTML401, 'UTF-8', false);
            $theArray[$key] = $value;
        }
        else
        {
            if (is_array($value))
                $this->sanitizeArray($value);
        }
    }
} /* -- sanitizeArray */
```

So it's hard for me to understand how it could strip them in one place, but not in another.

**Comment by jamiepittock** [comment]
It looks like the Rich Text field value is an object not an array so it's not being sanitised as part of the function you posted above. 

When the same field is used for the `seoDescription`, the object is turned into a string as part of the truncating which means that one does get sanitised.

Because OG and Twitter descriptions aren't truncated they are still objects when you attempt to sanitise them.

**Comment by khalwat** [comment]
ahhhhh, that makes sense.  Change it to: `entry.someRichText.getParsedContent()` ?

**Comment by jamiepittock** [comment]
Yeah that works but it's still a bit awkward that it works differently for the `seoDescription`. If you could handle it 'magically' I would within SEOmatic's internals and just allow users to set the value and not worry about what type of field it is.

**Comment by jamiepittock** [comment]
Anyway, at least I know I'm not going mad now. Thanks for you patience!

**Comment by khalwat** [comment]
I agree with you, I checked in a fix that should "automagically" convert any objects passed in into their string equivalent. It's checked into `develop` now:

https://github.com/nystudio107/seomatic/tree/develop
