### ISSUE TITLE
Quotes in entry title turn into &quot; in title tag

### ISSUE THREAD

**Issue by icopp** [khalwat/seomatic#64]
Looks like a bug in how SEOmatic is generating the HTML tags.

For an example: I name an entry `Reviews of New Book "Some Book Title Here"`. In the final page, the output title tag is `<title>Reviews of New Book &quot;Some Book Title Here&quot;</title>`, which doesn't render properly in browsers.

**Comment by khalwat** [comment]
What web browser isn't rendering this properly?

Chrome, FireFox, and Safari all seem to render it properly here?

**Comment by icopp** [comment]
Sorry - actually, I was going off the wrong info from somebody else there.

It shows up fine in browsers directly... the problem is when you do a social share with it. Sites like Facebook pick up on the `&quot;`, escape it, and drop that into the shared title, so that you end up with `Reviews of New Book &quot;Some Book Title Here&quot;` instead of `Reviews of New Book "Some Book Title Here"` showing up in a Facebook feed or on Twitter.

Hopefully that makes more sense?

**Comment by khalwat** [comment]
Good find!  The Facebook/Twitter attributes were indeed being double-encoded!  I've pushed a fix to the `develop` branch if you need it now:

https://github.com/nystudio107/seomatic/tree/develop

Otherwise it'll be rolled into an upcoming release whenever I get a few more things done with it.
