### ISSUE TITLE
Iconv issue

### ISSUE THREAD

**Issue by dsg-rob** [khalwat/seomatic#65]
Hello - 

I'm getting this error only on entries using the SEOmatic Meta Field Type:

`Fatal error: Call to undefined function Craft\iconv() in /srv/www/html/craft/plugins/seomatic/services/SeomaticService.php on line 2345`

Any help would be appreciated!

**Comment by dsg-rob** [comment]
Turns out I have a buggy version of iconv installed on my server. My bad!

**Comment by khalwat** [comment]
Glad I could help! :)
