### ISSUE TITLE
Open Graph and Twitter meta tags outputted even without any social media accounts saved

### ISSUE THREAD

**Issue by jamiepittock** [khalwat/seomatic#66]
SEOmatic 1.1.15

A fresh install of Craft and SEOmatic. No social media accounts have been added to SEOmatic but these tags are being outputted in my templates. 

```
<!-- Facebook OpenGraph -->

<meta property="og:type" content="website" />
<meta property="og:locale" content="en_gb" />
<meta property="og:url" content="http://craft-latest.dev/news/2016/we-just-installed-craft" />
<meta property="og:title" content="Some Title | Craft Latest" />
<meta property="og:description" content="<p>Craft is the CMS that’s powering Craft-latest.dev. It’s  beautiful, powerful, flexible, and easy-to-use, and it’s made by Pixel &amp; Tonic. We can’t wait to dive in and see what it’s capable of!</p><!--pagebreak--><p>This is even more captivating content, which you couldn’t see on the News index page because it was entered after a Page Break, and the News index template only likes to show the content on the first page.</p><p>Craft: a nice alternative to Word, if you’re making a website.</p>" />
<meta property="og:site_name" content="Craft Latest" />

<!-- Twitter Card -->

<meta property="twitter:title" content="Some Title | Craft Latest" />
<meta property="twitter:description" content="<p>Craft is the CMS that’s powering Craft-latest.dev. It’s beautiful, powerful, flexible, and easy-to-use, and it’s made by Pixel &amp; Tonic. We can’t wait to dive in and see what it’s capable of!</p><!--pagebreak--><p>This is even more captivating content, which you couldn’t see on the News index page because it was entered after a Page Break, and the News index template only likes to show the content on the first page.</p><p>Craft: a nice alternative to Word, if you’re making a website.</p>" />
```

Plus all the boilerplate JSON LD microdata is being outputted which doesn't seem right when I haven't added any information yet.

I'm sure earlier versions only output what has been explicitly inputted?

**Comment by khalwat** [comment]
So the OpenGraph info it can output regardless of whether there is a Facebook Handle or AppId set; so that should be correct.

The Twitter output, however, should not be happening unless there is a Twitter handle set, so something isn't right.

**Comment by khalwat** [comment]
Using SEOmatic 1.1.15, I set the Twitter Handle to nothing, reloaded the page, and it isn't rendering any Twitter card information.

Are you using a custom template for the `{% hook 'seomaticRender' %}` or something?

**Comment by khalwat** [comment]
...or are you perhaps explicitly setting the various `twitter` properties yourself via Twig?

**Comment by jamiepittock** [comment]
Right, yeah I am but I thought it worked differently than this previously. I thought I could explicitly set them in my template but the tags wouldn't be rendered unless a Twitter handle existed in the settings. This way I could set up the templates and it was up to the client whether they added various social accounts.

I must have dreamt it. As you were!

What about the Identity, Website and Place JSON? Should than be rendering even though I've not updated any settings? Maybe some defaults are set when you install SEOmatic.

**Comment by khalwat** [comment]
Basically, SEOmatic assumes that if you set something explicitly via Twig, that you want it rendered.  That includes the Facebook and Twitter data.  This hasn't changed.

As for the Identity/Website/Place JSON-LD, it also always renders them, because there should always be at least enough data to render stub versions of them.
