### ISSUE TITLE
No output using extractTextFromMatrix function

### ISSUE THREAD

**Issue by justkeen** [khalwat/seomatic#67]
Hi as discussed Im trying to use extractTextFromMatrix on my matrix field but no output is given. 

This throws an internal server error (Call to a member function getType() on string):
{{ extractTextFromMatrix(entry.matrixContent.first()) }}

No output with this:
{{ extractTextFromMatrix(entry.matrixContent) }}

<img width="1266" alt="schermafbeelding 2016-04-27 om 00 29 12" src="https://cloud.githubusercontent.com/assets/16735645/14836455/81cda566-0c10-11e6-8821-6fdf80725697.png">

**Comment by khalwat** [comment]
So here's my Matrix block:

<img width="658" alt="safariscreensnapz162" src="https://cloud.githubusercontent.com/assets/7570798/14872423/2f87a4dc-0cba-11e6-9b94-e97f8aad1e0c.png">

When I do this:

```
{{ extractTextFromMatrix(entry.someMatrix) }}
```

This is the output I get:

```
Red green blue They call me mellow yellow
```

...which is what I would expect.  I'm not sure why it isn't working for you, the code is fairly simple.

**Comment by justkeen** [comment]
It appears not to work because I had Dutch as my primary language and my user was also had the Dutch language. Its sorted now.

**Comment by khalwat** [comment]
huh.  Is it a problem with the translation?  Or some flaw in my code?  I'd think it should work regardless of language?

**Comment by justkeen** [comment]
I just tested it on my production site (english default) and dutch secondary language. I have set the description and keywords FieldType to matrix. When I look at Preview SEO Meta tags in the CP, it appears fine for as well English and Dutch. When I look at the front-end it falls back on the Site meta for Dutch (english is fine) except for the title. 

 Im using this twig code.

`{% set matrixText = extractTextFromMatrix(entry.matrixContent) %}

{% set seomaticMeta = seomaticMeta | merge({
        twitter: { 
        card: seomaticMeta.twitter.card,
        site: seomaticMeta.twitter.site,
        creator: seomaticMeta.twitter.creator,
        title: seomaticMeta.twitter.title,
        description: truncateStringOnWord(matrixText,160),
        image: img.getUrl('articleSingleImage')
    },
       og: { 
        type: seomaticMeta.og.type,
        locale: seomaticMeta.og.locale,
        url: seomaticMeta.og.url,
        title: seomaticMeta.og.title,
        description: truncateStringOnWord(matrixText,160),
        image: img.getUrl('articleSingleImage'),
        site_name: seomaticMeta.og.site_name,
        see_also: seomaticMeta.og.see_also
    }

}) %}`

**Comment by khalwat** [comment]
AHA!  It is indeed because of the language, I found this in my code:

```
        foreach ($fields as $field)
        {
            if ($field->fieldType->name == "Plain Text"
                || $field->fieldType->name == "Rich Text"
                || $field->fieldType->name == "Rich Text (Redactor I)"
                )
                {
                    $result .= strip_tags($block[$field->handle]) . " ";
                }
        }
```

...which will fail, because it's looking at the localized name of the field.  I've switched it over to looking at the `type` (which does not change from language to language).  I pushed the fix to the `develop` branch: https://github.com/nystudio107/seomatic/tree/develop

Nice find, thank you!!
