### ISSUE TITLE
No description or keywords when using FieldType with Matrix

### ISSUE THREAD

**Issue by justkeen** [khalwat/seomatic#68]
As u can see im selecting the Matrix field but nothing is displayed and it falls back on the Sitemeta.
<img width="759" alt="schermafbeelding 2016-04-27 om 00 45 30" src="https://cloud.githubusercontent.com/assets/16735645/14836618/bb50e068-0c11-11e6-9b40-9a4db3363116.png">

**Comment by khalwat** [comment]
dup of or at least related to: https://github.com/nystudio107/seomatic/issues/67
