### ISSUE TITLE
Seo Keywords on entry level not configurable per locale

### ISSUE THREAD

**Issue by justkeen** [khalwat/seomatic#70]
I have 2 locale (english and dutch). I notice two things:
1. Whenever I use custom text for my seo keywords and add a new keyword for english, the keyword is added for the dutch locale as well and vice versa. Whenever I delete a keyword in english locale, the one in dutch is removed as well. This appears like a bug to me. 
2. Im not sure if this is a bug (I don't think so) but should it be possible to use a different type per locale ? For example Seo Keyword English using FieldType and Seo Keywords in Dutch using Custom text ? Now its not possible. 

Just something else I noticed: TextRank works great for English but unfortunately not for Dutch.

**Comment by khalwat** [comment]
Do you have the field set to be localizable?  If so, I'd assume you could have different settings per localization.

**Comment by justkeen** [comment]
Alright sorry, my bad! I forgot to set it localizable. Ill close this thread.
