### ISSUE TITLE
Inconsistent display of information

### ISSUE THREAD

**Issue by hannahfishr** [khalwat/seomatic#71]
Having issues with the information showing up inconsistently across results and social media. Also, unsure of how to define information for individual pages. Any help would be greatly appreciated.

The text underneath 'we specialize in helping consumer and technology brands...' is the intended main search result info.

![screen shot 2016-04-29 at 10 38 53 am](https://cloud.githubusercontent.com/assets/18742259/14924301/ac72c4d0-0df6-11e6-8750-d681b701613d.png)
![screen shot 2016-04-29 at 10 39 03 am](https://cloud.githubusercontent.com/assets/18742259/14924302/ac74f3e0-0df6-11e6-9c94-b2c50b2567e3.png)
![screen shot 2016-04-29 at 10 39 15 am](https://cloud.githubusercontent.com/assets/18742259/14924303/ac750362-0df6-11e6-9955-d305023d08fe.png)

![screen shot 2016-04-28 at 3 30 34 pm](https://cloud.githubusercontent.com/assets/18742259/14924252/6ead5d04-0df6-11e6-8cf5-9030d4d530fa.png)
![screen shot 2016-04-28 at 3 32 51 pm](https://cloud.githubusercontent.com/assets/18742259/14924253/6ec17a96-0df6-11e6-8f80-9c9b5395a282.png)
![screen shot 2016-04-28 at 3 33 49 pm](https://cloud.githubusercontent.com/assets/18742259/14924254/6ec8c10c-0df6-11e6-8435-e772d28d4686.png)

**Comment by khalwat** [comment]
Got it figured?

**Comment by hannahfishr** [comment]
no! was going to consult with our developer before I posted again,
realizing this may not be an issue with the tool but maybe on our end so I
didn't want to bug anybody yet!

but any thoughts if you have any would be appreciated.

**Comment by khalwat** [comment]
In general, Google is in charge of what is displayed in their search results page.  You can't force it to display anything, but if it likes your SEO Description (if it's a good one), it'll use it.  Given that you're showing two different results, my guess is that the changes are recent, and Google hasn't finished indexing things yet.

As for the rest of it, it's really up to the developer and how they set things up for you.  Getting in touch with them is a good idea.

Also, this podcast I did on SEO might interest you as well:

http://craftpodcast.com/episodes/episode-8

**Comment by hannahfishr** [comment]
Thank you this is very helpful. This is as i suspected.

We set up the plugin internally without our developer so we will have him
take a look at it.

Thanks again.
