### ISSUE TITLE
Undefined index: organizationOwnerContactPoints

### ISSUE THREAD

**Issue by almeric** [khalwat/seomatic#72]
Just noticed this when turning devmode on. Been using the plugin a while, so my guess is something went wrong during an update?  

Line number:  
`SeomaticService.php(1144)`  

Any tips on how to resolve this issue? I can get to the Seomatic settings page in if devmode is off, but I can't save the `site identity` page for example (same error).

**Comment by almeric** [comment]
Looks like something went wrong between our staging & development environments. A DB import seems to have fixed the issue.  

Nothing to see here, move along :)

**Comment by khalwat** [comment]
Glad I could help!
