### ISSUE TITLE
article:author is supposed to be an array of facebook profiles

### ISSUE THREAD

**Issue by danieltott** [khalwat/seomatic#73]
I'm still figuring this out, but I got an "Object Invalid Value" warning on the facebook sharing debugger for a page I have set as type: article

![image](https://cloud.githubusercontent.com/assets/360261/15044573/7196d2d2-12a3-11e6-826a-fcd63787b13c.png)

Object at URL 'http://www.ottesq.com/articles/fha-certification-and-your-association' of type 'article' is invalid because the given value 'Ott & Associates Co., LPA' for property 'article:author' could not be parsed as type 'profile'.

Apparently the article:author tag is supposed to be [An array of Facebook profile URLs or IDs of the authors for this article](https://developers.facebook.com/docs/reference/opengraph/object-type/article/)

So when it's just set to the site name, it invalidates the `article` type and just sets it as `website`

**Comment by khalwat** [comment]
This is fixed in the `develop` branch:

https://github.com/nystudio107/seomatic/tree/develop

It will be rolled into the next release.
