### ISSUE TITLE
Field layout is broken in newer versions of craft

### ISSUE THREAD

**Issue by danieltott** [khalwat/seomatic#74]
This is on 2.6.2774 (looks fine):
![image](https://cloud.githubusercontent.com/assets/360261/15044842/3aa9dd76-12a5-11e6-9feb-140427e1a8a5.png)

This is on 2.6.2784: 
![image](https://cloud.githubusercontent.com/assets/360261/15044849/4030b76a-12a5-11e6-8c3f-3dc8bff8341b.png)

**Comment by danieltott** [comment]
All of the "Source: [dropdown]" fields are like this:

![image](https://cloud.githubusercontent.com/assets/360261/15044885/700fad56-12a5-11e6-9b92-07e6b54d1595.png)

**Comment by khalwat** [comment]
This is fixed in the version in the `develop` branch:

https://github.com/nystudio107/seomatic/tree/develop

It'll be rolled into the next release.
