### ISSUE TITLE
Bing Webmaster Tools?

### ISSUE THREAD

**Issue by chadcrowell** [khalwat/seomatic#76]
Possible to add a meta tag field for Bing WT site verification? Here is what the tag looks like:

`<meta name="msvalidate.01" content="auth_code_here" />`

and it goes in the head just like GWT.

**Comment by khalwat** [comment]
I added support for this in the `develop` branch:

https://github.com/nystudio107/seomatic/tree/develop

<img width="740" alt="safariscreensnapz184" src="https://cloud.githubusercontent.com/assets/7570798/15124013/2ee3d846-15db-11e6-8ea0-4932c96e1cf0.png">

It will be rolled into the next release of SEOmatic
