### ISSUE TITLE
Use twig syntax in SiteLinks Search Box field

### ISSUE THREAD

**Issue by superwick** [khalwat/seomatic#77]
Would like to be able to dynamically do this for things like multi-region sites (which may have different domains per region). So something like:
`{{ siteUrl }}/search?q={search_term_string}`

**Comment by khalwat** [comment]
Yeah I think that's a good idea

**Comment by khalwat** [comment]
So it actually already does let you use `environmentalVariables` in the fields:

<img width="315" alt="safariscreensnapz187" src="https://cloud.githubusercontent.com/assets/7570798/15158416/b5a1d544-16a4-11e6-828d-45aacb22f4e3.png">
<img width="534" alt="safariscreensnapz188" src="https://cloud.githubusercontent.com/assets/7570798/15158422/ba434a4c-16a4-11e6-91d9-ecb3a29ab4d5.png">

Seems like this should do what you want?  I'm assuming you likely already have per-site `environmentalVariables` ?

**Comment by superwick** [comment]
Ah yes. That works great. Thanks!
