### ISSUE TITLE
Feature Request: Allow settings to be set via a config file

### ISSUE THREAD

**Issue by mildlygeeky** [khalwat/seomatic#78]
For example, I'd like to be able to choose on an environment-by-environment basis when to show Google Analytics (we keep devMode turned off in staging, but with SEOmatic Google Analytics would then be popping up on stage).

As an example, Minimee does this nicely where it looks to see if minimee.php exists in the /config folder, and even uses Craft's own multi-environment checks for setting config options in code rather than in the GUI: https://github.com/johndwells/craft.minimee/blob/master/minimee/config.php

**Comment by khalwat** [comment]
Like this? https://github.com/nystudio107/seomatic/blob/master/config.php#L58
