### ISSUE TITLE
Is SEOMatic outputting Analytics code for Live Previews?

### ISSUE THREAD

**Issue by MattWilcox** [khalwat/seomatic#79]
Can't seem to confirm as Chrome isn't letting me View Source for the frame that's loaded in Live Preview; but we've noticed that on some of our client's sites, in their analytics, we are seeing the CMS trigger url itself being reported; we can only imagine this happening if SEOmatic is spitting out GA code while in the Live Preview mode. This isn't ideal and has lead to confused clients who haven't filtered out the CMS trigger url from their own reports.

Can anyone confirm?

**Comment by khalwat** [comment]
This is the template code used for Google Analytics:

```
{% if not craft.config.devMode and not craft.request.isLivePreview %}{{ craft.seomatic.renderGoogleAnalytics() |raw }}{% else %}<!-- Google Analytics script is NOT included in LivePreview or if devMode is on -->{% endif %}
```

...so it shouldn't be that it is rendering it during Live Preview.  If you figure it out, let me know, but it looks like it's behaving as expected.

**Comment by MattWilcox** [comment]
Developer error; the project in question wasn't running SEOmatic on the live version that had this error. I'd been checking against the dev version that is running SEOmatic, but wasn't pushed up yet.

Sorry.
