### ISSUE TITLE
Compatibility A&M forms

### ISSUE THREAD

**Issue by nealzie** [khalwat/seomatic#8]
Loving the plugin so far, I have a little issue but it might be too specific..

When I have the SEO plugin activated, sending forms through the a&m forms plugin doesn't work anymore, it gives the error. 

<img width="1441" alt="screen shot 2016-01-08 at 19 29 21" src="https://cloud.githubusercontent.com/assets/16614253/12205896/271ce500-b63e-11e5-96dc-a245345d6a55.png">

Although this is terribly specific to another plugin, I think it ties in to a bigger issue that involves date() fields.

**Comment by khalwat** [comment]
huh, that's very strange.  I will install it and have a look.  Have you mentioned this to the author of A&M forms?

**Comment by khalwat** [comment]
So it's AFTER you fill out a front-end form and click the Submit button that you see this error?

**Comment by khalwat** [comment]
Hmmm, I think I see what's going on actually.  I will have a fix for your shortly.

**Comment by khalwat** [comment]
Okay, I checked in a fix for you:

https://github.com/khalwat/seomatic

Let me know how that works for you.

**Comment by nealzie** [comment]
Thanks for the quick help! I reinstalled the plugin with the updated version but the exact same error appears. Since it's a date() related error, I thought I'd paste another error I get with the SEO plugin which also seems to be date() related. I have a structure section with a date field and in 'demoed' I can't view any entries, I just get this:
<img width="1360" alt="screen shot 2016-01-09 at 11 21 57" src="https://cloud.githubusercontent.com/assets/16614253/12215581/69c09fb6-b6c3-11e5-8074-caaee0ba601f.png">
  (http://multiniels.nl/rubicon/evenementen/sharepoint-2016-de-evolutie-van-sharepoint-1)

**Comment by khalwat** [comment]
hmmmm.  Sorry to have you do this, but can you try a change I just checked in (to address the first problem again):

https://github.com/khalwat/seomatic

**Comment by nealzie** [comment]
No apologies needed! I think you broke the entire thing now though.. :D

Missing argument 2 for Craft\TemplatesService::renderObjectTemplate(), called in ......craft/plugins/seomatic/twigextensions/SeomaticTwigExtension.php on line 167 and defined

**Comment by khalwat** [comment]
Ugh.  Okay, I pushed it again.  Hopefully this will do it.  Let me know...

**Comment by khalwat** [comment]
Looks like we got it fixed.  Thanks for your patience.
