### ISSUE TITLE
Entry Meta data not populating after entries imported via FeedMe

### ISSUE THREAD

**Issue by michaelroper** [khalwat/seomatic#81]
I have an existing SEOmatic fieldtype on my news article entry type, and after doing an import of articles via the FeedMe plugin, the Entry Meta SEO Title is not updated to reflect the Title field data (not sure about other seo fields) until I go in and re-save an article.

I also tried your suggestion of editing and re-saving the section, but that didn't seem to regenerate it either, nor did switching revisions off and on again.

Craft CMS 2.6.2788
SEOmatic 1.1.17 
Feed Me 1.4.11

**Comment by khalwat** [comment]
So I fixed this a while ago actually, I just never pushed out a release.  It's in the `develop` branch now, and will be pushed to release in 1.1.18
