### ISSUE TITLE
hreflang not full url

### ISSUE THREAD

**Issue by justkeen** [khalwat/seomatic#82]
The hreflang href does not contain the full entry url. i would expect if this was my english entry www.example.com/this-is-my-entry, the hreflang href for dutch would be www.example.com/nl/this-is-my-entry. Now it prints www.example.com/nl/

**Comment by khalwat** [comment]
hmmm, you're right, according to the spec https://support.google.com/webmasters/answer/189077?hl=en

**Comment by khalwat** [comment]
So I realized the reason I did it this way. I can detect if a site is localizable, but short of loading each entry's localization, I'm not sure there is a way to know which entries are localized and which are not. 

I will look into it a bit deeper.

**Comment by khalwat** [comment]
All of the above should now be fixed; the changes have been checked into the `develop` branch:

https://github.com/nystudio107/seomatic/tree/develop
