### ISSUE TITLE
renderMetrics action URL unable to find the requested action

### ISSUE THREAD

**Issue by john-henry** [khalwat/seomatic#83]
I'm testing the new renderMetrics feature and I couldn't seem to be able to render any metrics. Getting a blank 404 for the metrics pane. 

I can see the URL being called is

`http://domain.local/index.php/actions/seomatic/renderMetrics&url=http://domain.local/blog/my-blog-post-title`

When I visit the URL directly I get the following

> The system is unable to find the requested action "renderMetrics&url=http:"

**Comment by khalwat** [comment]
This is fixed in 1.1.19, which I just pushed out.  Sorry about that.
