### ISSUE TITLE
Make SEOMetric data available somewhere other than live preview

### ISSUE THREAD

**Issue by bossanova808** [khalwat/seomatic#85]
I personally think an extra tab makes the most sense.

Reason: live preview can really grind on long pages, so many avoid it.

**Comment by khalwat** [comment]
So the reason why I decided to attach it to Live Preview was that it seemed to make logical sense to me as a place for the UI.

Additionally, something that's pretty useful is that you can make changes to the site on the left, and it'll be updated in the live preview on the right -- including the statistics for SEOmetrics.

**Comment by bossanova808** [comment]
Sure.  Entirely up to you if you want to support it elsewhere (config item?) but I suspect I won't be alone in desiring it somewhere else.

Awesome work as per usual, anyway, whatever you decide!

**Comment by ajaffarali** [comment]
I completely agree with @bossanova808 - I barely use Live Preview as it bogs it down and would much prefer to have it as an extra tab or button next to the "Preview SEO Meta Display/Tags"

**Comment by khalwat** [comment]
Yeah so the problem with this... and the reason why piggybacking on LivePreview is so nice... is that for the SEOmetrics to work, it needs the context of a _page_ to evaluate.

If it were just in another tab, there would need to be some kind of UI to choose what page to evaluate.  And then you'd often want to see the page in context too (which sounds a lot like Live Preview).

**Comment by kaspar-allenbach** [comment]
Umm `¯\_(ツ)_/¯` Where is this icon in the LivePreview? I can't see it anywhere. Do I have to enable it somewhere?

**Comment by khalwat** [comment]
No, there is nothing to enable.  Simply go to Live Preview, and you should see this icon in the lower-left corner of the screen:

![safariscreensnapz222](https://cloud.githubusercontent.com/assets/7570798/15867015/4006c396-2caf-11e6-912e-171a74ef4da4.png)

If you don't see it, perhaps you are using some CSS with a very high `z-index` or such that might be overlapping it?
