### ISSUE TITLE
Transforming images

### ISSUE THREAD

**Issue by sjelfull** [khalwat/seomatic#87]
The fieldtype is great, and the fact that it can select images from Asset fields is soo good - but it serves the original image file, which can be any size or dimensions.

Could you add a way to set which transform to use, or perhaps just have some settings in the plugin for W x H?

**Comment by khalwat** [comment]
I like the idea of letting people pick a transform.

**Comment by challahan** [comment]
Second vote for this.  My original images are too big so Facebook rejects them.  Just using the logo for now..

**Comment by sjelfull** [comment]
As a temp. solution, I do this:

```
    {% if seomaticMeta.og.image is defined %}
        {% set transformImage = craft.imager.transformImage( seomaticMeta.og.image, { width: 775, height: 405, mode: 'crop' } ) %}
        {% set seomaticMeta = seomaticMeta | merge({
            og: {
                image: transformImage.url,
            }
        }) %}
    {% endif %}
```

**Comment by khalwat** [comment]
This is implemented in the build checked into `develop` for SEO Images, Twitter Images, and OpenGraph images for Site Meta, Template Meta, and Entry Meta:

https://github.com/nystudio107/seomatic/tree/develop
