### ISSUE TITLE
Add Focal Point Image Field type support.

### ISSUE THREAD

**Issue by pixeljitsu** [khalwat/seomatic#88]
Please add support for Focus Point image fields in the SEOmatic custom field type. Right now SEOmatic does not recognize Focus Point as a valid image source.

https://github.com/smcyr/Craft-FocusPoint

I'm pretty much exclusively using Focus Point for any images that have custom crops, so it would be advantageous to be able to have SEOmatic use the Focus Point field for the Social Image.

![fieldedit](https://cloud.githubusercontent.com/assets/2178979/15786546/3815fad4-298b-11e6-9270-df6f5a56c4c5.JPG)

**Comment by khalwat** [comment]
So I looked into this for a bit; it's a really cool idea.  The problem is that FocusPoint doesn't actually generate images.  You have to use it in conjunction with Imager for that to happen.
