### ISSUE TITLE
Section meta

### ISSUE THREAD

**Issue by 0xsven** [khalwat/seomatic#89]
1. I am using only one template file and a big matrix field to generate several pages. Unfortunately SEOmatic overwrites meta tags on a template basis and not on a section basis. Is there a way to change that?
2. I am wondering why you haven't included a sitemap generator? I am no expert so I am wondering how important a sitemap is for a company/product website. Can you recommend a sitemap generator?

**Comment by khalwat** [comment]
Re: 1, yes, you can do whatever you want with Twig: https://github.com/nystudio107/seomatic/wiki/08.-Dynamic-Twig-SEO-Meta

Re: 2, SiteMaps are important.  I'm on the fence as to whether I want to include it in SEOmatic, or leave it to another plugin.  There are a number of them out there that are quite good; here is one: https://github.com/joshuabaker/craft-sitemap
