### ISSUE TITLE
SEO Template Meta not used

### ISSUE THREAD

**Issue by akuales** [khalwat/seomatic#9]
Thank you so much for this great plugin - it's stuff like that, that makes a great CMS like Craft unrivaled.

Unfortunately it seems like there is an issue with displaying SEO Template Meta entries in Version 1.0.8. I always keep getting the default SiteMeta Information in frontend - even though clicking on "Preview SEO Meta Display" and "Preview SEO Meta Tags" shows the correct Template Meta Info.
Everything worked correctly though, when I uninstalled the newest Version of the plugin and installed 1.0.7 instead.
Thanks again for your work!

**Comment by khalwat** [comment]
Well, that's not good.  I will have a look.

**Comment by khalwat** [comment]
okay, I checked in a fix for you:

https://github.com/khalwat/seomatic

lmk...

**Comment by akuales** [comment]
Awesome, thank you very much. Works like a charm!
