### ISSUE TITLE
Ho to use an external image as SEO Image?

### ISSUE THREAD

**Issue by kaspar-allenbach** [khalwat/seomatic#90]
I have a Website with a Webcam Image.

Now I want this image to be in the og:image tag. The problem is, this image is updated every 10 minutes so I can't just add it via an asset field because then it becomes static.

So I tought about adding a textfield where I can write the url of said webcam image. But since the seomatic image field can only use asset fields this falls short.

So my only option is to overwrite the `seomaticMeta.seoImage` tag directely on the template. But how do I do this? 

```
{% if entry.section.handle == 'webcam' %}
      {% set seomaticMeta = seomaticMeta | merge({'seoImage': 'https://domain.com/webcam.jpg' }) %}
{% endif %}
{% hook 'seomaticRender' %}
```

which doesn't work. How do I overwrite the seo image tag?

**Comment by khalwat** [comment]
The above will work; you just need to also do it for the twitter:image and og:image variables.

**Comment by kaspar-allenbach** [comment]
For documentation purposes: 

```
{% set seomaticMeta = seomaticMeta | merge(
    { og: { image: 'https://domain.com/webcam.jpg'} },
    { twitter: { image: 'https://domain.com/webcam.jpg'} }
) %}
```
