### ISSUE TITLE
hreflang implementation

### ISSUE THREAD

**Issue by dommmel** [khalwat/seomatic#91]
Thanks for the awesome plugin!

I noticed that the hreflang implementation is a bit imprecise. I would have submitted a PR but I realized that It cannot be done inside the seo_meta template alone in a performant way and went with a custom implementation instead (in conjunction with a custom language switcher widget)

Nevertheless I wanted to let you know about the problems I found.
1. The current locale [should be listed as well](http://webmasters.stackexchange.com/questions/61534/should-i-include-the-current-language-code-in-link-rel-alternate-hreflang) (this can be done by removing `locale != craft.locale` on [this line](https://github.com/nystudio107/seomatic/blob/6a0c365a658a104228e67f602de4fe18b088797d/templates/_seo_meta.twig#L17)
2. There is no need to strip the region from the locale and use only the langauge as hreflang. This way we loose the ability to localize for e.g. UK, Canada vs. US
3. the hreflang links always point to the siteUrl. Instead they should point to the translated entry itself. This is tricky to solve within your plugin I guess...

Anyway. This is no complain. I hope you find that helpful.

**Comment by khalwat** [comment]
All of the above should now be fixed; the changes have been checked into the `develop` branch:

https://github.com/nystudio107/seomatic/tree/develop

**Comment by khalwat** [comment]
[Added] Added a `getLocalizedUrls` Twig filter/function that returns an array of localized URLs for the current request

As an added bonus, the `getLocalizedUrls` function can be used to generate a language switching menu, if you want it to. :)

**Comment by kaspar-allenbach** [comment]
On that note: The hreflang tag should only be set when a alternate version actually exits. So when there is a language defined but deactivated (See the usecase in my other [bug ticket](https://github.com/nystudio107/seomatic/issues/97)). Then the entire hreflang tag should be stripped from this section.

**Comment by khalwat** [comment]
Checked in a fix that will display ahreflang only if there is more than one language:

https://github.com/nystudio107/seomatic/tree/develop

**Comment by yellostudio** [comment]
From what i can see this is going to spit it out regardless of locale. Google didnt like it when we had this value printed on a site with no other locales setup.

```
{% set localizedUrls = getLocalizedUrls() %}
{% if localizedUrls |length > 0 %}
<link rel="alternate" href="{{ localizedUrls |first }}" hreflang="x-default" />
{% else %}
<link rel="alternate" href="{{ seomaticMeta.canonicalUrl }}" hreflang="x-default" />
{% endif %}
```

**Comment by khalwat** [comment]
Yes, it's fine to have an `x-default` if there are no other languages defined; I have that on my site:

https://nystudio107.com/

If you've updated to the latest SEOmatic, the previous issue should be fixed, but it might take Google a little while to re-crawl your pages.
