### ISSUE TITLE
Configuration isn't applied to old entries

### ISSUE THREAD

**Issue by Macxim** [khalwat/seomatic#93]
Hi, 

Is there a trick I missed which would avoid to manually save each old entries (created before having installed SEOmatic) one by one?

Everything works great for entries created _after_ installing the plugin.

Thanks for your work.

**Comment by khalwat** [comment]
Unfortunately, the way Craft works, when you add a field, it's empty, with no data in it.  That means that SEOmatic FieldTypes don't even have their default values in them (telling them what fields to pull from, etc.).  However, the documentation has a nice shortcut for you to help you do this:

https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

If you add an SEOmatic FieldType to an existing Section that already has entries in it, you'll need to re-save the Section to populate the newly added SEOmatic FieldType with data. You can do this via Settings → Edit My Section → hit Save.

**Comment by Macxim** [comment]
One question though:

In my SEOmatic Meta Field, let's say at first that I wanted the source for the SEO Keywords to be `Custom Text`, now after some time, I change my mind and I want another source (`From field` : xxx).

This modification isn't updated anywhere. Even after saving and re-saving the section.

**Comment by khalwat** [comment]
Yeah you're correct, all the settings for the SEOmatic FieldType do are providing defaults.

It sounds like you might be best suited by using the SEOmatic FieldType, but perhaps also some Twig templating:

https://github.com/nystudio107/seomatic/wiki/08.-Dynamic-Twig-SEO-Meta

**Comment by masiorama** [comment]
I've got the same problem @Macxim has, and I didn't understand your last comment @khalwat .
My situation here is that I'm trying to set a custom Text for the title of my single section, but the newly added configuration (and data) isn't saved at all, as you can see from the gif below... is this an expected behaviour?

![bug](https://cloud.githubusercontent.com/assets/731916/22853070/27c98168-f04c-11e6-90df-9302e6521cb4.gif)

**Comment by scottwakefield** [comment]
I think I'm experiencing the same issue @khalwat; using the latest version of Craft and SEOmatic.

Any change I make on entries isn't saved. Perhaps I'm missing something?

**Comment by scottwakefield** [comment]
All is working fine since updating to 1.1.42! Cheers @khalwat
