### ISSUE TITLE
Variables in Meta Template

### ISSUE THREAD

**Issue by exibit** [khalwat/seomatic#94]
Hi,
I would like to build templates for section where we already have a lot of entries. To avoid to save them once by once to fill in the empty new SEOmatic fields, I tried to build a template.

But I cannot succeed to add variables into the description and title fields. the title tag could be something like {title} - {year} but the template doesn't transform it in real data. However it works fine in an entry.

**How can I solve this ?**

I also report 2 bugs : 
- When you misspell a variable into a SEO title field and you save you got an Internal Server Error. The only way to solve this is to edit it directly into the database or... to delete the entry :-(
- in a Meta template the locales don't work. I have to change the language into my profile to create a template in that language. I have to that for each activated language

**Comment by khalwat** [comment]
So a few things.

First, you can avoid having to re-save each entry by checking out this part of the docs:

https://github.com/nystudio107/seomatic/wiki/05.-SEO-Entry-Meta

> If you add an SEOmatic FieldType to an existing Section that already has entries in it, you'll need to re-save the Section to populate the newly added SEOmatic FieldType with data. You can do this via Settings → Edit My Section → hit Save.

You are correct, there are no variables propagated to the SEO Template Metas; potentially, this might change, but for now that's the case.

As for the bugs, when you say that you misspell a variable in a SEO Title field, which field do you mean?  In the FieldType?  Or some other field?  If it's in a FieldType, I do try to catch errors:

```
                                try
                                {
                                    $entryMeta['seoTitle'] = craft()->templates->renderObjectTemplate($entryMeta['seoTitle'], $element);
                                }
                                catch (Exception $e)
                                {
                                    SeomaticPlugin::log("Template error in the `seoTitle` field.", LogLevel::Info, true);
                                }
```

As for the locales not working in Meta Templates, this is a known issues listed in the Road Map:

> [bug] Get the Template Metas implemented with full locale support, so the settings can all be per-locale based

**Comment by exibit** [comment]
Thank you for your feedback ;-)

**Comment by khalwat** [comment]
Can you tell me where/how you're able to get it to generate an internal server error by misspelling a variable?  What field are you entering something into?  Is it in a FieldType or elsewhere?

**Comment by exibit** [comment]
It's the SEO Title. I added a variable. To solve the problem we made some comments into the template then re-save the content.

**Comment by khalwat** [comment]
yes, but WHERE is the SEO title?  Is this in a FieldType?  Or on the Site Identity settings page?  Where?

**Comment by exibit** [comment]
Here
![capture d ecran 2016-06-21 a 09 06 48](https://cloud.githubusercontent.com/assets/2632397/16220831/8b146132-378f-11e6-8f3c-5a1373150bda.png)

**Comment by khalwat** [comment]
I checked a fix into `develop` that should address this:

https://github.com/nystudio107/seomatic/tree/develop

Give it a try?

**Comment by khalwat** [comment]
Just checked into `develop`:
- [Added] The SEO Title, SEO Description, and SEO Keywords fields in Template Metas can now include tags that output entry properties, such as `{title}` or `{myCustomField}` in them

https://github.com/nystudio107/seomatic/tree/develop
