### ISSUE TITLE
Documentation improvement for SEOmetrics

### ISSUE THREAD

**Issue by dommmel** [khalwat/seomatic#95]
SEOmetrics during Live Preview only works if System Status is set to "on"

Might be worth adding that to the documentation.
I would have submitted a PR for [this wiki page](https://github.com/nystudio107/seomatic/wiki/06.-SEOmetrics-during-Live-Preview). But I can't figure out how to do it. Maybe I can't? Hence this issue.

Thanks for the awesome plugin!

**Comment by khalwat** [comment]
huh.  I didn't know this was the case actually, interesting.

**Comment by khalwat** [comment]
Added it to the docs, thanks!

In the future, I may see if I can work around the restriction.
