### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by kaspar-allenbach** [khalwat/seomatic#97]
I have a site with two locales

de / en

Now I have a section where I have only one language so I deactivated the one unnecessary.
But now the page is inaccessible on the activated locale because of this: 

> Undefined index: en

```
/craft/plugins/seomatic/services/SeomaticService.php(2347)

2335             ->queryAll();
2336 
2337             foreach ($_rows as $row)
2338             {
2339               $path = ($row['uri'] == '__home__') ? '' : $row['uri'];
2340               $unsortedLocalizedUrls[$row['locale']] = UrlHelper::getSiteUrl($path, null, null, $row['locale'] );
2341             }
2342 
2343             $locales = craft()->i18n->getSiteLocales();
2344             foreach ($locales as $locale)
2345             {
2346                 $localeId = $locale->getId();
2347                 $localizedUrls[$localeId] = $unsortedLocalizedUrls[$localeId];
2348             }
2349         }
2350         else
2351         {
2352             $locales = craft()->i18n->getSiteLocales();
2353             foreach ($locales as $locale)
2354             {
2355                 $localeId = $locale->getId();
2356                 $localizedUrls[$localeId] = UrlHelper::getSiteUrl($requestUri, null, null, $localeId);
2357 
2358             }
2359         }
```

I guess this this a bug?
seomatic shouldn't care wether a locale is activated or not.

I'm on the 'https://github.com/nystudio107/seomatic/tree/develop' branch

**Comment by khalwat** [comment]
Great, thanks for the report, I will fix it! :D

**Comment by khalwat** [comment]
I checked a fix into `develop` for you.

**Comment by kaspar-allenbach** [comment]
Great Thank you :smiley:

**Comment by kaspar-allenbach** [comment]
I just updated SEOmatic (and also moved to the master branch) an I get this error again.

**Comment by khalwat** [comment]
You're using 1.1.22 and you're seeing this error?

**Comment by khalwat** [comment]
Okay, I must not have merged that one change.  I've merged it to `develop` and `master` now:

https://github.com/nystudio107/seomatic

Sorry about that.
