### ISSUE TITLE
Twitter Wrong Type

### ISSUE THREAD

**Issue by AbbeyDesign** [khalwat/seomatic#99]
I think your Twitter meta needs to be "name" and not "property".

**Comment by khalwat** [comment]
Wow, that's pretty egregious!  I can't believe I missed that until now (or it worked properly :) ).  I wonder if Twitter changed this spec at some point?  

Anyway, it's fixed in version 1.1.21:

https://github.com/nystudio107/seomatic

Thanks for pointing it out!

**Comment by AbbeyDesign** [comment]
As far as I know, it's always been "name" but Twitter never cared. Surprisingly, it's FaceBook that gets its panties in a wad over Twitter being misnamed.
